//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "APFBaseTask.h"

#import "APBDownloadDelegate-Protocol.h"
#import "IStatusBarDelegate-Protocol.h"

@class AFEAlertView, AFECircularView, APBModelLoader, NSString, UILabel, UIView;

@interface APFModelDownloadTask : APFBaseTask <IStatusBarDelegate, APBDownloadDelegate>
{
    AFECircularView *_circularView;
    UIView *_lomoCircularView;
    UILabel *_loadLable;
    APBModelLoader *_modelLoader;
    long long _retryCount;
    AFEAlertView *_alertView;
}

@property(retain, nonatomic) AFEAlertView *alertView; // @synthesize alertView=_alertView;
@property(nonatomic) long long retryCount; // @synthesize retryCount=_retryCount;
@property(retain, nonatomic) APBModelLoader *modelLoader; // @synthesize modelLoader=_modelLoader;
@property(nonatomic) __weak UILabel *loadLable; // @synthesize loadLable=_loadLable;
@property(nonatomic) __weak UIView *lomoCircularView; // @synthesize lomoCircularView=_lomoCircularView;
@property(nonatomic) __weak AFECircularView *circularView; // @synthesize circularView=_circularView;
- (void).cxx_destruct;
- (void)downloadFailedwithError:(id)arg1;
- (void)downloadSucceedwithFilePath:(id)arg1;
- (void)onDownloadProgressUpdate:(float)arg1;
- (void)_showAlertViewBy:(id)arg1;
- (void)onButtonCancel;
- (void)setLable:(id)arg1 lineSpacing:(double)arg2;
- (_Bool)_prepareCircularView:(id)arg1;
- (void)setupViewswithPipInfo:(id)arg1;
- (void)exitWithResult:(int)arg1 failReason:(id)arg2;
- (void)processEvent:(id)arg1 withCompletionCallback:(CDUnknownBlockType)arg2;
- (void)invokeWithPipeInfo:(id)arg1;
- (void)reset;
- (void)_setUp;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

