//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface APLogTrackManager : NSObject
{
}

+ (id)pageInfoWithIndex:(id)arg1;
+ (void)logAutoClickWithContext:(id)arg1;
+ (void)logPageUpdateWithIndex:(id)arg1 context:(id)arg2 updateType:(int)arg3;
+ (void)logPageUpdateWithIndex:(id)arg1 context:(id)arg2;
+ (void)logPageEndWithIndex:(id)arg1;
+ (void)logPageStartWithIndex:(id)arg1 context:(id)arg2;

@end

