//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "BKPasscodeFieldDelegate-Protocol.h"
#import "NSCopying-Protocol.h"
#import "UITextFieldDelegate-Protocol.h"

@class NSString, UIControl, UILabel;
@protocol BKPasscodeInputViewDelegate;

@interface BKPasscodeInputView : UIView <UITextFieldDelegate, BKPasscodeFieldDelegate, NSCopying>
{
    _Bool _isKeyboardTypeSet;
    _Bool _enabled;
    unsigned long long _maximumLength;
    long long _keyboardType;
    UIControl *_passcodeField;
    id <BKPasscodeInputViewDelegate> _delegate;
    unsigned long long _passcodeStyle;
    UILabel *_titleLabel;
    UILabel *_messageLabel;
    UILabel *_errorMessageLabel;
}

+ (void)configureErrorMessageLabel:(id)arg1;
+ (void)configureMessageLabel:(id)arg1;
+ (void)configureTitleLabel:(id)arg1;
@property(retain, nonatomic) UILabel *errorMessageLabel; // @synthesize errorMessageLabel=_errorMessageLabel;
@property(retain, nonatomic) UILabel *messageLabel; // @synthesize messageLabel=_messageLabel;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(nonatomic, getter=isEnabled) _Bool enabled; // @synthesize enabled=_enabled;
@property(nonatomic) unsigned long long passcodeStyle; // @synthesize passcodeStyle=_passcodeStyle;
@property(nonatomic) __weak id <BKPasscodeInputViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) long long keyboardType; // @synthesize keyboardType=_keyboardType;
@property(nonatomic) unsigned long long maximumLength; // @synthesize maximumLength=_maximumLength;
- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (_Bool)textFieldShouldReturn:(id)arg1;
- (_Bool)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (_Bool)passcodeFieldShouldDeleteBackward:(id)arg1;
- (_Bool)passcodeField:(id)arg1 shouldInsertText:(id)arg2;
- (void)passcodeControlEditingChanged:(id)arg1;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (_Bool)canResignFirstResponder;
- (_Bool)becomeFirstResponder;
- (_Bool)canBecomeFirstResponder;
- (void)layoutSubviews;
- (double)labelPasscodeSpace;
@property(retain, nonatomic) NSString *passcode;
@property(retain, nonatomic) NSString *errorMessage;
@property(retain, nonatomic) NSString *message;
@property(retain, nonatomic) NSString *title;
@property(retain, nonatomic) UIControl *passcodeField; // @synthesize passcodeField=_passcodeField;
- (void)_initialize;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

