//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class BLAssetPickerPresenter, BLPhotoAlbumInteractor, UINavigationController;

@interface BLAssetPickerStoryboard : NSObject
{
    BLAssetPickerPresenter *_presenter;
    BLPhotoAlbumInteractor *_interactor;
    UINavigationController *_rootNavViewController;
}

@property(retain, nonatomic) UINavigationController *rootNavViewController; // @synthesize rootNavViewController=_rootNavViewController;
@property(retain, nonatomic) BLPhotoAlbumInteractor *interactor; // @synthesize interactor=_interactor;
@property(retain, nonatomic) BLAssetPickerPresenter *presenter; // @synthesize presenter=_presenter;
- (void).cxx_destruct;
- (id)photosPickerInterface;
- (id)albumsInterface;
- (void)dismissAssetsPicker;
- (void)confirmPickAssets;
- (void)openPhotoPickerInterface;
- (void)openAssetAblumsPickerFrom:(id)arg1 withDelegate:(id)arg2;
- (id)init;

@end

