//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "BLBaseAPIModel.h"

@class NSNumber;

@interface BLCalendarExceptionDateAPIModel : BLBaseAPIModel
{
    NSNumber *_dateTime;
}

@property(retain, nonatomic) NSNumber *dateTime; // @synthesize dateTime=_dateTime;
- (void).cxx_destruct;
- (id)toDictionary;
- (id)initWithDictionary:(id)arg1;

@end

