//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "BLContentAPIResponse.h"

@interface BLContentDownloadAPIResponse : BLContentAPIResponse
{
    unsigned long long _contentLength;
    unsigned long long _contentRangeStart;
    unsigned long long _contentRangeEnd;
}

@property(nonatomic) unsigned long long contentRangeEnd; // @synthesize contentRangeEnd=_contentRangeEnd;
@property(nonatomic) unsigned long long contentRangeStart; // @synthesize contentRangeStart=_contentRangeStart;
@property(nonatomic) unsigned long long contentLength; // @synthesize contentLength=_contentLength;
- (id)initWithHeaderFields:(id)arg1;

@end

