//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSDictionary, NSString;

@interface BLDentrySimple : NSObject
{
    NSString *_spaceId;
    NSString *_spaceName;
    NSString *_path;
    NSString *_itemId;
    NSString *_fileName;
    NSString *_fileType;
    unsigned long long _fileSize;
    unsigned long long _type;
    long long _accessType;
    unsigned long long _encryptStatus;
}

@property(nonatomic) unsigned long long encryptStatus; // @synthesize encryptStatus=_encryptStatus;
@property(nonatomic) long long accessType; // @synthesize accessType=_accessType;
@property(nonatomic) unsigned long long type; // @synthesize type=_type;
@property(nonatomic) unsigned long long fileSize; // @synthesize fileSize=_fileSize;
@property(copy, nonatomic) NSString *fileType; // @synthesize fileType=_fileType;
@property(copy, nonatomic) NSString *fileName; // @synthesize fileName=_fileName;
@property(copy, nonatomic) NSString *itemId; // @synthesize itemId=_itemId;
@property(copy, nonatomic) NSString *path; // @synthesize path=_path;
@property(copy, nonatomic) NSString *spaceName; // @synthesize spaceName=_spaceName;
@property(copy, nonatomic) NSString *spaceId; // @synthesize spaceId=_spaceId;
- (void).cxx_destruct;
@property(retain, nonatomic) NSDictionary *extraDic;

@end

