//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "BLBaseAPIModel.h"

@class NSArray, NSString;

@interface BLDomainAPIModel : BLBaseAPIModel
{
    NSString *_domainID;
    NSString *_name;
    NSArray *_roles;
}

@property(retain, nonatomic) NSArray *roles; // @synthesize roles=_roles;
@property(retain, nonatomic) NSString *name; // @synthesize name=_name;
@property(retain, nonatomic) NSString *domainID; // @synthesize domainID=_domainID;
- (void).cxx_destruct;
- (id)initWithDictionary:(id)arg1;

@end

