//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSString;

@protocol BLEditorHeaderViewProtocol <NSObject>
- (_Bool)headerHasChanged;
- (NSString *)subjectText;
- (void)setSubjectText:(NSString *)arg1;
- (_Bool)headerBecomeFirshtResponder;
- (void)headerResignFirstResponder;
- (void)setFrame:(struct CGRect)arg1;
- (struct CGRect)frame;
- (void)setEditorHeaderViewDelegate:(id)arg1;
@end

