//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface BLKeyChainHelper : NSObject
{
}

+ (void)postLogEventNotificationWithMessage:(id)arg1;
+ (id)getStringForService:(id)arg1 account:(id)arg2;
+ (id)getStringForKey:(id)arg1;
+ (_Bool)setString:(id)arg1 forKey:(id)arg2 shouldBackupInDefaults:(_Bool)arg3;
+ (_Bool)setString:(id)arg1 forKey:(id)arg2;
+ (id)appName;

@end

