//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSDate, NSString;

@protocol BLMailOperationInterface <NSObject>

@optional
- (void)showReplayForwardOptions:(_Bool)arg1;
- (void)setToolBarItemsType:(long long)arg1;
- (void)showDatePickerWithSelectedDate:(NSDate *)arg1;
- (void)updateReminderTime:(NSString *)arg1;
- (void)showReminderPopupView:(_Bool)arg1;
- (void)updateFlagIconWithType:(long long)arg1;
@end

