//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSDate, NSString;

@interface BLReminderItem : NSObject
{
    NSString *_reminderType;
    NSString *_reminderDateString;
    NSDate *_reminderDate;
}

@property(retain, nonatomic) NSDate *reminderDate; // @synthesize reminderDate=_reminderDate;
@property(retain, nonatomic) NSString *reminderDateString; // @synthesize reminderDateString=_reminderDateString;
@property(retain, nonatomic) NSString *reminderType; // @synthesize reminderType=_reminderType;
- (void).cxx_destruct;

@end

