//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "UIWebViewDelegate-Protocol.h"

@class NSArray, NSString, UIWebView;
@protocol BLSDKLoginViewDelegate;

@interface BLSDKLoginView : UIView <UIWebViewDelegate>
{
    _Bool _canModify;
    _Bool _isFirstLoad;
    NSString *_clientId;
    NSString *_defaultEmail;
    NSArray *_emailList;
    NSString *_lang;
    id <BLSDKLoginViewDelegate> _delegate;
    UIWebView *_webView;
    long long _state;
}

@property(nonatomic) _Bool isFirstLoad; // @synthesize isFirstLoad=_isFirstLoad;
@property(nonatomic) long long state; // @synthesize state=_state;
@property(retain, nonatomic) UIWebView *webView; // @synthesize webView=_webView;
@property(nonatomic) __weak id <BLSDKLoginViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) _Bool canModify; // @synthesize canModify=_canModify;
@property(retain, nonatomic) NSString *lang; // @synthesize lang=_lang;
@property(retain, nonatomic) NSArray *emailList; // @synthesize emailList=_emailList;
@property(copy, nonatomic) NSString *defaultEmail; // @synthesize defaultEmail=_defaultEmail;
@property(copy, nonatomic) NSString *clientId; // @synthesize clientId=_clientId;
- (void).cxx_destruct;
- (void)webView:(id)arg1 didFailLoadWithError:(id)arg2;
- (void)webViewDidFinishLoad:(id)arg1;
- (void)webViewDidStartLoad:(id)arg1;
- (_Bool)webView:(id)arg1 shouldStartLoadWithRequest:(id)arg2 navigationType:(long long)arg3;
- (_Bool)isRedirectError:(id)arg1;
- (void)checkCode:(id)arg1;
- (void)goBack;
- (_Bool)canGoBack;
- (void)startLoad;
- (id)oauthParam;
- (id)bizParam;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

