//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "BLCancelable-Protocol.h"

@class NSArray, NSString;

@interface BLTaskCancelHandler : NSObject <BLCancelable>
{
    NSString *_taskId;
    NSArray *_taskIds;
}

@property(copy, nonatomic) NSArray *taskIds; // @synthesize taskIds=_taskIds;
@property(copy, nonatomic) NSString *taskId; // @synthesize taskId=_taskId;
- (void).cxx_destruct;
- (void)cancel;
- (id)initWithTaskIds:(id)arg1;
- (id)initWithTaskId:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

