//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface CommonUtility : NSObject
{
}

+ (id)getLastLocation;
+ (void)saveLastLocation:(id)arg1;
+ (struct MAMapRect)minMapRectForAnnotations:(id)arg1;
+ (struct MAMapRect)minMapRectForMapPoints:(struct MAMapPoint *)arg1 count:(unsigned long long)arg2;
+ (struct MAMapRect)mapRectForOverlays:(id)arg1;
+ (struct MAMapRect)mapRectUnion:(struct MAMapRect *)arg1 count:(unsigned long long)arg2;
+ (struct MAMapRect)unionMapRect1:(struct MAMapRect)arg1 mapRect2:(struct MAMapRect)arg2;
+ (id)polylinesForTransit:(id)arg1;
+ (void)replenishPolylinesForTransit:(id)arg1 CurrentSegment:(id)arg2 Polylines:(id)arg3;
+ (id)polylinesForPath:(id)arg1;
+ (void)replenishPolylinesForPathWith:(id)arg1 lastPolyline:(id)arg2 Polylines:(id)arg3;
+ (id)polylinesForSegment:(id)arg1;
+ (void)replenishPolylinesForSegment:(id)arg1 busLinePolyline:(id)arg2 Segment:(id)arg3 polylines:(id)arg4;
+ (id)polylinesForWalking:(id)arg1;
+ (void)replenishPolylinesForWalkingWiht:(id)arg1 LastPolyline:(id)arg2 Polylines:(id)arg3 Walking:(id)arg4;
+ (id)polylineForBusLine:(id)arg1;
+ (id)polylineForStep:(id)arg1;
+ (id)polylineForCoordinateString:(id)arg1;
+ (struct CLLocationCoordinate2D *)coordinatesForString:(id)arg1 coordinateCount:(unsigned long long *)arg2 parseToken:(id)arg3;

@end

