//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "Marshal.h"

@class NSString;

@interface DTAdsAlertStyleModel : Marshal
{
    NSString *_mediaId;
    NSString *_title;
    NSString *_text;
    NSString *_actText1;
    NSString *_actUrl1;
    NSString *_actText2;
    NSString *_actUrl2;
}

@property(copy, nonatomic) NSString *actUrl2; // @synthesize actUrl2=_actUrl2;
@property(copy, nonatomic) NSString *actText2; // @synthesize actText2=_actText2;
@property(copy, nonatomic) NSString *actUrl1; // @synthesize actUrl1=_actUrl1;
@property(copy, nonatomic) NSString *actText1; // @synthesize actText1=_actText1;
@property(copy, nonatomic) NSString *text; // @synthesize text=_text;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(copy, nonatomic) NSString *mediaId; // @synthesize mediaId=_mediaId;
- (void).cxx_destruct;
- (id)filedsMeta__;
- (id)init;

@end

