//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSArray, NSAttributedString, NSString, UIImage;

@interface DTAlertPopViewModel : NSObject
{
    _Bool _showSubtitleHor;
    _Bool _animationing;
    double _normalHeight;
    long long _type;
    NSString *_title;
    UIImage *_titleLoadingImage;
    NSString *_subTitle;
    NSString *_content;
    NSAttributedString *_contentAttribute;
    UIImage *_image;
    NSString *_imageDescrible;
    NSArray *_images;
    NSArray *_subTitles;
    NSArray *_contentAttributes;
    double _animationDuration;
    CDUnknownBlockType _animationCompletion;
}

@property(copy, nonatomic) CDUnknownBlockType animationCompletion; // @synthesize animationCompletion=_animationCompletion;
@property(nonatomic) double animationDuration; // @synthesize animationDuration=_animationDuration;
@property(copy, nonatomic) NSArray *contentAttributes; // @synthesize contentAttributes=_contentAttributes;
@property(copy, nonatomic) NSArray *subTitles; // @synthesize subTitles=_subTitles;
@property(copy, nonatomic) NSArray *images; // @synthesize images=_images;
@property(nonatomic) _Bool animationing; // @synthesize animationing=_animationing;
@property(copy, nonatomic) NSString *imageDescrible; // @synthesize imageDescrible=_imageDescrible;
@property(retain, nonatomic) UIImage *image; // @synthesize image=_image;
@property(copy, nonatomic) NSAttributedString *contentAttribute; // @synthesize contentAttribute=_contentAttribute;
@property(copy, nonatomic) NSString *content; // @synthesize content=_content;
@property(nonatomic) _Bool showSubtitleHor; // @synthesize showSubtitleHor=_showSubtitleHor;
@property(copy, nonatomic) NSString *subTitle; // @synthesize subTitle=_subTitle;
@property(retain, nonatomic) UIImage *titleLoadingImage; // @synthesize titleLoadingImage=_titleLoadingImage;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(nonatomic) long long type; // @synthesize type=_type;
@property(nonatomic) double normalHeight; // @synthesize normalHeight=_normalHeight;
- (void).cxx_destruct;
- (id)init;

@end

