//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "DTViewController.h"

#import "UITextFieldDelegate-Protocol.h"

@class NSString, UILabel, UITextField, WKIDLJoinGroupValidationModel;

@interface DTApplyJoinGroupViewController : DTViewController <UITextFieldDelegate>
{
    UITextField *_inputTextField;
    UILabel *_subtitleLabel;
    _Bool _onSendingApplyRequest;
    WKIDLJoinGroupValidationModel *_joinGroupModel;
    CDUnknownBlockType _didApplyBlock;
}

@property(copy, nonatomic) CDUnknownBlockType didApplyBlock; // @synthesize didApplyBlock=_didApplyBlock;
@property(retain, nonatomic) WKIDLJoinGroupValidationModel *joinGroupModel; // @synthesize joinGroupModel=_joinGroupModel;
- (void).cxx_destruct;
- (_Bool)isValidMessageContent:(id)arg1;
- (void)sendApplyJoinGroupRequest;
- (void)didTapSend:(id)arg1;
- (void)didTapCancel:(id)arg1;
- (id)formatPlaceholder;
- (void)showPlaceholder;
- (void)setupViewComponents;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

