//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "DTAttendLocationUpdataDelegate-Protocol.h"
#import "DTMapViewControllerDelegate-Protocol.h"

@class DTAttendAssistantViewController, DTUserPositionModel, NSString, UINavigationController;

@interface DTAttendAssistant : NSObject <DTMapViewControllerDelegate, DTAttendLocationUpdataDelegate>
{
    NSString *_corpId;
    UINavigationController *_naviViewController;
    long long _mapPickStatus;
    DTUserPositionModel *_originPositionModel;
    DTUserPositionModel *_destPositionModel;
    DTAttendAssistantViewController *_attAssistViewController;
}

+ (void)showAttendAssistantWithCorpId:(id)arg1 naviController:(id)arg2;
@property(retain, nonatomic) DTAttendAssistantViewController *attAssistViewController; // @synthesize attAssistViewController=_attAssistViewController;
@property(retain, nonatomic) DTUserPositionModel *destPositionModel; // @synthesize destPositionModel=_destPositionModel;
@property(retain, nonatomic) DTUserPositionModel *originPositionModel; // @synthesize originPositionModel=_originPositionModel;
@property(nonatomic) long long mapPickStatus; // @synthesize mapPickStatus=_mapPickStatus;
@property(retain, nonatomic) UINavigationController *naviViewController; // @synthesize naviViewController=_naviViewController;
@property(copy, nonatomic) NSString *corpId; // @synthesize corpId=_corpId;
- (void).cxx_destruct;
- (void)mapViewControllerDidCancel:(id)arg1;
- (void)mapViewController:(id)arg1 didFailWithCode:(long long)arg2 error:(id)arg3;
- (void)mapViewController:(id)arg1 didUpdatePOI:(id)arg2;
- (void)updateDestinationLocationForAssistantController:(id)arg1 originPositionModel:(id)arg2 destPositionModel:(id)arg3;
- (void)updateOriginLocationForAssistantController:(id)arg1 originPositionModel:(id)arg2 destPositionModel:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

