//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSString;

@interface DTAvatarListViewItem : NSObject
{
    long long _uid;
    long long _orgId;
    NSString *_name;
    NSString *_avatarMediaId;
}

@property(copy, nonatomic) NSString *avatarMediaId; // @synthesize avatarMediaId=_avatarMediaId;
@property(nonatomic) NSString *name; // @synthesize name=_name;
@property(nonatomic) long long orgId; // @synthesize orgId=_orgId;
@property(nonatomic) long long uid; // @synthesize uid=_uid;
- (void).cxx_destruct;

@end

