//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "DTBaseCell.h"

@class DTBannerCellItem, UIImageView;

@interface DTBannerCell : DTBaseCell
{
    DTBannerCellItem *_cellItem;
    UIImageView *_bannerImageView;
}

@property(retain, nonatomic) UIImageView *bannerImageView; // @synthesize bannerImageView=_bannerImageView;
@property(retain, nonatomic) DTBannerCellItem *cellItem; // @synthesize cellItem=_cellItem;
- (void).cxx_destruct;
- (void)layoutSubViewsForCell;
- (void)configCellWithItem:(id)arg1;
- (void)prepareForCellReuse;
- (id)initWithReuseIdentifier:(id)arg1;

@end

