//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSString;

@interface DTBizRedEnvelopFlow : NSObject
{
    _Bool _isLuck;
    int _flowId;
    long long _createTime;
    long long _modifyTime;
    long long _sender;
    NSString *_clusterId;
    NSString *_amount;
    long long _receiver;
    long long _status;
    NSString *_leaveMessage;
}

@property(nonatomic) _Bool isLuck; // @synthesize isLuck=_isLuck;
@property(copy, nonatomic) NSString *leaveMessage; // @synthesize leaveMessage=_leaveMessage;
@property(nonatomic) long long status; // @synthesize status=_status;
@property(nonatomic) long long receiver; // @synthesize receiver=_receiver;
@property(copy, nonatomic) NSString *amount; // @synthesize amount=_amount;
@property(nonatomic) int flowId; // @synthesize flowId=_flowId;
@property(copy, nonatomic) NSString *clusterId; // @synthesize clusterId=_clusterId;
@property(nonatomic) long long sender; // @synthesize sender=_sender;
@property(nonatomic) long long modifyTime; // @synthesize modifyTime=_modifyTime;
@property(nonatomic) long long createTime; // @synthesize createTime=_createTime;
- (void).cxx_destruct;

@end

