//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSString;

@interface DTBizAttendeeModel : NSObject
{
    NSString *_alias;
    long long _uid;
    long long _attendStatus;
    NSString *_address;
}

@property(copy, nonatomic) NSString *address; // @synthesize address=_address;
@property(nonatomic) long long attendStatus; // @synthesize attendStatus=_attendStatus;
@property(nonatomic) long long uid; // @synthesize uid=_uid;
@property(copy, nonatomic) NSString *alias; // @synthesize alias=_alias;
- (void).cxx_destruct;

@end

