//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSString;

@interface DTBroadcastRequest : NSObject
{
    id _adData;
    NSString *_adKey;
    CDUnknownBlockType _finishBlock;
}

+ (id)requestWithADData:(id)arg1 adKey:(id)arg2 finishBlock:(CDUnknownBlockType)arg3;
@property(copy, nonatomic) CDUnknownBlockType finishBlock; // @synthesize finishBlock=_finishBlock;
@property(copy, nonatomic) NSString *adKey; // @synthesize adKey=_adKey;
@property(retain, nonatomic) id adData; // @synthesize adData=_adData;
- (void).cxx_destruct;

@end

