//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "DTViewController.h"

#import "BusinessConfHeaderDelegate-Protocol.h"
#import "BusinessConfMeberDelegate-Protocol.h"
#import "DTVideoConferencePreCellDataSource-Protocol.h"
#import "MFMessageComposeViewControllerDelegate-Protocol.h"
#import "UICollectionViewDataSource-Protocol.h"
#import "UICollectionViewDelegate-Protocol.h"

@class AVAudioPlayer, DTAlertView, DTBadgeView, DTBusinessConfChairPersonHeaderView, DTBusinessConfSummaryView, DTBusinessConfUserTipView, NSArray, NSString, NSTimer, UIAlertView, UIButton, UICollectionView, UICollectionViewFlowLayout, UIImageView, UILabel, UIView;

@interface DTBusinessConferenceViewController : DTViewController <UICollectionViewDelegate, UICollectionViewDataSource, BusinessConfMeberDelegate, DTVideoConferencePreCellDataSource, BusinessConfHeaderDelegate, MFMessageComposeViewControllerDelegate>
{
    _Bool _itemSelected;
    _Bool _clear;
    _Bool _amIConnected;
    _Bool _showLocalAPN;
    unsigned long long _from;
    unsigned long long _viewState;
    UICollectionView *_collectionView;
    UICollectionViewFlowLayout *_collectionLayout;
    UICollectionView *_preCollectionView;
    UICollectionViewFlowLayout *_preCollectionLayout;
    NSString *_preTitle;
    NSArray *_memberArrays;
    NSArray *_preMemberArrays;
    UIButton *_terminateConfButton;
    UIButton *_exitConfButton;
    UIView *_customNaviBar;
    UIButton *_muteAllButton;
    UIButton *_confTextButton;
    UIButton *_confReadyButton;
    UILabel *_confReadyButtonLabel;
    UIImageView *_maskView;
    UIAlertView *_kickoutAlert;
    UIAlertView *_terminateAlert;
    UIAlertView *_leaveAlert;
    UIAlertView *_warnAlert;
    UIAlertView *_errAlert;
    UIAlertView *_networkAlert;
    DTAlertView *_callingAlert;
    NSArray *_eventsArray;
    DTBusinessConfChairPersonHeaderView *_headerView;
    AVAudioPlayer *_player;
    DTBusinessConfUserTipView *_conferenceTipView;
    long long _startTimeStamp;
    DTBadgeView *_drafImageView;
    DTBusinessConfSummaryView *_summaryView;
    DTBusinessConfSummaryView *_smsContentView;
    NSTimer *_timer;
    long long _orientation;
}

@property(nonatomic) long long orientation; // @synthesize orientation=_orientation;
@property(retain, nonatomic) NSTimer *timer; // @synthesize timer=_timer;
@property(retain, nonatomic) DTBusinessConfSummaryView *smsContentView; // @synthesize smsContentView=_smsContentView;
@property(retain, nonatomic) DTBusinessConfSummaryView *summaryView; // @synthesize summaryView=_summaryView;
@property(retain, nonatomic) DTBadgeView *drafImageView; // @synthesize drafImageView=_drafImageView;
@property(nonatomic) long long startTimeStamp; // @synthesize startTimeStamp=_startTimeStamp;
@property(retain, nonatomic) DTBusinessConfUserTipView *conferenceTipView; // @synthesize conferenceTipView=_conferenceTipView;
@property(nonatomic) _Bool showLocalAPN; // @synthesize showLocalAPN=_showLocalAPN;
@property(nonatomic) _Bool amIConnected; // @synthesize amIConnected=_amIConnected;
@property(retain, nonatomic) AVAudioPlayer *player; // @synthesize player=_player;
@property(retain, nonatomic) DTBusinessConfChairPersonHeaderView *headerView; // @synthesize headerView=_headerView;
@property(retain, nonatomic) NSArray *eventsArray; // @synthesize eventsArray=_eventsArray;
@property(nonatomic) _Bool clear; // @synthesize clear=_clear;
@property(retain, nonatomic) DTAlertView *callingAlert; // @synthesize callingAlert=_callingAlert;
@property(retain, nonatomic) UIAlertView *networkAlert; // @synthesize networkAlert=_networkAlert;
@property(retain, nonatomic) UIAlertView *errAlert; // @synthesize errAlert=_errAlert;
@property(retain, nonatomic) UIAlertView *warnAlert; // @synthesize warnAlert=_warnAlert;
@property(retain, nonatomic) UIAlertView *leaveAlert; // @synthesize leaveAlert=_leaveAlert;
@property(retain, nonatomic) UIAlertView *terminateAlert; // @synthesize terminateAlert=_terminateAlert;
@property(retain, nonatomic) UIAlertView *kickoutAlert; // @synthesize kickoutAlert=_kickoutAlert;
@property(retain, nonatomic) UIImageView *maskView; // @synthesize maskView=_maskView;
@property(retain, nonatomic) UILabel *confReadyButtonLabel; // @synthesize confReadyButtonLabel=_confReadyButtonLabel;
@property(retain, nonatomic) UIButton *confReadyButton; // @synthesize confReadyButton=_confReadyButton;
@property(retain, nonatomic) UIButton *confTextButton; // @synthesize confTextButton=_confTextButton;
@property(retain, nonatomic) UIButton *muteAllButton; // @synthesize muteAllButton=_muteAllButton;
@property(retain, nonatomic) UIView *customNaviBar; // @synthesize customNaviBar=_customNaviBar;
@property(retain, nonatomic) UIButton *exitConfButton; // @synthesize exitConfButton=_exitConfButton;
@property(retain, nonatomic) UIButton *terminateConfButton; // @synthesize terminateConfButton=_terminateConfButton;
@property(nonatomic, getter=isItemSelected) _Bool itemSelected; // @synthesize itemSelected=_itemSelected;
@property(retain, nonatomic) NSArray *preMemberArrays; // @synthesize preMemberArrays=_preMemberArrays;
@property(retain, nonatomic) NSArray *memberArrays; // @synthesize memberArrays=_memberArrays;
@property(retain, nonatomic) NSString *preTitle; // @synthesize preTitle=_preTitle;
@property(retain, nonatomic) UICollectionViewFlowLayout *preCollectionLayout; // @synthesize preCollectionLayout=_preCollectionLayout;
@property(retain, nonatomic) UICollectionView *preCollectionView; // @synthesize preCollectionView=_preCollectionView;
@property(retain, nonatomic) UICollectionViewFlowLayout *collectionLayout; // @synthesize collectionLayout=_collectionLayout;
@property(retain, nonatomic) UICollectionView *collectionView; // @synthesize collectionView=_collectionView;
@property(nonatomic) unsigned long long viewState; // @synthesize viewState=_viewState;
@property(nonatomic) unsigned long long from; // @synthesize from=_from;
- (void).cxx_destruct;
- (void)handleActionSheet:(id)arg1 buttonIndex:(long long)arg2 buttonTitle:(id)arg3 member:(id)arg4;
- (void)avatarPressed:(id)arg1;
- (void)specialPressed;
- (unsigned long long)memberCount;
- (void)entryPwd:(id)arg1;
- (void)messageComposeViewController:(id)arg1 didFinishWithResult:(long long)arg2;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (id)collectionView:(id)arg1 viewForSupplementaryElementOfKind:(id)arg2 atIndexPath:(id)arg3;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (void)unReceiveCall;
- (void)startTimerDetective;
- (void)sendSingleMessage:(id)arg1 otherUid:(long long)arg2;
- (void)sendDingMessageWithContent:(id)arg1;
- (void)sendMessageWithContent:(id)arg1;
- (void)cancelShakeStatus;
- (void)removeMember:(id)arg1;
- (CDUnknownBlockType)contactPicked;
- (void)addMember;
- (void)terminateConf;
- (void)leaveConf;
- (void)muteAll:(id)arg1;
- (void)readyStartConf:(id)arg1;
- (void)sendMessage:(id)arg1 conversationId:(id)arg2 tag:(long long)arg3;
- (void)changeConversationTitle:(id)arg1 oldTitle:(id)arg2;
- (void)updateDraft:(id)arg1 conversationId:(id)arg2;
- (void)sendMessageToGroup:(id)arg1;
- (void)sendMessageToMyself:(id)arg1 send:(_Bool)arg2;
- (void)confText;
- (void)exitConference;
- (void)resetView;
- (void)checkHangUp;
- (void)localNoti;
- (void)dismissNetErrorAlert;
- (void)showNetErrorAlert:(id)arg1 message:(id)arg2;
- (void)refreshHeaderView;
- (void)reloadConf:(id)arg1 forceClear:(_Bool)arg2;
- (void)reloadLayout:(id)arg1;
- (void)teleCallStatus:(id)arg1;
- (void)showLocalAPN:(id)arg1;
- (double)getMainContentAreaY;
- (double)getCurrentViewAreaY;
- (void)viewWillLayoutSubviews;
- (void)loadConferenceCallBack;
- (void)changeNavigationBarByViewState:(unsigned long long)arg1;
- (void)switchViewState:(unsigned long long)arg1;
- (void)loadCompoment;
- (void)didReceiveMemoryWarning;
- (void)willMoveToParentViewController:(id)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)init;
- (void)dealloc;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

