//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "DTBaseCell.h"

@class DTBusinessContactCellItem, DTTimeLineView, UIButton, UIImageView, UILabel, YYLabel;

@interface DTBusinessContactCell : DTBaseCell
{
    DTTimeLineView *_timeLineView;
    YYLabel *_titleLabel;
    UILabel *_contentLabel;
    UIButton *_showMoreButton;
    DTBusinessContactCellItem *_item;
    UIImageView *_indicatorImageView;
}

+ (double)calculateHeightWithItem:(id)arg1;
+ (double)titleHeightWithItem:(id)arg1 maxWidth:(double)arg2 needShowMore:(_Bool *)arg3;
+ (id)attriStringFontWithText:(id)arg1 formatList:(id)arg2;
+ (unsigned long long)numberOfRowsWithItem:(id)arg1 maxWidth:(double)arg2 totalHeight:(double *)arg3;
@property(retain, nonatomic) UIImageView *indicatorImageView; // @synthesize indicatorImageView=_indicatorImageView;
@property(retain, nonatomic) DTBusinessContactCellItem *item; // @synthesize item=_item;
@property(retain, nonatomic) UIButton *showMoreButton; // @synthesize showMoreButton=_showMoreButton;
@property(retain, nonatomic) UILabel *contentLabel; // @synthesize contentLabel=_contentLabel;
@property(retain, nonatomic) YYLabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) DTTimeLineView *timeLineView; // @synthesize timeLineView=_timeLineView;
- (void).cxx_destruct;
- (void)showMoreButtonAction;
- (void)configCellWithItem:(id)arg1;
- (void)layoutSubViewsForCell;
- (id)initWithCellItem:(id)arg1;

@end

