//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "Marshal.h"

#import "JSONCollectionType-Protocol.h"

@class DTCallManageJumpModel, NSArray, NSString;

@interface DTCallManageCardMiddleModel : Marshal <JSONCollectionType>
{
    NSString *_mediaId;
    DTCallManageJumpModel *_jumpModel;
    NSArray *_details;
}

@property(copy, nonatomic) NSArray *details; // @synthesize details=_details;
@property(retain, nonatomic) DTCallManageJumpModel *jumpModel; // @synthesize jumpModel=_jumpModel;
@property(copy, nonatomic) NSString *mediaId; // @synthesize mediaId=_mediaId;
- (void).cxx_destruct;
- (id)filedsMeta__;
- (id)init;
- (Class)arrayElementTypeForFieldName:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

