//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIButton;

@interface DTCertifyView : UIView
{
    UIButton *_certifyButton;
    UIButton *_whitePaperButton;
    CDUnknownBlockType _clickBlock;
}

@property(copy, nonatomic) CDUnknownBlockType clickBlock; // @synthesize clickBlock=_clickBlock;
@property(retain, nonatomic) UIButton *whitePaperButton; // @synthesize whitePaperButton=_whitePaperButton;
@property(retain, nonatomic) UIButton *certifyButton; // @synthesize certifyButton=_certifyButton;
- (void).cxx_destruct;
- (void)whitePapaerClicked;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

