//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "OpenModel.h"

#import "DTCMailFolderTagAdapter-Protocol.h"
#import "OpenModelProtocol-Protocol.h"

@class BLAccount, NSString;

@interface DTCFolder : OpenModel <DTCMailFolderTagAdapter, OpenModelProtocol>
{
    _Bool _shouldPush;
    _Bool _isLocalFolder;
    _Bool _hasMore;
    long long _uuid;
    NSString *_syncKey;
    NSString *_folderID;
    long long _type;
    long long _groupType;
    NSString *_name;
    NSString *_parentID;
    long long _level;
    long long _lastVisitDate;
    long long _ancestorType;
    NSString *_oldestItemID;
    NSString *_path;
    NSString *_folderAcl;
    NSString *_ownerEmail;
    long long _unreadCount;
    long long _modificationStatus;
    long long _lastSwitchDate;
    long long _flags;
    BLAccount *_account;
}

+ (unsigned long long)currentNewestVersion;
+ (_Bool)upgradeTableToVersion:(unsigned long long)arg1 MDHandler:(id)arg2;
+ (void)createTableWithMDHandler:(id)arg1;
+ (_Bool)isShardingTable;
+ (id)tableName;
+ (id)primaryKeyName;
+ (_Bool)hasAutoIncrementPrimaryKey;
+ (void)createLocalFoldersWithAccount:(id)arg1;
+ (id)folderFromAPIFolderModel:(id)arg1 andAccount:(id)arg2;
+ (long long)folderTypeFromAPIFolderType:(long long)arg1;
+ (long long)apiFolderTypeFromFolderType:(long long)arg1;
+ (id)findFolderWithPath:(id)arg1 account:(id)arg2;
+ (id)folderWithUUID:(long long)arg1 account:(id)arg2;
+ (id)findMailFolderWithAccount:(id)arg1;
+ (id)findPushFoldersWithAccount:(id)arg1 withInbox:(_Bool)arg2;
+ (id)findWithWithFolderID:(id)arg1 type:(long long)arg2 account:(id)arg3;
+ (id)findFirstWithFolderID:(id)arg1 type:(long long)arg2 account:(id)arg3;
+ (id)findFirstMailFolderWithFolderID:(id)arg1 account:(id)arg2;
+ (id)findWithWithType:(long long)arg1 account:(id)arg2;
+ (id)findFirstWithType:(long long)arg1 account:(id)arg2;
+ (id)generateLocalSentFolderWithAccount:(id)arg1;
+ (id)generateFolerFromImapFolder:(id)arg1 account:(id)arg2;
+ (long long)folderTypeWithPath:(id)arg1;
+ (id)dt_trashMailFolder:(id)arg1;
+ (id)localizableStringForFolderDisplayName:(id)arg1;
@property(retain, nonatomic) BLAccount *account; // @synthesize account=_account;
@property(nonatomic) long long flags; // @synthesize flags=_flags;
@property(nonatomic) long long lastSwitchDate; // @synthesize lastSwitchDate=_lastSwitchDate;
@property(nonatomic) long long modificationStatus; // @synthesize modificationStatus=_modificationStatus;
@property(nonatomic) long long unreadCount; // @synthesize unreadCount=_unreadCount;
@property(copy, nonatomic) NSString *ownerEmail; // @synthesize ownerEmail=_ownerEmail;
@property(copy, nonatomic) NSString *folderAcl; // @synthesize folderAcl=_folderAcl;
@property(nonatomic) _Bool hasMore; // @synthesize hasMore=_hasMore;
@property(copy, nonatomic) NSString *path; // @synthesize path=_path;
@property(copy, nonatomic) NSString *oldestItemID; // @synthesize oldestItemID=_oldestItemID;
@property(nonatomic) long long ancestorType; // @synthesize ancestorType=_ancestorType;
@property(nonatomic) long long lastVisitDate; // @synthesize lastVisitDate=_lastVisitDate;
@property(nonatomic) _Bool isLocalFolder; // @synthesize isLocalFolder=_isLocalFolder;
@property(nonatomic) _Bool shouldPush; // @synthesize shouldPush=_shouldPush;
@property(nonatomic) long long level; // @synthesize level=_level;
@property(copy, nonatomic) NSString *parentID; // @synthesize parentID=_parentID;
@property(copy, nonatomic) NSString *name; // @synthesize name=_name;
@property(nonatomic) long long groupType; // @synthesize groupType=_groupType;
@property(nonatomic) long long type; // @synthesize type=_type;
@property(copy, nonatomic) NSString *folderID; // @synthesize folderID=_folderID;
@property(copy, nonatomic) NSString *syncKey; // @synthesize syncKey=_syncKey;
@property(nonatomic) long long uuid; // @synthesize uuid=_uuid;
- (void).cxx_destruct;
- (id)initWithAccount:(id)arg1;
- (id)init;
- (void)initSelf;
- (void)setNeedSentStatus:(_Bool)arg1;
- (_Bool)needSentStatus;
- (unsigned long long)mailCount;
- (unsigned long long)localUnreadCount;
- (id)accountSpaceUniqueId;
- (unsigned long long)newMailFolderCount;
- (unsigned long long)newMailCount;
- (_Bool)hasNewMailModificaton;
- (_Bool)allowToogleToOnlyUnreadMode;
- (_Bool)dt_shouldDisplayRecepients;
- (_Bool)dt_allowMutliEdit;
- (_Bool)dt_shouldFlag;
- (_Bool)dt_shouldFilter;
- (_Bool)dt_shouldThreading;
- (_Bool)dt_allowOperation;
@property(nonatomic) _Bool noParent;
- (id)uniqueId;
- (_Bool)isTag;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

