//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class DTCircleFeedCellInfo, NSArray;

@interface DTCirclePostsDataProvider : NSObject
{
    NSArray *_cellInfoArray;
    NSArray *_galleryModels;
    unsigned long long _uid;
    CDUnknownBlockType _didChangeAllContentCallback;
    CDUnknownBlockType _willChangeContentCallback;
    CDUnknownBlockType _didChangeContentCallback;
    CDUnknownBlockType _didChangeObjectCallback;
    NSArray *_postModels;
    DTCircleFeedCellInfo *_newCommentsRemindCellInfo;
    DTCircleFeedCellInfo *_spacingCellInfo;
}

@property(retain, nonatomic) DTCircleFeedCellInfo *spacingCellInfo; // @synthesize spacingCellInfo=_spacingCellInfo;
@property(retain, nonatomic) DTCircleFeedCellInfo *newCommentsRemindCellInfo; // @synthesize newCommentsRemindCellInfo=_newCommentsRemindCellInfo;
@property(copy, nonatomic) NSArray *postModels; // @synthesize postModels=_postModels;
@property(copy, nonatomic) CDUnknownBlockType didChangeObjectCallback; // @synthesize didChangeObjectCallback=_didChangeObjectCallback;
@property(copy, nonatomic) CDUnknownBlockType didChangeContentCallback; // @synthesize didChangeContentCallback=_didChangeContentCallback;
@property(copy, nonatomic) CDUnknownBlockType willChangeContentCallback; // @synthesize willChangeContentCallback=_willChangeContentCallback;
@property(copy, nonatomic) CDUnknownBlockType didChangeAllContentCallback; // @synthesize didChangeAllContentCallback=_didChangeAllContentCallback;
@property(readonly, nonatomic) unsigned long long uid; // @synthesize uid=_uid;
@property(readonly, nonatomic) NSArray *galleryModels; // @synthesize galleryModels=_galleryModels;
@property(readonly, nonatomic) NSArray *cellInfoArray; // @synthesize cellInfoArray=_cellInfoArray;
- (void).cxx_destruct;
- (id)cellInfoArrayWithPostModel:(id)arg1 inCellInfoArray:(id)arg2;
- (id)replacePostModel:(id)arg1 inModels:(id)arg2;
- (id)removeCellInfosForPostModel:(id)arg1 inCellInfoArray:(id)arg2;
- (id)indexPathsForPostModel:(id)arg1 inCellInfoArray:(id)arg2;
- (id)postModelInModels:(id)arg1 withPostId:(long long)arg2;
- (long long)indexOfPostModelInModels:(id)arg1 withPostId:(long long)arg2;
- (_Bool)containsPostModelInModels:(id)arg1 withPostId:(long long)arg2;
- (id)createCellInfoArrayWithPostModels:(id)arg1;
- (void)deleteCellsWithPostId:(long long)arg1;
- (void)addCellsWithPostModels:(id)arg1;
- (void)updateCellsWithPostModel:(id)arg1;
- (void)replacePostModel:(id)arg1;
- (void)deletePostWithPostId:(long long)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (void)deleteCommentWithPostModel:(id)arg1 commentId:(long long)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (void)commentWithPostModel:(id)arg1 replyToUid:(long long)arg2 content:(id)arg3 completionHandler:(CDUnknownBlockType)arg4;
- (void)likeOrRecallLikeWithPostModel:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (void)loadMoreObjectsWithCompletionHandler:(CDUnknownBlockType)arg1;
- (void)pullToRefreshObjectsWithCompletionHandler:(CDUnknownBlockType)arg1;
- (void)reloadLocalCache;
- (void)loadLocalCache;
- (id)cellInfoAtIndexPath:(id)arg1;
- (long long)numberOfCells;
- (long long)indexOfGalleryModelsWithPostModel:(id)arg1;
- (_Bool)isFeeds;
- (void)markAllNoticeAsRead;
- (void)setupCellInfoArrayWithPostModels:(id)arg1;
- (void)setupPhotoObjectsWithPostModels:(id)arg1;
- (void)setGalleryModels:(id)arg1;
- (void)setCellInfoArray:(id)arg1;
- (void)receiveCommentUpdateSuccessNotification:(id)arg1;
- (void)receiveCreatePostSuccessNotification:(id)arg1;
- (void)receiveNoticeUpdateNotification:(id)arg1;
- (id)initWithUid:(long long)arg1;
- (id)init;
- (void)dealloc;

@end

