//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "UIScrollViewDelegate-Protocol.h"

@class MASConstraint, NSString, SYWaterDropView, UIImageView, UILabel;

@interface DTCircleFeedParallaxHeaderView : UIView <UIScrollViewDelegate>
{
    _Bool _isDragging;
    _Bool _didStopRefreshAnimating;
    CDUnknownBlockType _avatarDidTapCallback;
    CDUnknownBlockType _didPullToRefreshCallback;
    long long _uid;
    SYWaterDropView *_waterdropEffectView;
    UILabel *_usernameLabel;
    UIView *_avatarView;
    UIView *_wrapper;
    MASConstraint *_wrapperInsetsConstraint;
    UIView *_coverContainerView;
    UIImageView *_coverImageView;
    MASConstraint *_coverContainerHeightConstraint;
    MASConstraint *_coverImageViewBottomConstraint;
    MASConstraint *_coverImageViewHeightConstraint;
    struct UIEdgeInsets _wrapperInsets;
}

@property(retain, nonatomic) MASConstraint *coverImageViewHeightConstraint; // @synthesize coverImageViewHeightConstraint=_coverImageViewHeightConstraint;
@property(retain, nonatomic) MASConstraint *coverImageViewBottomConstraint; // @synthesize coverImageViewBottomConstraint=_coverImageViewBottomConstraint;
@property(retain, nonatomic) MASConstraint *coverContainerHeightConstraint; // @synthesize coverContainerHeightConstraint=_coverContainerHeightConstraint;
@property(retain, nonatomic) UIImageView *coverImageView; // @synthesize coverImageView=_coverImageView;
@property(retain, nonatomic) UIView *coverContainerView; // @synthesize coverContainerView=_coverContainerView;
@property(retain, nonatomic) MASConstraint *wrapperInsetsConstraint; // @synthesize wrapperInsetsConstraint=_wrapperInsetsConstraint;
@property(retain, nonatomic) UIView *wrapper; // @synthesize wrapper=_wrapper;
@property(retain, nonatomic) UIView *avatarView; // @synthesize avatarView=_avatarView;
@property(retain, nonatomic) UILabel *usernameLabel; // @synthesize usernameLabel=_usernameLabel;
@property(retain, nonatomic) SYWaterDropView *waterdropEffectView; // @synthesize waterdropEffectView=_waterdropEffectView;
@property(nonatomic) _Bool didStopRefreshAnimating; // @synthesize didStopRefreshAnimating=_didStopRefreshAnimating;
@property(nonatomic) _Bool isDragging; // @synthesize isDragging=_isDragging;
@property(readonly, nonatomic) long long uid; // @synthesize uid=_uid;
@property(copy, nonatomic) CDUnknownBlockType didPullToRefreshCallback; // @synthesize didPullToRefreshCallback=_didPullToRefreshCallback;
@property(copy, nonatomic) CDUnknownBlockType avatarDidTapCallback; // @synthesize avatarDidTapCallback=_avatarDidTapCallback;
@property(nonatomic) struct UIEdgeInsets wrapperInsets; // @synthesize wrapperInsets=_wrapperInsets;
- (void).cxx_destruct;
- (id)username;
- (id)createAvatarView;
- (void)stopRefreshAnimating;
- (void)startRefreshAnimating;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1 uid:(long long)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

