//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class DTAutoLayoutLabel, DTAvatarView, DTCircleNoticeModel, DTCircleNoticeThumbnailView, UILabel;

@interface DTCircleNoticeCell : UITableViewCell
{
    DTCircleNoticeModel *_noticeModel;
    DTAvatarView *_avatarView;
    UILabel *_usernameLabel;
    DTAutoLayoutLabel *_commentLabel;
    UILabel *_createdAtLabel;
    DTCircleNoticeThumbnailView *_thumbnailView;
}

@property(retain, nonatomic) DTCircleNoticeThumbnailView *thumbnailView; // @synthesize thumbnailView=_thumbnailView;
@property(retain, nonatomic) UILabel *createdAtLabel; // @synthesize createdAtLabel=_createdAtLabel;
@property(retain, nonatomic) DTAutoLayoutLabel *commentLabel; // @synthesize commentLabel=_commentLabel;
@property(retain, nonatomic) UILabel *usernameLabel; // @synthesize usernameLabel=_usernameLabel;
@property(retain, nonatomic) DTAvatarView *avatarView; // @synthesize avatarView=_avatarView;
@property(retain, nonatomic) DTCircleNoticeModel *noticeModel; // @synthesize noticeModel=_noticeModel;
- (void).cxx_destruct;
- (id)deletedAttributedString;
- (id)likedAttributedString;
- (id)commentAttributedStringWithCommentModel:(id)arg1;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

