//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSMutableArray;

@interface DTCIMAPFetchInfosQueue : NSObject
{
    CDUnknownBlockType _successBlock;
    CDUnknownBlockType _failedBlock;
    NSMutableArray *_indexSets;
}

@property(retain, nonatomic) NSMutableArray *indexSets; // @synthesize indexSets=_indexSets;
@property(copy, nonatomic) CDUnknownBlockType failedBlock; // @synthesize failedBlock=_failedBlock;
@property(copy, nonatomic) CDUnknownBlockType successBlock; // @synthesize successBlock=_successBlock;
- (void).cxx_destruct;
- (void)processFetch;
- (void)addInfos:(id)arg1 forFolder:(id)arg2 forAccount:(id)arg3;

@end

