//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSMutableDictionary;

@interface DTCircleContactCache : NSObject
{
    NSMutableDictionary *_contactCache;
    NSMutableDictionary *_nicknameCache;
    NSMutableDictionary *_authorSubtitleCache;
}

+ (id)sharedInstance;
@property(retain, nonatomic) NSMutableDictionary *authorSubtitleCache; // @synthesize authorSubtitleCache=_authorSubtitleCache;
@property(retain, nonatomic) NSMutableDictionary *nicknameCache; // @synthesize nicknameCache=_nicknameCache;
@property(retain, nonatomic) NSMutableDictionary *contactCache; // @synthesize contactCache=_contactCache;
- (void).cxx_destruct;
- (void)fetchContactsIfNeededWithUIDs:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (void)asyncFetchEnterpriseCardWithUID:(long long)arg1 orgId:(long long)arg2;
- (void)fetchAuthorSubtitlesIfNeededWithUIDs:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (void)fetchContactsIfNeededWithPostModels:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (id)cachedContactWithUID:(long long)arg1;
- (id)cachedNicknameWithUID:(long long)arg1;
- (id)cachedAuthorSubtitleWithUID:(long long)arg1;
- (void)removeAllCache;
- (void)receiveContactUpdatedNotification:(id)arg1;
- (id)init;
- (void)dealloc;

@end

