//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class DTImageView, UILabel;

@interface DTCirclePostPageShareLinkCell : UITableViewCell
{
    DTImageView *_linkImageView;
    UILabel *_linkTitleLabel;
}

@property(retain, nonatomic) UILabel *linkTitleLabel; // @synthesize linkTitleLabel=_linkTitleLabel;
@property(retain, nonatomic) DTImageView *linkImageView; // @synthesize linkImageView=_linkImageView;
- (void).cxx_destruct;
- (void)setLinkTitle:(id)arg1 linkThumbnailImageURL:(id)arg2;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

