//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "DTUITableViewController.h"

@class DTCircleFeedAdjustsNavigationBarSupport, DTCircleFeedPagingController, DTCircleFeedParallaxHeaderView, DTCirclePhotoBrowserHelper, DTCirclePostsDataProvider;

@interface DTCirclePostsViewController : DTUITableViewController
{
    long long _uid;
    DTCirclePostsDataProvider *_dataProvider;
    DTCircleFeedPagingController *_pagingController;
    DTCirclePhotoBrowserHelper *_photoBrowserHelper;
    DTCircleFeedAdjustsNavigationBarSupport *_adjustsNavigationBarSupport;
    DTCircleFeedParallaxHeaderView *_headerView;
}

@property(retain, nonatomic) DTCircleFeedParallaxHeaderView *headerView; // @synthesize headerView=_headerView;
@property(retain, nonatomic) DTCircleFeedAdjustsNavigationBarSupport *adjustsNavigationBarSupport; // @synthesize adjustsNavigationBarSupport=_adjustsNavigationBarSupport;
@property(retain, nonatomic) DTCirclePhotoBrowserHelper *photoBrowserHelper; // @synthesize photoBrowserHelper=_photoBrowserHelper;
@property(retain, nonatomic) DTCircleFeedPagingController *pagingController; // @synthesize pagingController=_pagingController;
@property(retain, nonatomic) DTCirclePostsDataProvider *dataProvider; // @synthesize dataProvider=_dataProvider;
@property(readonly, nonatomic) long long uid; // @synthesize uid=_uid;
- (void).cxx_destruct;
- (void)pushDetailViewControllerWithPostModel:(id)arg1;
- (void)configTableViewCell:(id)arg1 cellInfo:(id)arg2 atIndexPath:(id)arg3;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)updateNavigationBarAppearance;
- (void)setupPagingController;
- (void)setupDataProvider;
- (void)setupTableView;
- (void)recentCommentsItemDidTapHandler:(id)arg1;
- (void)setupBarButtonItems;
- (void)viewDidLayoutSubviews;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)initWithUid:(long long)arg1;

@end

