//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class UITextField;
@protocol DTCMailQuickAddViewControllerDelegate;

@interface DTCMailQuickAddViewController : UIViewController
{
    UITextField *txtContent;
    id <DTCMailQuickAddViewControllerDelegate> _delegate;
}

@property(nonatomic) __weak id <DTCMailQuickAddViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)didReceiveMemoryWarning;
- (void)rightBarButtonItemPress:(id)arg1;
- (void)leftBarButtonItemPress:(id)arg1;
- (void)viewDidLoad;

@end

