//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class DTCMail, DTCMailListFilterCondition, NSArray, NSIndexPath, NSString, UITableView;

@protocol DTCMailListAdapterProtocol <NSObject>
@property(retain, nonatomic) NSArray *tags;
@property(nonatomic) long long sessionCount;
@property(copy, nonatomic) NSString *sessionID;
@property(nonatomic) _Bool isThread;
@property(nonatomic) __weak UITableView *tableView;
- (void)loadMoreDataWithCondition:(DTCMailListFilterCondition *)arg1 completionBlock:(void (^)(_Bool))arg2 failureBlock:(void (^)(NSError *))arg3;
- (void)refreshMailWithCompletionBlock:(void (^)(void))arg1 failureBlock:(void (^)(NSError *))arg2;
- (long long)mailCountIncludeSubSession;
- (long long)mailCount;
- (_Bool)isEmpty;
- (NSString *)sectionTitleForSection:(long long)arg1;
- (long long)numberOfSections;
- (long long)numberOfRowsInSection:(long long)arg1;
- (NSArray *)allMails;
- (NSIndexPath *)indexPathForObject:(DTCMail *)arg1;
- (DTCMail *)objectAtIndexPath:(NSIndexPath *)arg1;
- (id)initWithObj:(id)arg1;
@end

