//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class DTCMailReceiverViewModel, UIButton, UILabel;

@interface DTCMailReceiverCell : UITableViewCell
{
    UILabel *_statusLabel;
    UILabel *_nameLabel;
    UILabel *_emailLabel;
    UILabel *_disableLabel;
    UIButton *_rightButton;
    DTCMailReceiverViewModel *_model;
}

@property(retain, nonatomic) DTCMailReceiverViewModel *model; // @synthesize model=_model;
@property(retain, nonatomic) UIButton *rightButton; // @synthesize rightButton=_rightButton;
@property(retain, nonatomic) UILabel *disableLabel; // @synthesize disableLabel=_disableLabel;
@property(retain, nonatomic) UILabel *emailLabel; // @synthesize emailLabel=_emailLabel;
@property(retain, nonatomic) UILabel *nameLabel; // @synthesize nameLabel=_nameLabel;
@property(retain, nonatomic) UILabel *statusLabel; // @synthesize statusLabel=_statusLabel;
- (void).cxx_destruct;
- (void)rightButtonClick:(id)arg1;
- (void)configWithData:(id)arg1;
- (void)layoutSubviews;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

