//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

#import "UITextFieldDelegate-Protocol.h"

@class DTCommonItem, NSString, UIButton, UIImageView, UILabel, UISwitch, UITextField;

@interface DTCommonTableViewCell : UITableViewCell <UITextFieldDelegate>
{
    _Bool _showTopLine;
    _Bool _showBottomLine;
    long long _index;
    long long _number;
    DTCommonItem *_item;
    UILabel *_nameLabel;
    UILabel *_detailLabel;
    UITextField *_inputTextField;
    UIImageView *_indicatorView;
    UIButton *_rightButton;
    UISwitch *_swither;
    UIImageView *_topLineView;
    UIImageView *_bottomLineView;
    struct UIEdgeInsets _topSeparatorInset;
    struct UIEdgeInsets _bottomSeparatorInset;
}

+ (double)cellHeightForItem:(id)arg1;
@property(retain, nonatomic) UIImageView *bottomLineView; // @synthesize bottomLineView=_bottomLineView;
@property(retain, nonatomic) UIImageView *topLineView; // @synthesize topLineView=_topLineView;
@property(retain, nonatomic) UISwitch *swither; // @synthesize swither=_swither;
@property(retain, nonatomic) UIButton *rightButton; // @synthesize rightButton=_rightButton;
@property(retain, nonatomic) UIImageView *indicatorView; // @synthesize indicatorView=_indicatorView;
@property(retain, nonatomic) UITextField *inputTextField; // @synthesize inputTextField=_inputTextField;
@property(retain, nonatomic) UILabel *detailLabel; // @synthesize detailLabel=_detailLabel;
@property(retain, nonatomic) UILabel *nameLabel; // @synthesize nameLabel=_nameLabel;
@property(retain, nonatomic) DTCommonItem *item; // @synthesize item=_item;
@property(nonatomic) long long number; // @synthesize number=_number;
@property(nonatomic) long long index; // @synthesize index=_index;
@property(nonatomic) struct UIEdgeInsets bottomSeparatorInset; // @synthesize bottomSeparatorInset=_bottomSeparatorInset;
@property(nonatomic) struct UIEdgeInsets topSeparatorInset; // @synthesize topSeparatorInset=_topSeparatorInset;
@property(nonatomic) _Bool showBottomLine; // @synthesize showBottomLine=_showBottomLine;
@property(nonatomic) _Bool showTopLine; // @synthesize showTopLine=_showTopLine;
- (void).cxx_destruct;
- (void)getResignFirstReponseNotice;
- (_Bool)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (void)textFieldCharChange;
- (_Bool)textFieldShouldReturn:(id)arg1;
- (void)rightBtnClick;
- (void)switchChange:(id)arg1;
- (void)drawSeperaterLineOfCell;
- (void)setLineHidden:(_Bool)arg1;
- (void)setHighlighted:(_Bool)arg1 animated:(_Bool)arg2;
- (void)setLocationOfCellAtIndex:(long long)arg1 inNumberOfRowsInSelfSection:(long long)arg2;
- (void)setTextFeildReturnKeyType:(long long)arg1;
- (void)layoutSubviews;
- (void)configWithItem:(id)arg1;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

