//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "DTConferenceServicePersistenceProtocol-Protocol.h"

@class NSString, OpenDatabase, OpenMDHandler;

@interface DTConferenceServicePersistenceIMP : NSObject <DTConferenceServicePersistenceProtocol>
{
    OpenDatabase *_dbConnection;
    OpenMDHandler *_confHistoryHandler;
    OpenMDHandler *_confADHandler;
    OpenMDHandler *_confShowPageHandler;
    OpenMDHandler *_confUserMobileHandler;
    OpenMDHandler *_confCallNumInfoHandler;
    OpenMDHandler *_bizCallNumInfoHandler;
    OpenMDHandler *_confCallKitInfoHandler;
    OpenMDHandler *_confCallManageHandler;
    OpenMDHandler *_confCallManageRedInfoHandler;
    OpenMDHandler *_confCallManageADInfoHandler;
    OpenMDHandler *_confSaveContactHandler;
    OpenMDHandler *_confHistoryConferenceRecommendHandler;
}

@property(retain, nonatomic) OpenMDHandler *confHistoryConferenceRecommendHandler; // @synthesize confHistoryConferenceRecommendHandler=_confHistoryConferenceRecommendHandler;
@property(retain, nonatomic) OpenMDHandler *confSaveContactHandler; // @synthesize confSaveContactHandler=_confSaveContactHandler;
@property(retain, nonatomic) OpenMDHandler *confCallManageADInfoHandler; // @synthesize confCallManageADInfoHandler=_confCallManageADInfoHandler;
@property(retain, nonatomic) OpenMDHandler *confCallManageRedInfoHandler; // @synthesize confCallManageRedInfoHandler=_confCallManageRedInfoHandler;
@property(retain, nonatomic) OpenMDHandler *confCallManageHandler; // @synthesize confCallManageHandler=_confCallManageHandler;
@property(retain, nonatomic) OpenMDHandler *confCallKitInfoHandler; // @synthesize confCallKitInfoHandler=_confCallKitInfoHandler;
@property(retain, nonatomic) OpenMDHandler *bizCallNumInfoHandler; // @synthesize bizCallNumInfoHandler=_bizCallNumInfoHandler;
@property(retain, nonatomic) OpenMDHandler *confCallNumInfoHandler; // @synthesize confCallNumInfoHandler=_confCallNumInfoHandler;
@property(retain, nonatomic) OpenMDHandler *confUserMobileHandler; // @synthesize confUserMobileHandler=_confUserMobileHandler;
@property(retain, nonatomic) OpenMDHandler *confShowPageHandler; // @synthesize confShowPageHandler=_confShowPageHandler;
@property(retain, nonatomic) OpenMDHandler *confADHandler; // @synthesize confADHandler=_confADHandler;
@property(retain, nonatomic) OpenMDHandler *confHistoryHandler; // @synthesize confHistoryHandler=_confHistoryHandler;
@property(retain, nonatomic) OpenDatabase *dbConnection; // @synthesize dbConnection=_dbConnection;
- (void).cxx_destruct;
- (_Bool)saveHistoryConferenceRecommendUsers:(id)arg1;
- (id)loadHistoryConferenceRecommendUsers;
- (id)loadContactModelsByMobiles:(id)arg1;
- (id)loadContactModelByMobile:(id)arg1;
- (_Bool)saveContactModel:(id)arg1;
- (id)loadConfCallManageADInfoModelByKey:(id)arg1;
- (_Bool)saveConfCallManageADInfo:(id)arg1;
- (id)loadConfCallManageRedInfoModelByKey:(id)arg1;
- (_Bool)saveConfCallManageRedInfo:(id)arg1;
- (id)loadConfCallManageInfoModelByOrgId:(long long)arg1;
- (_Bool)saveConfCallManageInfo:(id)arg1;
- (id)loadConfCallKitInfoModelBySessionId:(id)arg1;
- (_Bool)updateConfCallKitInfo:(id)arg1;
- (_Bool)saveConfCallKitInfo:(id)arg1;
- (_Bool)deleteAllBizCallInfo;
- (_Bool)deleteBizCallInfoWithOrgId:(long long)arg1;
- (id)loadAllBizCallNumInfoModel;
- (id)loadBizCallNumInfoModelWithOrgId:(long long)arg1;
- (_Bool)saveBizCallNumInfo:(id)arg1;
- (_Bool)deleteCallNumInfo;
- (void)asyncLoadConfCallNumInfoModelBlock:(CDUnknownBlockType)arg1;
- (id)loadConfCallNumInfoModel;
- (_Bool)updateConfCallNumInfo:(id)arg1;
- (_Bool)saveConfCallNumInfo:(id)arg1;
- (void)deleteUserMobilesWithUids:(id)arg1;
- (void)saveUserMobiles:(id)arg1;
- (id)userMobilesForUids:(id)arg1;
- (_Bool)deleteShowPage;
- (void)asyncLoadConfPageModelBlock:(CDUnknownBlockType)arg1;
- (id)loadConfPageModel;
- (_Bool)updateConfPage:(id)arg1;
- (_Bool)saveConfPage:(id)arg1;
- (_Bool)deleteADInfo;
- (void)asyncLoadConfADBlock:(CDUnknownBlockType)arg1;
- (id)loadConfAD;
- (_Bool)updateConfAD:(id)arg1;
- (_Bool)saveConfAD:(id)arg1;
- (void)asyncLoadConfHistoryByUUID:(id)arg1 doneBlock:(CDUnknownBlockType)arg2;
- (id)loadConfHistoryByUUID:(id)arg1;
- (_Bool)updateConfHistory:(id)arg1;
- (_Bool)saveConfHistory:(id)arg1;
- (id)initWithDbConnection:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

