//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "DTConferenceHelperProtocol-Protocol.h"

@class CTCallCenter, CTTelephonyNetworkInfo, DTDingCardCloudSettingInfoModel, NSString;

@interface DTConferenceHelperIMP : NSObject <DTConferenceHelperProtocol>
{
    CTCallCenter *_callCenter;
    CTTelephonyNetworkInfo *_telephonyInfo;
    _Bool _enableConferenceShowInvite;
    _Bool _enableConferenceVIPMonitor;
    _Bool _enableVoIP2PSTN;
    _Bool _enableCallKit;
    _Bool _enableVideoConf;
    _Bool _enableVoIP;
    _Bool _enableVidyoStrategy;
    _Bool _enableVoIPRelayTester;
    _Bool _enableBizCallAnimation;
    _Bool _audioOnlyInVideoTest;
    _Bool _openCloseCameraInVideoTest;
    _Bool _openCallManageTest;
    _Bool _showCallManageContentTest;
    _Bool _showVoIPConferenceTest;
    _Bool _enableRecommendVoIP;
    _Bool _triggerCall;
    unsigned long long _enableConferenceOrVideoConferenceMemberCount;
    unsigned long long _enableConferenceMemberCount;
    unsigned long long _enableConferenceMiniumMemberCount;
    DTDingCardCloudSettingInfoModel *_dingCardCloudSettingInfo;
}

@property(retain, nonatomic) DTDingCardCloudSettingInfoModel *dingCardCloudSettingInfo; // @synthesize dingCardCloudSettingInfo=_dingCardCloudSettingInfo;
@property(nonatomic) _Bool triggerCall; // @synthesize triggerCall=_triggerCall;
@property(nonatomic) _Bool showVoIPConferenceTest; // @synthesize showVoIPConferenceTest=_showVoIPConferenceTest;
@property(nonatomic) _Bool showCallManageContentTest; // @synthesize showCallManageContentTest=_showCallManageContentTest;
@property(nonatomic) _Bool openCallManageTest; // @synthesize openCallManageTest=_openCallManageTest;
@property(nonatomic) _Bool openCloseCameraInVideoTest; // @synthesize openCloseCameraInVideoTest=_openCloseCameraInVideoTest;
@property(nonatomic) _Bool audioOnlyInVideoTest; // @synthesize audioOnlyInVideoTest=_audioOnlyInVideoTest;
@property(nonatomic) _Bool enableVoIP2PSTN; // @synthesize enableVoIP2PSTN=_enableVoIP2PSTN;
@property(nonatomic) _Bool enableConferenceVIPMonitor; // @synthesize enableConferenceVIPMonitor=_enableConferenceVIPMonitor;
- (void).cxx_destruct;
- (id)getResultWithPhoneList:(id)arg1 organization:(id)arg2 label:(id)arg3;
- (id)checkIfSavedContact:(id)arg1 organization:(id)arg2 label:(id)arg3;
- (id)getPhoneNumberWithUid:(id)arg1 recordPhone:(id)arg2;
- (void)getDingAccountWithUid:(long long)arg1 completion:(CDUnknownBlockType)arg2;
- (void)saveCallKitRecordWithCallId:(id)arg1 fromUid:(id)arg2 uuidStr:(id)arg3 sessionId:(id)arg4;
- (void)goToOpenUrl:(id)arg1;
- (void)showBigShowWithPic:(id)arg1 title:(id)arg2 content:(id)arg3 jumpBtnText:(id)arg4 jumpUrlStr:(id)arg5 confirmText:(id)arg6 completion:(CDUnknownBlockType)arg7;
- (void)shouldShowDingCardADFromType:(unsigned long long)arg1 completion:(CDUnknownBlockType)arg2;
- (_Bool)checkIfNeedToShowDingCardADFromType:(unsigned long long)arg1 fileSize:(long long)arg2;
- (long long)getDingCardADInterval;
- (id)getDingCardADKey:(unsigned long long)arg1;
- (_Bool)checkEnterpriseCardWithOrgIds:(id)arg1 orgLevels:(id)arg2;
- (_Bool)checkDingCardGlobal:(id)arg1;
- (_Bool)checkValueIfChanged:(id)arg1 withModel:(id)arg2;
- (_Bool)shouldShowDingCardWithModel:(id)arg1;
- (id)getDingCardCloudSettingInfo;
- (id)getDingCardInfo;
- (void)updateDingCardCloudSettingInfo:(id)arg1 value:(id)arg2;
- (void)dingCardCloudSettingChanged:(id)arg1;
- (void)disappearDingCardReddot:(_Bool)arg1;
- (_Bool)shouldShowDingCardReddot;
- (void)writeBizCallSettingPageEnterRecord:(id)arg1 callNumInfo:(id)arg2;
- (_Bool)readBizCallSettingPageEnterRecord:(id)arg1 callNumInfo:(id)arg2;
- (void)writeConferenceSettingPageEnterRecord:(id)arg1 callNumInfo:(id)arg2;
- (_Bool)readConferenceSettingPageEnterRecord:(id)arg1 callNumInfo:(id)arg2;
- (void)recordSysCall:(id)arg1 calleeMobile:(id)arg2;
- (void)conferenceStartWithModel:(id)arg1 cid:(id)arg2 calleeUids:(id)arg3 state:(unsigned long long)arg4 completion:(CDUnknownBlockType)arg5;
- (void)bizCallQuickStartWithUid:(long long)arg1 withPhone:(id)arg2;
- (void)conferenceQuickStartWithUids:(id)arg1 cid:(id)arg2 quickType:(long long)arg3;
- (void)conferenceQuickStartWithUids:(id)arg1 cid:(id)arg2 quickType:(long long)arg3 inModal:(id)arg4;
- (void)makeSystemCallWithPhone:(id)arg1 withUid:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)updateMobile:(id)arg1 model:(id)arg2;
- (void)getPhoneNumberFromLocalContactWithUid:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)getPhoneNumber:(id)arg1 withUid:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)createIdToForPhoneRecord:(id)arg1 sendRecord:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;
- (void)conferenceStartSysCallWithUid:(id)arg1 withPhone:(id)arg2 cid:(id)arg3 source:(long long)arg4 completion:(CDUnknownBlockType)arg5;
- (void)conferenceStartWithUid:(id)arg1 withPhone:(id)arg2 cid:(id)arg3 actionTitle:(id)arg4 source:(long long)arg5 inModal:(id)arg6;
- (void)conferenceStartWithUid:(id)arg1 withPhone:(id)arg2 cid:(id)arg3 source:(long long)arg4 inModal:(id)arg5;
- (CDUnknownBlockType)contactPickedWithConfType:(long long)arg1 source:(long long)arg2 cid:(id)arg3 inModal:(id)arg4;
- (void)conferenceStartWithSelectMembersFromCid:(id)arg1 title:(id)arg2 source:(long long)arg3 callType:(long long)arg4 inModal:(id)arg5;
- (void)conferenceStartWithUids:(id)arg1 cid:(id)arg2 actionTitle:(id)arg3 types:(id)arg4 showMore:(_Bool)arg5 source:(long long)arg6 inModal:(id)arg7;
- (void)conferenceStartWithUids:(id)arg1 cid:(id)arg2 actionTitle:(id)arg3 showMore:(_Bool)arg4 source:(long long)arg5 inModal:(id)arg6;
- (void)conferenceStartWithUids:(id)arg1 cid:(id)arg2 showMore:(_Bool)arg3 source:(long long)arg4 inModal:(id)arg5;
- (void)conferenceStartWithUids:(id)arg1 cid:(id)arg2 inModal:(id)arg3 completion:(CDUnknownBlockType)arg4;
- (_Bool)showVoIPConferenceInterface;
- (_Bool)showExternContact;
- (_Bool)useAnotherDaySaveContact;
- (_Bool)useSaveContactOnceFunction;
- (_Bool)showCloseAllCameraInVideoConf;
- (_Bool)showCallManage;
- (_Bool)useDingCardADInDingDrive;
- (_Bool)useVideoConferenceVIPAlarm;
- (_Bool)useVideoConferencePanel;
- (_Bool)useActionSheet;
- (_Bool)useNewActionSheet;
- (_Bool)checkIfSimCardInside;
- (id)getMobileService:(id)arg1;
- (id)currentRadioAccessTechnology;
- (id)getMobileService;
- (void)removeTeleCallStatusNotifiy;
- (void)willResignActiveNotification:(id)arg1;
- (void)triggerTeleCallStatusNotifiy;
- (_Bool)checkIfConfCallerUidIsSystemUid:(long long)arg1;
- (long long)checkCurrentConferenceBusinessStatus;
- (_Bool)isInVideoConference;
- (_Bool)isInPSTN;
- (_Bool)isInVoIP;
- (_Bool)isInConference;
- (void)triggerConfAlarm:(id)arg1 type:(long long)arg2;
- (id)getUsualContact:(long long)arg1;
- (id)getConferenceExtensionMessage:(id)arg1;
- (id)conferenceCellConversationId;
- (id)conferenceConversationId;
@property(readonly, nonatomic) unsigned long long enableConferenceOrVideoConferenceMemberCount; // @synthesize enableConferenceOrVideoConferenceMemberCount=_enableConferenceOrVideoConferenceMemberCount;
@property(nonatomic) _Bool enableRecommendVoIP; // @synthesize enableRecommendVoIP=_enableRecommendVoIP;
@property(nonatomic) unsigned long long enableConferenceVideoMemberCount;
@property(nonatomic) unsigned long long enableConferenceMiniumMemberCount; // @synthesize enableConferenceMiniumMemberCount=_enableConferenceMiniumMemberCount;
@property(nonatomic) unsigned long long enableConferenceMemberCount; // @synthesize enableConferenceMemberCount=_enableConferenceMemberCount;
@property(nonatomic) _Bool supportFixLine;
@property(nonatomic) _Bool enableVoIP; // @synthesize enableVoIP=_enableVoIP;
@property(nonatomic) _Bool enableVoIPCallOutViaCallKit;
@property(nonatomic) _Bool enableBizCallAnimation; // @synthesize enableBizCallAnimation=_enableBizCallAnimation;
@property(nonatomic) _Bool enableVoIPRelayTester; // @synthesize enableVoIPRelayTester=_enableVoIPRelayTester;
@property(nonatomic) _Bool enableVidyoStrategy; // @synthesize enableVidyoStrategy=_enableVidyoStrategy;
@property(nonatomic) _Bool enableVideoConf; // @synthesize enableVideoConf=_enableVideoConf;
@property(nonatomic) _Bool enableCallKit; // @synthesize enableCallKit=_enableCallKit;
@property(nonatomic) _Bool enableConferenceShowInvite; // @synthesize enableConferenceShowInvite=_enableConferenceShowInvite;
- (id)init;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

