//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class DTFrequentContactsManager, DTFriendManager, DTMobileContactManager, DTQuotaManager, DTSafeDeviceManager, DTSearchEngine, DTSearchManager;

@interface DTContactCenter : NSObject
{
    _Bool _hasTaskRun;
    DTFriendManager *_friendManager;
    DTFrequentContactsManager *_frequentContactsManager;
    DTMobileContactManager *_mobileContactManager;
    DTSearchManager *_searchManager;
    DTSearchEngine *_searchEngine;
    DTSafeDeviceManager *_safeDeviceManager;
    DTQuotaManager *_quotaManager;
}

+ (unsigned long long)convertToTypeWithorgLevel:(long long)arg1;
+ (id)displayEmailWithContact:(id)arg1;
+ (id)bindedEmailWithContact:(id)arg1;
+ (id)emailWithDingAccount:(id)arg1;
+ (id)dingAccountWithEmail:(id)arg1;
+ (id)sharedCenter;
@property _Bool hasTaskRun; // @synthesize hasTaskRun=_hasTaskRun;
@property(retain, nonatomic) DTQuotaManager *quotaManager; // @synthesize quotaManager=_quotaManager;
@property(retain, nonatomic) DTSafeDeviceManager *safeDeviceManager; // @synthesize safeDeviceManager=_safeDeviceManager;
@property(retain, nonatomic) DTSearchEngine *searchEngine; // @synthesize searchEngine=_searchEngine;
@property(retain, nonatomic) DTSearchManager *searchManager; // @synthesize searchManager=_searchManager;
@property(retain, nonatomic) DTMobileContactManager *mobileContactManager; // @synthesize mobileContactManager=_mobileContactManager;
@property(retain, nonatomic) DTFrequentContactsManager *frequentContactsManager; // @synthesize frequentContactsManager=_frequentContactsManager;
@property(retain, nonatomic) DTFriendManager *friendManager; // @synthesize friendManager=_friendManager;
- (void).cxx_destruct;
- (void)jumpToWebViewWithUrl:(id)arg1;
- (id)rightsUrlByType:(unsigned long long)arg1 orgLevel:(long long)arg2;
- (void)setNeedShowUpgrade:(_Bool)arg1;
- (void)checkIfUserRightsLevelUpgrade:(id)arg1;
- (void)userRightsLevelUpgrade:(id)arg1;
- (void)showUserRightsLevelUpgradeView:(long long)arg1;
- (void)createConferenceCallBackNumbers:(id)arg1;
- (void)createCallBackNumbers:(id)arg1;
- (void)removeTaskWhenSignout:(id)arg1;
- (void)asyncSaveDingTalkPhone;
- (void)asyncOpenSearchIndex;
- (void)asyncLoadFunctionToDatabase;
- (void)runTaskWhenSignin:(id)arg1;
- (void)clear;
- (void)setup;
- (long long)myFirstDepartIdOrMasterUidWithOrgId:(long long)arg1;
- (void)addNotifications;
- (void)dealloc;

@end

