//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "DTContactPickSearchHandler.h"

@class DTSectionItem, NSDictionary, NSString;

@interface DTContactPickGroupMultiSelectSearchHandler : DTContactPickSearchHandler
{
    _Bool _isLocalSearchFinish;
    unsigned long long _bizType;
    DTSectionItem *_sectionItem;
    NSDictionary *_index;
    NSString *_searchText;
}

@property(nonatomic) _Bool isLocalSearchFinish; // @synthesize isLocalSearchFinish=_isLocalSearchFinish;
@property(copy, nonatomic) NSString *searchText; // @synthesize searchText=_searchText;
@property(copy, nonatomic) NSDictionary *index; // @synthesize index=_index;
@property(retain, nonatomic) DTSectionItem *sectionItem; // @synthesize sectionItem=_sectionItem;
@property(nonatomic) unsigned long long bizType; // @synthesize bizType=_bizType;
- (void).cxx_destruct;
- (void)showConversationMembers:(id)arg1;
- (id)signImageTypeForConversation:(id)arg1;
- (id)statusList;
- (id)filterBindConversations:(id)arg1;
- (id)filterConversations:(id)arg1;
- (void)dealWithConversations:(id)arg1 searchText:(id)arg2 hasMore:(_Bool)arg3 successBlock:(CDUnknownBlockType)arg4 failureBlock:(CDUnknownBlockType)arg5;
- (id)filterWithConversation:(id)arg1;
- (void)fetchMTMConversationsWithSearchText:(id)arg1 offset:(long long)arg2 size:(long long)arg3 successBlock:(CDUnknownBlockType)arg4 failureBlock:(CDUnknownBlockType)arg5;
- (void)fetchMTMConversationsOnServerWithSearchText:(id)arg1 offset:(long long)arg2 size:(long long)arg3 successBlock:(CDUnknownBlockType)arg4 failureBlock:(CDUnknownBlockType)arg5;
- (void)searchMTMConversationsWithSearchText:(id)arg1 offset:(long long)arg2 size:(long long)arg3 successBlock:(CDUnknownBlockType)arg4 failureBlock:(CDUnknownBlockType)arg5;
- (void)beginLoadMoreController:(id)arg1 successBlock:(CDUnknownBlockType)arg2 failureBlock:(CDUnknownBlockType)arg3;
- (void)searchText:(id)arg1 successBlock:(CDUnknownBlockType)arg2 failureBlock:(CDUnknownBlockType)arg3;
- (id)loadModelControllerForSearchView:(id)arg1;
- (id)dataSourceForSearchViewController:(id)arg1;
- (id)emptyViewForViewController:(id)arg1;
- (_Bool)shouldShowEmptyView:(id)arg1;
- (void)updateCellWithIdentifier:(id)arg1 isSelected:(_Bool)arg2;
- (void)conversationHasUnselected:(id)arg1;
- (void)conversationHasSelected:(id)arg1;
- (void)searchViewWillDestory:(id)arg1;
- (void)searchViewWillShow:(id)arg1;
- (void)dealloc;

@end

