//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "DTContactPickHandler.h"

#import "DTExternalContactListDataSourceDelegate-Protocol.h"

@class DTCellItem, DTContactPickExternalSearchHandler, DTContactPickExternalViewController, DTSectionItem, NSDictionary, NSString;

@interface DTContactPickExternalHandler : DTContactPickHandler <DTExternalContactListDataSourceDelegate>
{
    DTContactPickExternalViewController *_externalContactVC;
    DTSectionItem *_listSelectAllSection;
    DTCellItem *_listSelectAllCellItem;
    DTSectionItem *_filterSelectAllSection;
    DTCellItem *_filterSelectAllCellItem;
    NSDictionary *_listIndex;
    NSDictionary *_filterIndex;
    DTContactPickExternalSearchHandler *_searchHandler;
}

@property(retain, nonatomic) DTContactPickExternalSearchHandler *searchHandler; // @synthesize searchHandler=_searchHandler;
@property(copy, nonatomic) NSDictionary *filterIndex; // @synthesize filterIndex=_filterIndex;
@property(copy, nonatomic) NSDictionary *listIndex; // @synthesize listIndex=_listIndex;
@property(retain, nonatomic) DTCellItem *filterSelectAllCellItem; // @synthesize filterSelectAllCellItem=_filterSelectAllCellItem;
@property(retain, nonatomic) DTSectionItem *filterSelectAllSection; // @synthesize filterSelectAllSection=_filterSelectAllSection;
@property(retain, nonatomic) DTCellItem *listSelectAllCellItem; // @synthesize listSelectAllCellItem=_listSelectAllCellItem;
@property(retain, nonatomic) DTSectionItem *listSelectAllSection; // @synthesize listSelectAllSection=_listSelectAllSection;
@property(nonatomic) __weak DTContactPickExternalViewController *externalContactVC; // @synthesize externalContactVC=_externalContactVC;
- (void).cxx_destruct;
- (void)selectAllItemDidClick:(id)arg1 cell:(id)arg2 isSelected:(_Bool)arg3;
- (void)reloadTableViewData;
- (void)updateCellItemWithIdentifier:(id)arg1 isSelect:(_Bool)arg2;
- (void)personsHasUnselected:(id)arg1;
- (void)personsHasSelected:(id)arg1;
- (void)personHasUnselected:(id)arg1;
- (void)personHasSelected:(id)arg1;
- (id)genrateCellItemWithExternalContact:(id)arg1;
- (id)generateExternalContacts:(id)arg1 originDataSource:(id)arg2 totalCount:(long long)arg3 filterString:(id)arg4;
- (void)dealloc;
- (id)searchHandlerForExternalSearchVC:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

