//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "DTBaseCell.h"

@class DTCreateTeamCellItem, DTWebImageView, UIButton;

@interface DTCreateTeamCell : DTBaseCell
{
    DTCreateTeamCellItem *_cellItem;
    UIButton *_createButton;
    DTWebImageView *_iconView;
}

@property(retain, nonatomic) DTWebImageView *iconView; // @synthesize iconView=_iconView;
@property(retain, nonatomic) UIButton *createButton; // @synthesize createButton=_createButton;
@property(retain, nonatomic) DTCreateTeamCellItem *cellItem; // @synthesize cellItem=_cellItem;
- (void).cxx_destruct;
- (void)createTeam;
- (void)layoutSubViewsForCell;
- (void)configCellWithItem:(id)arg1;
- (id)initWithReuseIdentifier:(id)arg1;

@end

