//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "BLBaseAPITask.h"

@class DTBizCSpaceDentry, NSString;
@protocol DTCSpaceDentryPersistenceProtocol;

@interface DTCSpaceDentryDownloadTask : BLBaseAPITask
{
    NSString *_spaceId;
    NSString *_bizType;
    NSString *_objectId;
    DTBizCSpaceDentry *_downloadFile;
    id <DTCSpaceDentryPersistenceProtocol> _dentryPersistenceIMP;
    NSString *_downloadURL;
    unsigned long long _originDownloadedSize;
    double _startTimeInterval;
}

+ (void)plusDownloadFailCountWithSpaceId:(long long)arg1 itemId:(id)arg2;
+ (long long)downloadFailCountWithSpaceId:(long long)arg1 itemId:(id)arg2;
+ (id)downloadFailCountMap;
@property(nonatomic) double startTimeInterval; // @synthesize startTimeInterval=_startTimeInterval;
@property(nonatomic) unsigned long long originDownloadedSize; // @synthesize originDownloadedSize=_originDownloadedSize;
@property(retain, nonatomic) NSString *downloadURL; // @synthesize downloadURL=_downloadURL;
@property(retain, nonatomic) id <DTCSpaceDentryPersistenceProtocol> dentryPersistenceIMP; // @synthesize dentryPersistenceIMP=_dentryPersistenceIMP;
@property(retain, nonatomic) DTBizCSpaceDentry *downloadFile; // @synthesize downloadFile=_downloadFile;
@property(retain, nonatomic) NSString *objectId; // @synthesize objectId=_objectId;
@property(retain, nonatomic) NSString *bizType; // @synthesize bizType=_bizType;
@property(retain, nonatomic) NSString *spaceId; // @synthesize spaceId=_spaceId;
- (void).cxx_destruct;
- (unsigned long long)correctDownloadedSize;
- (void)reportDingPanDownloadFailed:(id)arg1 response:(id)arg2;
- (void)hanldeCompleteWithResponse:(id)arg1 successCallback:(CDUnknownBlockType)arg2 failCallback:(CDUnknownBlockType)arg3;
- (void)startDownload;
- (void)process;

@end

