//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "Marshal.h"

@class NSString;

@interface DTCSpaceAttachmentResultModel : Marshal
{
    NSString *_attachmentName;
    NSString *_fileId;
}

@property(copy, nonatomic) NSString *fileId; // @synthesize fileId=_fileId;
@property(copy, nonatomic) NSString *attachmentName; // @synthesize attachmentName=_attachmentName;
- (void).cxx_destruct;
- (id)filedsMeta__;
- (id)init;

@end

