//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSError;

@protocol DTCSpaceCoFolderDataSourceCallback <NSObject>

@optional
- (void)changeSortBtnEnable:(_Bool)arg1;
- (void)quitFolderFailedCallBack:(NSError *)arg1;
- (void)quitFolderSuccessCallBack;
- (void)createFolderFailedCallBack:(NSError *)arg1;
- (void)createFolderSuccessCallBack;
- (void)loadFolderDataFailed:(NSError *)arg1;
- (void)loadFolderDataSuccess;
@end

