//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "Marshal.h"

@class NSNumber, NSString;

@interface DTCSpaceBaseResultModel : Marshal
{
    NSNumber *_errorCode;
    NSString *_errorMessage;
}

@property(copy, nonatomic) NSString *errorMessage; // @synthesize errorMessage=_errorMessage;
@property(retain, nonatomic) NSNumber *errorCode; // @synthesize errorCode=_errorCode;
- (void).cxx_destruct;
- (id)filedsMeta__;
- (id)init;

@end

