//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "DTCMode.h"

#import "DTSpaceModel-Protocol.h"

@class NSString;

@interface DTCSpaceMode : DTCMode <DTSpaceModel>
{
    _Bool _copyable;
    _Bool _priority;
    _Bool _isEncrypt;
    NSString *_spaceId;
    NSString *_itemId;
    NSString *_path;
    NSString *_fileName;
    unsigned long long _fileSize;
    NSString *_fileType;
    NSString *_type;
    long long _oid;
    NSString *_cid;
    NSString *_cname;
    long long _mid;
    long long _appId;
    unsigned long long _duration;
    NSString *_picUrl;
    NSString *_picAuthUrl;
    NSString *_picAuthCode;
    long long _rotation;
    unsigned long long _picWidth;
    unsigned long long _picHeight;
    unsigned long long _picSize;
    unsigned long long _tag;
}

+ (long long)orgIdWithJsonDict:(id)arg1 cid:(id)arg2;
+ (id)jsonStringWithMode:(id)arg1;
+ (id)buildWithJsonDict:(id)arg1;
+ (id)buildWithJsonString:(id)arg1;
@property(nonatomic) unsigned long long tag; // @synthesize tag=_tag;
@property(nonatomic) unsigned long long picSize; // @synthesize picSize=_picSize;
@property(nonatomic) unsigned long long picHeight; // @synthesize picHeight=_picHeight;
@property(nonatomic) unsigned long long picWidth; // @synthesize picWidth=_picWidth;
@property(nonatomic) long long rotation; // @synthesize rotation=_rotation;
@property(copy, nonatomic) NSString *picAuthCode; // @synthesize picAuthCode=_picAuthCode;
@property(copy, nonatomic) NSString *picAuthUrl; // @synthesize picAuthUrl=_picAuthUrl;
@property(copy, nonatomic) NSString *picUrl; // @synthesize picUrl=_picUrl;
@property(nonatomic) unsigned long long duration; // @synthesize duration=_duration;
@property(nonatomic) _Bool isEncrypt; // @synthesize isEncrypt=_isEncrypt;
@property(nonatomic) _Bool priority; // @synthesize priority=_priority;
@property(nonatomic) long long appId; // @synthesize appId=_appId;
@property(nonatomic) _Bool copyable; // @synthesize copyable=_copyable;
@property(nonatomic) long long mid; // @synthesize mid=_mid;
@property(copy, nonatomic) NSString *cname; // @synthesize cname=_cname;
@property(copy, nonatomic) NSString *cid; // @synthesize cid=_cid;
@property(nonatomic) long long oid; // @synthesize oid=_oid;
@property(copy, nonatomic) NSString *type; // @synthesize type=_type;
@property(copy, nonatomic) NSString *fileType; // @synthesize fileType=_fileType;
@property(nonatomic) unsigned long long fileSize; // @synthesize fileSize=_fileSize;
@property(copy, nonatomic) NSString *fileName; // @synthesize fileName=_fileName;
@property(copy, nonatomic) NSString *path; // @synthesize path=_path;
@property(copy, nonatomic) NSString *itemId; // @synthesize itemId=_itemId;
@property(copy, nonatomic) NSString *spaceId; // @synthesize spaceId=_spaceId;
- (void).cxx_destruct;
- (id)stoken;
- (void)setStoken:(id)arg1;
- (void)setFolderFileType:(long long)arg1;
- (long long)folderFileType;
- (void)setCurrentConversation:(id)arg1;
- (id)currentConversation;

// Remaining properties
@property(copy, nonatomic) NSString *author;
@property(copy, nonatomic) NSString *contentDetail;
@property(copy, nonatomic) NSString *contentPicMediaId;
@property(copy, nonatomic) NSString *contentTitle;
@property(nonatomic) unsigned long long date;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(nonatomic) int fileCount;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(copy, nonatomic) NSString *title;
@property(copy, nonatomic) NSString *titleColor;

@end

