//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class DTBizCSpaceDentry;

@interface DTCSpaceUploadItem : NSObject
{
    DTBizCSpaceDentry *_file;
    CDUnknownBlockType _startCallback;
    CDUnknownBlockType _fileProgressCallback;
    CDUnknownBlockType _fileSuccessCallback;
    CDUnknownBlockType _fileCompleteCallback;
    CDUnknownBlockType _fileFailureCallback;
    id _asset;
}

@property(retain, nonatomic) id asset; // @synthesize asset=_asset;
@property(copy, nonatomic) CDUnknownBlockType fileFailureCallback; // @synthesize fileFailureCallback=_fileFailureCallback;
@property(copy, nonatomic) CDUnknownBlockType fileCompleteCallback; // @synthesize fileCompleteCallback=_fileCompleteCallback;
@property(copy, nonatomic) CDUnknownBlockType fileSuccessCallback; // @synthesize fileSuccessCallback=_fileSuccessCallback;
@property(copy, nonatomic) CDUnknownBlockType fileProgressCallback; // @synthesize fileProgressCallback=_fileProgressCallback;
@property(copy, nonatomic) CDUnknownBlockType startCallback; // @synthesize startCallback=_startCallback;
@property(retain, nonatomic) DTBizCSpaceDentry *file; // @synthesize file=_file;
- (void).cxx_destruct;
- (void)updateWithServerDentry:(id)arg1;
- (id)transfer2CSpaceError:(id)arg1;
- (void)markAsFinishUpload:(id)arg1 error:(id)arg2;
- (void)markAsComplete;
- (void)updateProgress:(unsigned long long)arg1 sentSize:(unsigned long long)arg2;
- (void)markAsStart;
- (void)markAsFailed:(id)arg1;

@end

