//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSArray, NSString;

@interface DTCSpaceMainSectionInfo : NSObject
{
    NSArray *_infos;
    unsigned long long _index;
    NSString *_sectionHeader;
    double _sectionHeaderHeight;
}

@property(nonatomic) double sectionHeaderHeight; // @synthesize sectionHeaderHeight=_sectionHeaderHeight;
@property(copy, nonatomic) NSString *sectionHeader; // @synthesize sectionHeader=_sectionHeader;
@property(nonatomic) unsigned long long index; // @synthesize index=_index;
@property(copy, nonatomic) NSArray *infos; // @synthesize infos=_infos;
- (void).cxx_destruct;

@end

