//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSMutableDictionary, NSMutableSet, NSRecursiveLock, YYThreadSafeArray;

@interface DTCSConfInfoManager : NSObject
{
    _Bool _initialized;
    YYThreadSafeArray *_waitBlocks;
    long long _currentUid;
    NSMutableSet *_reqTopicSet;
    NSRecursiveLock *_reqLock;
    NSMutableDictionary *_csTopicDic;
    NSRecursiveLock *_topicLock;
    NSMutableDictionary *_csConfigDic;
    NSRecursiveLock *_configLock;
}

+ (id)sharedManager;
@property(retain, nonatomic) NSRecursiveLock *configLock; // @synthesize configLock=_configLock;
@property(retain, nonatomic) NSMutableDictionary *csConfigDic; // @synthesize csConfigDic=_csConfigDic;
@property(retain, nonatomic) NSRecursiveLock *topicLock; // @synthesize topicLock=_topicLock;
@property(retain, nonatomic) NSMutableDictionary *csTopicDic; // @synthesize csTopicDic=_csTopicDic;
@property(retain, nonatomic) NSRecursiveLock *reqLock; // @synthesize reqLock=_reqLock;
@property(retain, nonatomic) NSMutableSet *reqTopicSet; // @synthesize reqTopicSet=_reqTopicSet;
@property(nonatomic) long long currentUid; // @synthesize currentUid=_currentUid;
@property(retain, nonatomic) YYThreadSafeArray *waitBlocks; // @synthesize waitBlocks=_waitBlocks;
@property _Bool initialized; // @synthesize initialized=_initialized;
- (void).cxx_destruct;
- (id)requestingTopics;
- (void)flushWaiteBlocks:(_Bool)arg1;
- (void)doAfterInitialesd:(CDUnknownBlockType)arg1;
- (_Bool)shouldUpdateOAActivityTopic:(id)arg1;
- (void)onScreenUnlockNotification:(id)arg1;
- (void)onAccountLogoutNotification:(id)arg1;
- (void)onAccountLoginNotification:(id)arg1;
- (void)handleCloudSettingNotify:(id)arg1;
- (void)showTipsAlertIfNeed;
- (void)filterInvalidNotes:(id)arg1 parentDictionary:(id)arg2 key:(id)arg3;
- (id)filterDiffDictinary:(id)arg1;
- (void)updateDictionary:(id)arg1 withDictionary:(id)arg2 parentDictionary:(id)arg3 mKey:(id)arg4 topic:(id)arg5;
- (id)mergeJson:(id)arg1 subJson:(id)arg2 topic:(id)arg3 localVersion:(long long)arg4;
- (void)handleOAUserJsonDataError:(id)arg1 localVersion:(long long)arg2;
- (_Bool)updateBizConfigWithCsConfigModel:(id)arg1;
- (void)updateBizTopicWithCsConfigModel:(id)arg1;
- (void)refreshConfigurationsWithTopics:(id)arg1;
- (void)checkAndRefreshTopic;
- (id)fetchLocalBizCsConfigs;
- (id)fetchLocalBizCsTopics;
- (void)fetchLocalConfigurations;
- (void)loadLocalCsConfigs;
- (void)clearConfigurations;
- (long long)configVersionWithTopic:(id)arg1;
- (id)configDataWithTopic:(id)arg1;
- (void)dealloc;
- (id)init;
- (id)parseJsapiMapList;
- (id)parseActivityInfo;
- (_Bool)isHolderReplaceEnable;
- (_Bool)isWebViewMonitorEnabled;
- (id)parseFunControlDictionary;
- (id)userPDPRoles;
- (id)parseChannelList;
- (id)searchShortcutData;
- (void)uploadZipWithZipPath:(id)arg1 completeBlock:(CDUnknownBlockType)arg2;
- (_Bool)addCSConfInfoLogToZipWithZipArchive:(id)arg1;
- (_Bool)generateZipWithPath:(id)arg1 addContentToZipBlock:(CDUnknownBlockType)arg2;
- (void)generateLogWithTopic:(id)arg1 filePath:(id)arg2;
- (id)logFilePathWithlogFileName:(id)arg1;
- (id)logDirectroyPath;
- (id)logFileNameWithNamePrefix:(id)arg1 topic:(id)arg2;
- (id)logFileNamePrefix;
- (void)cleanLogFiles;
- (void)uploadCSConfInfoWithTopics:(id)arg1 completedBlock:(CDUnknownBlockType)arg2;
- (void)uploadCSConfInfoWithTopic:(id)arg1 completedBlock:(CDUnknownBlockType)arg2;
- (void)uploadAllCSConfInfosWithCompletedBlock:(CDUnknownBlockType)arg1;
- (_Bool)needPopRoleSelection;
- (unsigned long long)lowerLimitForIndustryCode:(unsigned long long)arg1;
- (_Bool)isRecommendExperienceTeam;
- (id)getConfigTopicData;
- (id)getArtificialServiceContent;
- (_Bool)isSupportArtificialService;
- (id)userConfiguration;
- (void)clearLocalOAUserDataAndReload;
- (_Bool)checkOAUserDataValidityWithContact:(id)arg1;
- (_Bool)checkWorkInfoValidity:(id)arg1;
- (_Bool)checkOAUserDataInnerValidity:(id)arg1;
- (void)checkOAUserDataValidity:(id)arg1;
- (void)delayAndCheckOAUserDataValidity:(id)arg1;
- (id)parseWorkInfoList;
- (id)parseSyncAppIdsForHPM;
- (id)parseSyncInfoForHPM;
- (_Bool)compareHpmInfo:(id)arg1 newInfo:(id)arg2;
- (id)hpmInfoWithAppId:(id)arg1 appDic:(id)arg2;
- (id)appIdToAppInfoDictionary;
- (id)findValueFrom:(id)arg1 key:(id)arg2;
- (_Bool)isSendMailToGroupShowInSetting;
- (_Bool)isSendMailToGroupShow;
- (long long)maxGroupNumberToSendMail;

@end

