//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class DTConversationGroupRule, UIViewController, WKBizConversationGroup;

@interface DTCustomGroupChatListDataLoader : NSObject
{
    DTConversationGroupRule *_groupRule;
    UIViewController *_controller;
    WKBizConversationGroup *_group;
    CDUnknownBlockType _didLoadRowItemsBlock;
    CDUnknownBlockType _didLoadMissedConversationBlock;
}

@property(copy, nonatomic) CDUnknownBlockType didLoadMissedConversationBlock; // @synthesize didLoadMissedConversationBlock=_didLoadMissedConversationBlock;
@property(copy, nonatomic) CDUnknownBlockType didLoadRowItemsBlock; // @synthesize didLoadRowItemsBlock=_didLoadRowItemsBlock;
@property(retain, nonatomic) WKBizConversationGroup *group; // @synthesize group=_group;
@property(readonly, nonatomic) __weak UIViewController *controller; // @synthesize controller=_controller;
- (void).cxx_destruct;
- (id)filterByConversations:(id)arg1;
- (void)clearGroupGap;
- (void)handleGroupGapWithLocalCids:(id)arg1;
- (id)findMissedCidsInCacheTable:(id)arg1 withCids:(id)arg2;
- (void)loadConversations;
- (void)didFinishLoadMissedConversations:(id)arg1;
- (id)initWithController:(id)arg1 groupRule:(id)arg2;
- (id)initWithController:(id)arg1 group:(id)arg2;

@end

