//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class UIViewController;

@protocol DTDentrySearchInterface <NSObject>
- (void)setOutViewController:(UIViewController *)arg1;
- (_Bool)isActive;
- (void)setUnActive:(UIViewController *)arg1;
- (void)setActive:(UIViewController *)arg1;
- (void)didSearchFail;
- (void)didSearchSuccess;

@optional
- (void)initOrgInfoWithCompletionBlock:(void (^)(NSError *))arg1;
- (void)reloadData;
- (void)didClearHistoryKeyword;
- (void)showMoreResultsFail;
- (void)showMoreResultsSuccess:(_Bool)arg1;
@end

