//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "DTCSpacePhotoBrowserDataSource-Protocol.h"

@class BLSpaceEntry, DTBizCSpaceDentry, DTCSpaceOperationProcessor, DTCSpacePhotoItem, NSString, UIViewController;
@protocol BLCancelable, DTDentryDetailInterfaceV1, OS_dispatch_queue, SDWebImageOperation;

@interface DTDentryDetailPresenterV1 : NSObject <DTCSpacePhotoBrowserDataSource>
{
    _Bool forceUseDBObject;
    _Bool _checkPrivilege;
    _Bool _isDownloading;
    _Bool _saveTemp;
    _Bool _isWaterMark;
    _Bool _isDocReadOnly;
    _Bool _isLocalPreview;
    UIViewController<DTDentryDetailInterfaceV1> *_userInterface;
    NSString *_token;
    BLSpaceEntry *_spaceEntry;
    DTBizCSpaceDentry *_file;
    id <BLCancelable> _downloadCancelItem;
    DTCSpacePhotoItem *_photoItem;
    NSObject<OS_dispatch_queue> *_ioQueue;
    id <SDWebImageOperation> _sdOperation;
    DTCSpaceOperationProcessor *_operationProcessor;
    NSString *_finalFilePath;
    NSString *_finalFileType;
}

+ (id)directPreviewFileType;
+ (id)supportPreviewFileType;
@property(nonatomic) _Bool isLocalPreview; // @synthesize isLocalPreview=_isLocalPreview;
@property(copy, nonatomic) NSString *finalFileType; // @synthesize finalFileType=_finalFileType;
@property(copy, nonatomic) NSString *finalFilePath; // @synthesize finalFilePath=_finalFilePath;
@property(nonatomic) _Bool isDocReadOnly; // @synthesize isDocReadOnly=_isDocReadOnly;
@property(nonatomic) _Bool isWaterMark; // @synthesize isWaterMark=_isWaterMark;
@property(retain, nonatomic) DTCSpaceOperationProcessor *operationProcessor; // @synthesize operationProcessor=_operationProcessor;
@property(nonatomic) _Bool saveTemp; // @synthesize saveTemp=_saveTemp;
@property(retain, nonatomic) id <SDWebImageOperation> sdOperation; // @synthesize sdOperation=_sdOperation;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *ioQueue; // @synthesize ioQueue=_ioQueue;
@property(retain, nonatomic) DTCSpacePhotoItem *photoItem; // @synthesize photoItem=_photoItem;
@property(retain, nonatomic) id <BLCancelable> downloadCancelItem; // @synthesize downloadCancelItem=_downloadCancelItem;
@property(retain, nonatomic) DTBizCSpaceDentry *file; // @synthesize file=_file;
@property(nonatomic) _Bool isDownloading; // @synthesize isDownloading=_isDownloading;
@property(nonatomic) _Bool checkPrivilege; // @synthesize checkPrivilege=_checkPrivilege;
@property(retain, nonatomic) BLSpaceEntry *spaceEntry; // @synthesize spaceEntry=_spaceEntry;
@property(copy, nonatomic) NSString *token; // @synthesize token=_token;
@property(nonatomic) __weak UIViewController<DTDentryDetailInterfaceV1> *userInterface; // @synthesize userInterface=_userInterface;
@property(nonatomic) _Bool forceUseDBObject; // @synthesize forceUseDBObject;
- (void).cxx_destruct;
- (unsigned long long)sourceOperationType;
- (void)processRename:(id)arg1;
- (void)processDelete:(id)arg1;
- (void)cancelDownloadPhotoWithKey:(id)arg1;
- (id)downloadPhotoAtIndex:(unsigned long long)arg1 progress:(CDUnknownBlockType)arg2 completion:(CDUnknownBlockType)arg3;
- (id)photoRequestHeader;
- (id)photoAtIndex:(unsigned long long)arg1;
- (_Bool)enableLongPressGesture;
- (id)photoes;
- (unsigned long long)currentPhotoIndex;
- (unsigned long long)photoCounts;
- (void)previewHTMLWithFilePath:(id)arg1;
- (void)previewTXTWithFilePath:(id)arg1;
- (void)previewAudioWithFilePath:(id)arg1;
- (void)previewEMLWithFilePath:(id)arg1;
- (void)previewImageWithFilePath:(id)arg1;
- (_Bool)needCheckPriviligeWithDentry:(id)arg1;
- (_Bool)isDirectPreviewFile:(id)arg1;
- (_Bool)directPreviewOnlineIfNeeded:(id)arg1;
- (void)downloadPreviewableFile:(id)arg1;
- (void)downloadOriginFile:(id)arg1 automaticly:(_Bool)arg2;
- (void)checkDentryExist:(id)arg1;
- (id)formatSizeString:(double)arg1;
- (_Bool)downloadIfNeed:(id)arg1;
- (void)previewDentry:(id)arg1 localFilePath:(id)arg2 localFileType:(id)arg3 automaticly:(_Bool)arg4;
- (void)startDownload:(id)arg1 automaticly:(_Bool)arg2;
- (unsigned long long)checkDownloadStatus:(id)arg1;
- (_Bool)hasFullPrivilege;
- (_Bool)isFileReadOnly;
- (_Bool)isShowWaterMark;
- (_Bool)isFileSupportQuickLookPreview:(id)arg1 size:(unsigned long long)arg2;
- (_Bool)isFileSupportOnlinePreview:(id)arg1 size:(unsigned long long)arg2;
- (void)viewPhoto:(id)arg1;
- (void)moveDentry:(id)arg1 toTarget:(id)arg2;
- (void)deleteDentry:(id)arg1;
- (void)stopDownload:(id)arg1;
- (void)pauseOrResumeDownload:(id)arg1;
- (void)startDownload:(id)arg1;
- (_Bool)previewDocDentryOnline:(id)arg1;
- (void)cleanView;
- (void)_setupWithDentry:(id)arg1;
- (void)setupWithDentry:(id)arg1;
- (id)dateString:(double)arg1;
- (void)setupWithDentrySimpleModel:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

