//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "DTTableViewController.h"

@interface DTDebugListController : DTTableViewController
{
}

- (void)addWKWebViewURLPrefix:(id)arg1;
- (void)showWKWebViewURLPrefixConfigAlert;
- (void)logFastConfigLocalStrage;
- (void)swithcJavaScriptRunMode;
- (void)switchHpmEnvironment;
- (void)clearConferenceInfo;
- (void)adjustImageDownConcurrent;
- (void)switchImageDownloadOperation;
- (void)selectEnvironment;
- (void)manualUploadCSConfig;
- (void)openSpdySwitch;
- (void)changeSpdyLogLevel;
- (void)showQueryPage;
- (void)openNetDiagnoserViewController;
- (void)showDeviceTokenPage;
- (void)loadDatasource;
- (void)viewDidLoad;

@end

