//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface DTDID : NSObject
{
}

+ (void)setEnableDidBindEnv:(_Bool)arg1;
+ (_Bool)_isEnableDidBindEnv;
+ (_Bool)_isBindEnvChanged;
+ (_Bool)_saveDid:(id)arg1;
+ (void)_saveDeviceEnv;
+ (id)_readDeviceEnv;
+ (id)_calcDeviceEnv;
+ (id)generateNewDid;
+ (id)generateOldDid;
+ (void)resetDid:(id)arg1;
+ (id)did;

@end

