//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "DTContactTableViewCell.h"

@class UIButton, UIImageView;

@interface DTDingReceiverStatusTableViewCellV2 : DTContactTableViewCell
{
    _Bool _isPicker;
    _Bool _isUnConfirm;
    UIButton *_iconButton;
    UIImageView *_statusBgImageView;
}

+ (double)calculateCellHeight:(id)arg1 cellWidth:(double)arg2;
@property(retain, nonatomic) UIImageView *statusBgImageView; // @synthesize statusBgImageView=_statusBgImageView;
@property(retain, nonatomic) UIButton *iconButton; // @synthesize iconButton=_iconButton;
@property(nonatomic) _Bool isUnConfirm; // @synthesize isUnConfirm=_isUnConfirm;
@property(nonatomic) _Bool isPicker; // @synthesize isPicker=_isPicker;
- (void).cxx_destruct;
- (void)configCellWithContactItem:(id)arg1;
- (void)layoutSubviews;
- (void)setPickerStyle:(_Bool)arg1;
- (void)userNameLabelTextDidChange:(id)arg1 change:(id)arg2;
- (id)initWithCellStyle:(unsigned long long)arg1 reuseIdentifier:(id)arg2;

@end

