//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "Marshal.h"

@class NSNumber, NSString;

@interface DTDingConfirmPushModel : Marshal
{
    NSNumber *_dingId;
    NSNumber *_receiverId;
    NSString *_extInfo;
    NSNumber *_unconfirmCount;
    NSNumber *_modelTypeInTopic;
}

@property(retain, nonatomic) NSNumber *modelTypeInTopic; // @synthesize modelTypeInTopic=_modelTypeInTopic;
@property(retain, nonatomic) NSNumber *unconfirmCount; // @synthesize unconfirmCount=_unconfirmCount;
@property(copy, nonatomic) NSString *extInfo; // @synthesize extInfo=_extInfo;
@property(retain, nonatomic) NSNumber *receiverId; // @synthesize receiverId=_receiverId;
@property(retain, nonatomic) NSNumber *dingId; // @synthesize dingId=_dingId;
- (void).cxx_destruct;
- (id)filedsMeta__;
- (id)init;

@end

