//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class DTBizDingModel, UIButton;

@interface DTDingListCellContentBottomActionView : UIView
{
    CDUnknownBlockType _leftButtonDidTapCallback;
    CDUnknownBlockType _rightButtonDidTapCallback;
    DTBizDingModel *_dingModel;
    UIButton *_leftButton;
    UIButton *_rightButton;
    UIView *_topSeparator;
    UIView *_divider;
}

+ (struct CGSize)sizeThatFits:(struct CGSize)arg1 withDingModel:(id)arg2;
@property(retain, nonatomic) UIView *divider; // @synthesize divider=_divider;
@property(retain, nonatomic) UIView *topSeparator; // @synthesize topSeparator=_topSeparator;
@property(retain, nonatomic) UIButton *rightButton; // @synthesize rightButton=_rightButton;
@property(retain, nonatomic) UIButton *leftButton; // @synthesize leftButton=_leftButton;
@property(retain, nonatomic) DTBizDingModel *dingModel; // @synthesize dingModel=_dingModel;
@property(copy, nonatomic) CDUnknownBlockType rightButtonDidTapCallback; // @synthesize rightButtonDidTapCallback=_rightButtonDidTapCallback;
@property(copy, nonatomic) CDUnknownBlockType leftButtonDidTapCallback; // @synthesize leftButtonDidTapCallback=_leftButtonDidTapCallback;
- (void).cxx_destruct;
- (void)rightButtonDidTap:(id)arg1;
- (void)leftButtonDidTap:(id)arg1;
- (void)updateSubViewFrame;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

