//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "Marshal.h"

@class NSArray, NSNumber, NSString;

@interface DTDingUnreadModel : Marshal
{
    NSString *_statusMessage;
    NSNumber *_statusCode;
    NSArray *_unreadUsers;
}

@property(copy, nonatomic) NSArray *unreadUsers; // @synthesize unreadUsers=_unreadUsers;
@property(retain, nonatomic) NSNumber *statusCode; // @synthesize statusCode=_statusCode;
@property(copy, nonatomic) NSString *statusMessage; // @synthesize statusMessage=_statusMessage;
- (void).cxx_destruct;
- (id)filedsMeta__;
- (id)init;

@end

