//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "DTDingCreatorInputParams-Protocol.h"
#import "DTDingInputParamProtocol-Protocol.h"

@class DTBizConversation, DTBizDingAttachmentAudio, DTBizDingLinkModel, DTBizDingModel, DTBizMessage, DTDingDraftModel, NSArray, NSDate, NSString;

@interface DTDingCreatorInputParams : NSObject <DTDingInputParamProtocol, DTDingCreatorInputParams>
{
    _Bool _needLoadDraft;
    _Bool _applyDraftByConfirm;
    _Bool _goDingListWhenSucceed;
    _Bool _canEditable;
    _Bool _showAddNewReceiver;
    _Bool _showPickGroupMember;
    _Bool _notShowDeleteAttachmentsBtn;
    _Bool _isAudioContentTypeDefaultSelected;
    _Bool _ignoreShowAlert;
    _Bool _isFocusDing;
    _Bool _disableSelectReceivers;
    _Bool _isTaskDing;
    _Bool _isWisper;
    NSArray *_recorderUserIds;
    DTBizMessage *_message;
    DTBizConversation *_conversation;
    NSArray *_selectedUserIds;
    long long _receiverCount;
    long long _defaultRemindType;
    CDUnknownBlockType _successBlock;
    CDUnknownBlockType _failBlock;
    CDUnknownBlockType _cancelBlock;
    NSDate *_sendTime;
    DTBizDingLinkModel *_linkModel;
    NSArray *_attachments;
    long long _contentType;
    NSString *_textContent;
    DTBizDingAttachmentAudio *_audioAttach;
    NSString *_amrFilePath;
    NSString *_mediaId;
    unsigned long long _source;
    DTBizDingModel *_referencedDingModel;
    long long _parentId;
    NSArray *_ccUids;
    long long _ccCount;
    NSString *_customTitle;
    long long _deadlineTime;
    long long _taskRemindMinutes;
    long long _taskRemindUrgentLevel;
    unsigned long long _bizSource;
    NSString *_bizId;
    DTDingDraftModel *_draftModel;
    long long _inputType;
}

@property(nonatomic) long long inputType; // @synthesize inputType=_inputType;
@property(readonly, nonatomic) DTDingDraftModel *draftModel; // @synthesize draftModel=_draftModel;
@property(copy, nonatomic) NSString *bizId; // @synthesize bizId=_bizId;
@property(nonatomic) unsigned long long bizSource; // @synthesize bizSource=_bizSource;
@property(nonatomic) _Bool isWisper; // @synthesize isWisper=_isWisper;
@property(nonatomic) long long taskRemindUrgentLevel; // @synthesize taskRemindUrgentLevel=_taskRemindUrgentLevel;
@property(nonatomic) long long taskRemindMinutes; // @synthesize taskRemindMinutes=_taskRemindMinutes;
@property(nonatomic) long long deadlineTime; // @synthesize deadlineTime=_deadlineTime;
@property(nonatomic) _Bool isTaskDing; // @synthesize isTaskDing=_isTaskDing;
@property(copy, nonatomic) NSString *customTitle; // @synthesize customTitle=_customTitle;
@property(nonatomic) long long ccCount; // @synthesize ccCount=_ccCount;
@property(copy, nonatomic) NSArray *ccUids; // @synthesize ccUids=_ccUids;
@property(nonatomic) long long parentId; // @synthesize parentId=_parentId;
@property(retain, nonatomic) DTBizDingModel *referencedDingModel; // @synthesize referencedDingModel=_referencedDingModel;
@property(nonatomic) _Bool disableSelectReceivers; // @synthesize disableSelectReceivers=_disableSelectReceivers;
@property(nonatomic) unsigned long long source; // @synthesize source=_source;
@property(nonatomic) _Bool isFocusDing; // @synthesize isFocusDing=_isFocusDing;
@property(nonatomic) _Bool ignoreShowAlert; // @synthesize ignoreShowAlert=_ignoreShowAlert;
@property(copy, nonatomic) NSString *mediaId; // @synthesize mediaId=_mediaId;
@property(nonatomic) _Bool isAudioContentTypeDefaultSelected; // @synthesize isAudioContentTypeDefaultSelected=_isAudioContentTypeDefaultSelected;
@property(copy, nonatomic) NSString *amrFilePath; // @synthesize amrFilePath=_amrFilePath;
@property(retain, nonatomic) DTBizDingAttachmentAudio *audioAttach; // @synthesize audioAttach=_audioAttach;
@property(copy, nonatomic) NSString *textContent; // @synthesize textContent=_textContent;
@property(nonatomic) long long contentType; // @synthesize contentType=_contentType;
@property(copy, nonatomic) NSArray *attachments; // @synthesize attachments=_attachments;
@property(retain, nonatomic) DTBizDingLinkModel *linkModel; // @synthesize linkModel=_linkModel;
@property(retain, nonatomic) NSDate *sendTime; // @synthesize sendTime=_sendTime;
@property(copy, nonatomic) CDUnknownBlockType cancelBlock; // @synthesize cancelBlock=_cancelBlock;
@property(copy, nonatomic) CDUnknownBlockType failBlock; // @synthesize failBlock=_failBlock;
@property(copy, nonatomic) CDUnknownBlockType successBlock; // @synthesize successBlock=_successBlock;
@property(nonatomic) _Bool notShowDeleteAttachmentsBtn; // @synthesize notShowDeleteAttachmentsBtn=_notShowDeleteAttachmentsBtn;
@property(nonatomic) _Bool showPickGroupMember; // @synthesize showPickGroupMember=_showPickGroupMember;
@property(nonatomic) _Bool showAddNewReceiver; // @synthesize showAddNewReceiver=_showAddNewReceiver;
@property(nonatomic) long long defaultRemindType; // @synthesize defaultRemindType=_defaultRemindType;
@property(nonatomic) _Bool canEditable; // @synthesize canEditable=_canEditable;
@property(nonatomic) _Bool goDingListWhenSucceed; // @synthesize goDingListWhenSucceed=_goDingListWhenSucceed;
@property(nonatomic) long long receiverCount; // @synthesize receiverCount=_receiverCount;
@property(copy, nonatomic) NSArray *selectedUserIds; // @synthesize selectedUserIds=_selectedUserIds;
@property(retain, nonatomic) DTBizConversation *conversation; // @synthesize conversation=_conversation;
@property(retain, nonatomic) DTBizMessage *message; // @synthesize message=_message;
@property(nonatomic) _Bool applyDraftByConfirm; // @synthesize applyDraftByConfirm=_applyDraftByConfirm;
@property(nonatomic) _Bool needLoadDraft; // @synthesize needLoadDraft=_needLoadDraft;
@property(copy, nonatomic) NSArray *recorderUserIds; // @synthesize recorderUserIds=_recorderUserIds;
- (void).cxx_destruct;
- (void)configWithDraftModel:(CDUnknownBlockType)arg1;
- (_Bool)needUseDraftCCList:(id)arg1;
- (_Bool)needUseDraftReceiverList:(id)arg1;
- (_Bool)isValidTime:(long long)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

