//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "DTDownloadStrategyDelegate-Protocol.h"
#import "DTWebImageStrategyDelegate-Protocol.h"

@class NSString;

@interface DTDownloadIMP : NSObject <DTDownloadStrategyDelegate, DTWebImageStrategyDelegate>
{
    _Bool _isLogin;
}

+ (id)buildCacheKeyFilter:(id)arg1;
+ (id)sharedIMP;
@property _Bool isLogin; // @synthesize isLogin=_isLogin;
- (id)webImageManager:(id)arg1 imageControl:(id)arg2;
- (void)configureDTDLManager;
- (void)configureDTWebImageManager;
- (void)configureSDWebImageManager;
- (id)downloadBigImageWithSpaceId:(id)arg1 itemId:(id)arg2 progress:(CDUnknownBlockType)arg3 completed:(CDUnknownBlockType)arg4;
- (id)downloadBigImageWithURL:(id)arg1 progress:(CDUnknownBlockType)arg2 completed:(CDUnknownBlockType)arg3;
- (void)didDDSidUpdateNotification:(id)arg1;
- (void)configDownload;
- (void)didSignOut:(id)arg1;
- (void)didSignUp:(id)arg1;
- (void)didSignIn:(id)arg1;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

