//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SClient.h"

@interface DTDpOrgService : SClient
{
}

+ (id)_appname__;
+ (id)_serviceKey__;
- (void)getOrgConversations:(id)arg1 start:(id)arg2 size:(id)arg3 byOrder:(id)arg4 callback:(id)arg5;

@end

