//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "Marshal.h"

@class NSNumber, NSString;

@interface DTDynamicEmotionModel : Marshal
{
    NSString *_dynamicEmotionId;
    NSString *_mediaId;
    NSNumber *_width;
    NSNumber *_height;
    NSString *_thumbUrl;
    NSNumber *_thumbWidth;
    NSNumber *_thumbHeight;
    NSString *_authMediaId;
    NSString *_source;
}

@property(copy, nonatomic) NSString *source; // @synthesize source=_source;
@property(copy, nonatomic) NSString *authMediaId; // @synthesize authMediaId=_authMediaId;
@property(retain, nonatomic) NSNumber *thumbHeight; // @synthesize thumbHeight=_thumbHeight;
@property(retain, nonatomic) NSNumber *thumbWidth; // @synthesize thumbWidth=_thumbWidth;
@property(copy, nonatomic) NSString *thumbUrl; // @synthesize thumbUrl=_thumbUrl;
@property(retain, nonatomic) NSNumber *height; // @synthesize height=_height;
@property(retain, nonatomic) NSNumber *width; // @synthesize width=_width;
@property(copy, nonatomic) NSString *mediaId; // @synthesize mediaId=_mediaId;
@property(copy, nonatomic) NSString *dynamicEmotionId; // @synthesize dynamicEmotionId=_dynamicEmotionId;
- (void).cxx_destruct;
- (id)filedsMeta__;
- (id)init;
- (id)downloadURL;

@end

