//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "DTTableViewController.h"

@class DTButtonView, DTCell, DTSectionItem, DTWebImageView, UIImage, UITextField;

@interface DTEditRootDeptViewController : DTTableViewController
{
    UITextField *_editingTextField;
    DTCell *_currentEditingCell;
    DTButtonView *_nextButton;
    UIImage *_placeholderImage;
    DTWebImageView *_bannerImageView;
    DTSectionItem *_deptSectionItem;
}

@property(retain, nonatomic) DTSectionItem *deptSectionItem; // @synthesize deptSectionItem=_deptSectionItem;
@property(retain, nonatomic) DTWebImageView *bannerImageView; // @synthesize bannerImageView=_bannerImageView;
@property(retain, nonatomic) UIImage *placeholderImage; // @synthesize placeholderImage=_placeholderImage;
@property(retain, nonatomic) DTButtonView *nextButton; // @synthesize nextButton=_nextButton;
@property(retain, nonatomic) DTCell *currentEditingCell; // @synthesize currentEditingCell=_currentEditingCell;
@property(retain, nonatomic) UITextField *editingTextField; // @synthesize editingTextField=_editingTextField;
- (void).cxx_destruct;
- (void)nextButtonClick:(id)arg1;
- (void)onKeyboardWillHide:(id)arg1;
- (void)onKeyboardWillShow:(id)arg1;
- (void)hideKeyboard;
- (void)pickCityOfTeam:(id)arg1;
- (id)itemWithInsertModel;
- (void)insertItem:(id)arg1 intoDataSource:(id)arg2;
- (void)removeItem:(id)arg1 formDataSource:(id)arg2;
- (id)itemWithDeleteModel;
- (void)setBannerImage;
- (id)showsDeparts:(id)arg1;
- (void)getTemplateDeparts;
- (void)loadDataSource;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)clickEvent:(id)arg1;
- (void)hideKeyboardActionForView:(id)arg1;
- (void)viewWillLayoutSubviews;
- (void)viewDidLoad;
- (id)init;

@end

