//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "Marshal.h"

@class NSArray, NSNumber, NSString;

@interface DTExternalContactModelList : Marshal
{
    _Bool _hasMore;
    NSArray *_orgExternalModels;
    NSNumber *_totalOrg;
    NSNumber *_totalContactCount;
    NSString *_nextCursor;
    NSString *_logMap;
}

@property(copy, nonatomic) NSString *logMap; // @synthesize logMap=_logMap;
@property(nonatomic) _Bool hasMore; // @synthesize hasMore=_hasMore;
@property(copy, nonatomic) NSString *nextCursor; // @synthesize nextCursor=_nextCursor;
@property(retain, nonatomic) NSNumber *totalContactCount; // @synthesize totalContactCount=_totalContactCount;
@property(retain, nonatomic) NSNumber *totalOrg; // @synthesize totalOrg=_totalOrg;
@property(copy, nonatomic) NSArray *orgExternalModels; // @synthesize orgExternalModels=_orgExternalModels;
- (void).cxx_destruct;
- (id)filedsMeta__;
- (id)init;

@end

