//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "DTGroupedAppViewDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"

@class DTDefaultWorkAppView, DTViewMicroAppItem, NSArray, NSString;
@protocol DTGroupedAppDelegate;

@interface DTGroupedAppDatasource : NSObject <UITableViewDataSource, DTGroupedAppViewDelegate>
{
    DTViewMicroAppItem *_appItem;
    DTDefaultWorkAppView *_mainAppView;
    id <DTGroupedAppDelegate> _delegate;
    long long _orgId;
    NSArray *_microItemList;
}

@property(copy, nonatomic) NSArray *microItemList; // @synthesize microItemList=_microItemList;
@property(nonatomic) long long orgId; // @synthesize orgId=_orgId;
@property(nonatomic) __weak id <DTGroupedAppDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) DTDefaultWorkAppView *mainAppView; // @synthesize mainAppView=_mainAppView;
@property(retain, nonatomic) DTViewMicroAppItem *appItem; // @synthesize appItem=_appItem;
- (void).cxx_destruct;
- (void)groupedAppViewTableViewDidDismiss:(id)arg1;
- (double)groupedAppViewTableViewHeight:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 viewForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)fetchDatasourceWithAppItem:(id)arg1;
- (id)initWithOrgId:(long long)arg1 appItem:(id)arg2 mainAppView:(id)arg3;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

