//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class DTGraffitiPanelDot, UIColor;

@interface DTGraffitiPanelDotItem : NSObject
{
    _Bool _isSelect;
    DTGraffitiPanelDot *_dot;
    UIColor *_bgColor;
    CDUnknownBlockType _actionBlock;
}

@property(copy, nonatomic) CDUnknownBlockType actionBlock; // @synthesize actionBlock=_actionBlock;
@property(retain, nonatomic) UIColor *bgColor; // @synthesize bgColor=_bgColor;
@property(nonatomic) _Bool isSelect; // @synthesize isSelect=_isSelect;
@property(nonatomic) __weak DTGraffitiPanelDot *dot; // @synthesize dot=_dot;
- (void).cxx_destruct;

@end

