//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSString;

@interface DTHorizontalPopdownItem : NSObject
{
    NSString *_title;
    NSString *_normalIcon;
    NSString *_highlightIcon;
    NSString *_superscript;
    CDUnknownBlockType _clickBlock;
    CDUnknownBlockType _longPressBlock;
}

@property(copy, nonatomic) CDUnknownBlockType longPressBlock; // @synthesize longPressBlock=_longPressBlock;
@property(copy, nonatomic) CDUnknownBlockType clickBlock; // @synthesize clickBlock=_clickBlock;
@property(copy, nonatomic) NSString *superscript; // @synthesize superscript=_superscript;
@property(copy, nonatomic) NSString *highlightIcon; // @synthesize highlightIcon=_highlightIcon;
@property(copy, nonatomic) NSString *normalIcon; // @synthesize normalIcon=_normalIcon;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
- (void).cxx_destruct;
- (id)initWithTitle:(id)arg1 normalIcon:(id)arg2 highlightIcon:(id)arg3 superscript:(id)arg4 clickBlock:(CDUnknownBlockType)arg5 longPressBlock:(CDUnknownBlockType)arg6;

@end

