//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "Marshal.h"

@class NSData, NSNumber, NSString;

@interface DTHttp2LwpRspModel : Marshal
{
    NSNumber *_httpErrorCode;
    NSString *_httpErrorReason;
    NSNumber *_code;
    NSData *_body;
}

@property(retain, nonatomic) NSData *body; // @synthesize body=_body;
@property(retain, nonatomic) NSNumber *code; // @synthesize code=_code;
@property(copy, nonatomic) NSString *httpErrorReason; // @synthesize httpErrorReason=_httpErrorReason;
@property(retain, nonatomic) NSNumber *httpErrorCode; // @synthesize httpErrorCode=_httpErrorCode;
- (void).cxx_destruct;
- (id)filedsMeta__;
- (id)init;

@end

