//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class DTBadgeView, DTIcon, DTIconButton;

@interface DTIconView : UIView
{
    DTIcon *_iconModel;
    DTIconButton *_icon;
    DTBadgeView *_badge;
}

@property(retain, nonatomic) DTBadgeView *badge; // @synthesize badge=_badge;
@property(retain, nonatomic) DTIconButton *icon; // @synthesize icon=_icon;
@property(retain, nonatomic) DTIcon *iconModel; // @synthesize iconModel=_iconModel;
- (void).cxx_destruct;
- (void)iconDidClick:(id)arg1;
- (void)updateFrame;
- (void)asynRequestIconImageWithIconLink:(id)arg1;
- (void)configIconViewWithIconModel:(id)arg1;
- (_Bool)isImageIcon;
- (_Bool)isEmpty;
- (void)layoutSubviews;
- (void)setFrame:(struct CGRect)arg1;
- (id)init;

@end

