//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class DTTeamJobTitle, NSString, UIImage;

@interface DTIdentifier : NSObject
{
    _Bool _isActived;
    _Bool _enableEmailMode;
    _Bool _isAdmin;
    NSString *_primaryKey;
    long long _uid;
    NSString *_mobile;
    NSString *_staffId;
    long long _orgId;
    NSString *_orgName;
    NSString *_name;
    UIImage *_avatar;
    NSString *_mediaId;
    unsigned long long _source;
    NSString *_email;
    unsigned long long _numberType;
    NSString *_remark;
    DTTeamJobTitle *_jobTitle;
}

+ (id)identifierWithMobile:(id)arg1 uid:(long long)arg2 staffId:(id)arg3 orgId:(long long)arg4 name:(id)arg5 mediaId:(id)arg6 avatar:(id)arg7;
@property(retain, nonatomic) DTTeamJobTitle *jobTitle; // @synthesize jobTitle=_jobTitle;
@property(nonatomic) _Bool isAdmin; // @synthesize isAdmin=_isAdmin;
@property(copy, nonatomic) NSString *remark; // @synthesize remark=_remark;
@property(nonatomic) _Bool enableEmailMode; // @synthesize enableEmailMode=_enableEmailMode;
@property(nonatomic) _Bool isActived; // @synthesize isActived=_isActived;
@property(nonatomic) unsigned long long numberType; // @synthesize numberType=_numberType;
@property(copy, nonatomic) NSString *email; // @synthesize email=_email;
@property(nonatomic) unsigned long long source; // @synthesize source=_source;
@property(copy, nonatomic) NSString *mediaId; // @synthesize mediaId=_mediaId;
@property(retain, nonatomic) UIImage *avatar; // @synthesize avatar=_avatar;
@property(copy, nonatomic) NSString *name; // @synthesize name=_name;
@property(copy, nonatomic) NSString *orgName; // @synthesize orgName=_orgName;
@property(nonatomic) long long orgId; // @synthesize orgId=_orgId;
@property(copy, nonatomic) NSString *staffId; // @synthesize staffId=_staffId;
@property(copy, nonatomic) NSString *mobile; // @synthesize mobile=_mobile;
@property(nonatomic) long long uid; // @synthesize uid=_uid;
@property(copy, nonatomic) NSString *primaryKey; // @synthesize primaryKey=_primaryKey;
- (void).cxx_destruct;
- (_Bool)mobile:(id)arg1 isSameWithAnother:(id)arg2 exact:(_Bool)arg3;
- (unsigned long long)priority;
- (_Bool)isEqualToIdentifier:(id)arg1 exactMobile:(_Bool)arg2;
- (_Bool)isEqualToIdentifier:(id)arg1;
- (id)staffIdAndOrgId;

@end

