//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface DTIMModuleConfig : NSObject
{
}

+ (_Bool)isIMOTOUnreadMessage2DINGEnabled;
+ (void)setDidShownGuideTipsForUnreadMessage2Ding:(_Bool)arg1;
+ (_Bool)didShownGuideTipsForUnreadMessage2Ding;
+ (void)setDidShowRemindLaterSystemMessage:(_Bool)arg1;
+ (_Bool)didShowRemindLaterSystemMessage;
+ (_Bool)isEnableChangePinAsSchedule;
+ (_Bool)isEnabledExportVideoAs480P;
+ (_Bool)isEnabledDebugTool;
+ (_Bool)isEnabledPreleaseEnv;
+ (_Bool)isEnabledDebug;

@end

