//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "DTIMAPRequest.h"

@class DTIMAPFolder, NSArray, NSIndexSet, NSString;

@interface DTIMAPFetchMessagesRequest : DTIMAPRequest
{
    _Bool _fetchByUID;
    _Bool _handleFault;
    int _requestKind;
    unsigned int _fromUID;
    unsigned int _toUID;
    NSString *_path;
    DTIMAPFolder *_folder;
    NSIndexSet *_indexSet;
    NSArray *_messages;
    long long _handleLevel;
}

@property(nonatomic) long long handleLevel; // @synthesize handleLevel=_handleLevel;
@property(readonly, nonatomic) NSArray *messages; // @synthesize messages=_messages;
@property(nonatomic) _Bool handleFault; // @synthesize handleFault=_handleFault;
@property(retain, nonatomic) NSIndexSet *indexSet; // @synthesize indexSet=_indexSet;
@property(retain, nonatomic) DTIMAPFolder *folder; // @synthesize folder=_folder;
@property(nonatomic) unsigned int toUID; // @synthesize toUID=_toUID;
@property(nonatomic) unsigned int fromUID; // @synthesize fromUID=_fromUID;
@property(copy, nonatomic) NSString *path; // @synthesize path=_path;
@property(nonatomic) int requestKind; // @synthesize requestKind=_requestKind;
@property(nonatomic) _Bool fetchByUID; // @synthesize fetchByUID=_fetchByUID;
- (void).cxx_destruct;
- (void)mainRequest;
- (id)init;

@end

