//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSOperation.h>

@class DTIMAPSession, NSError, NSString;
@protocol DTIMAPRequestDelegate;

@interface DTIMAPRequest : NSOperation
{
    DTIMAPSession *_session;
    _Bool _started;
    id <DTIMAPRequestDelegate> _delegate;
    NSError *_error;
    long long _tag;
    NSString *_requestName;
    NSString *_selectPath;
    CDUnknownBlockType _successBlock;
    CDUnknownBlockType _failureBlock;
}

@property(nonatomic) _Bool started; // @synthesize started=_started;
@property(copy, nonatomic) CDUnknownBlockType failureBlock; // @synthesize failureBlock=_failureBlock;
@property(copy, nonatomic) CDUnknownBlockType successBlock; // @synthesize successBlock=_successBlock;
@property(copy, nonatomic) NSString *selectPath; // @synthesize selectPath=_selectPath;
@property(copy, nonatomic) NSString *requestName; // @synthesize requestName=_requestName;
@property(nonatomic) long long tag; // @synthesize tag=_tag;
@property(retain, nonatomic) NSError *error; // @synthesize error=_error;
@property(nonatomic) __weak id <DTIMAPRequestDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) DTIMAPSession *session; // @synthesize session=_session;
- (void).cxx_destruct;
- (void)finished;
- (void)mainFinished;
- (void)cancel;
- (void)startRequest;
- (void)mainRequest;
- (void)main;

@end

