//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@interface DTImagePickerSelectView : UIView
{
    _Bool _horizontalLocked;
    _Bool _verticalLocked;
    CDUnknownBlockType _viewDidDrag;
    UIView *_rbView;
    struct CGRect _scope;
}

@property(retain, nonatomic) UIView *rbView; // @synthesize rbView=_rbView;
@property(copy, nonatomic) CDUnknownBlockType viewDidDrag; // @synthesize viewDidDrag=_viewDidDrag;
@property(nonatomic) struct CGRect scope; // @synthesize scope=_scope;
@property(nonatomic) _Bool verticalLocked; // @synthesize verticalLocked=_verticalLocked;
@property(nonatomic) _Bool horizontalLocked; // @synthesize horizontalLocked=_horizontalLocked;
- (void).cxx_destruct;
- (void)touchesMoved:(id)arg1 withEvent:(id)arg2;
- (id)hitTest:(struct CGPoint)arg1 withEvent:(id)arg2;
- (id)createView;
- (void)layoutSubviews;
- (void)loadComponent;
- (id)initWithFrame:(struct CGRect)arg1;

@end

