//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface DTInactiveConversationCleanUpActor : NSObject
{
}

+ (void)startDelayAction;
+ (void)execute;
+ (_Bool)cleanUpCheckingAvailable;
+ (void)updateCleanUpCheckingTime:(double)arg1;
+ (double)lastCleanUpCheckingTime;
+ (id)groupConversationIds:(id)arg1;
+ (id)mergeIdsWithPartialA:(id)arg1 partialB:(id)arg2;
+ (long long)inactiveConversationExpirationTime:(long long)arg1;
+ (void)reportDidFinishCleanupInactiveConversations:(id)arg1;
+ (void)cleanUp:(id)arg1;

@end

