//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SClient.h"

@interface DTIotTerminalKeyIService : SClient
{
}

+ (id)_appname__;
+ (id)_serviceKey__;
- (void)getPskV2:(id)arg1 corpId:(id)arg2 umidToken:(id)arg3 wifiMac:(id)arg4 callback:(id)arg5;
- (void)getDynamicNetPsk:(id)arg1;
- (void)getPsk:(id)arg1 umidToken:(id)arg2 wifiMac:(id)arg3 callback:(id)arg4;

@end

