//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSString;

@interface DTJoinTeamInvite : NSObject
{
    NSString *_orgName;
    long long _orgId;
    unsigned long long _status;
    long long _uid;
    NSString *_userNick;
    NSString *_mediaId;
}

@property(copy, nonatomic) NSString *mediaId; // @synthesize mediaId=_mediaId;
@property(copy, nonatomic) NSString *userNick; // @synthesize userNick=_userNick;
@property(nonatomic) long long uid; // @synthesize uid=_uid;
@property(nonatomic) unsigned long long status; // @synthesize status=_status;
@property(nonatomic) long long orgId; // @synthesize orgId=_orgId;
@property(copy, nonatomic) NSString *orgName; // @synthesize orgName=_orgName;
- (void).cxx_destruct;
- (id)toIDLModel;
- (id)initWithIDLModel:(id)arg1;

@end

