//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "LAPluginBase.h"

@interface DTLAPBizUtils : LAPluginBase
{
}

+ (id)pluginExactName;
- (void)selectEmoji:(id)arg1 to:(id)arg2;
- (void)__exported__selectEmoji:(id)arg1 to:(id)arg2;
- (_Bool)requestParameterValid:(id)arg1 response:(id)arg2;
- (void)getLocaleAndNationByCorpId:(id)arg1 to:(id)arg2;
- (void)__exported__getLocaleAndNationByCorpId:(id)arg1 to:(id)arg2;
- (void)stickPage:(id)arg1 to:(id)arg2;
- (void)__exported__stickPage:(id)arg1 to:(id)arg2;
- (void)timestamp:(id)arg1 to:(id)arg2;
- (void)__exported__timestamp:(id)arg1 to:(id)arg2;

@end

