//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSString, UIView;
@protocol DTLoadMoreDelegate;

@interface DTLoadMoreController : NSObject
{
    _Bool _noMore;
    _Bool _isLoading;
    long long _nextCursor;
    NSString *_nextCursorString;
    unsigned long long _pageSize;
    double _preloadHeight;
    UIView *_loadingView;
    unsigned long long _direct;
    id <DTLoadMoreDelegate> _delegate;
}

@property(nonatomic) _Bool isLoading; // @synthesize isLoading=_isLoading;
@property(nonatomic) __weak id <DTLoadMoreDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) unsigned long long direct; // @synthesize direct=_direct;
@property(retain, nonatomic) UIView *loadingView; // @synthesize loadingView=_loadingView;
@property(nonatomic) double preloadHeight; // @synthesize preloadHeight=_preloadHeight;
@property(nonatomic) unsigned long long pageSize; // @synthesize pageSize=_pageSize;
@property(copy, nonatomic) NSString *nextCursorString; // @synthesize nextCursorString=_nextCursorString;
@property(nonatomic) long long nextCursor; // @synthesize nextCursor=_nextCursor;
@property(nonatomic) _Bool noMore; // @synthesize noMore=_noMore;
- (void).cxx_destruct;
- (void)reset;
- (void)setNextCursorString:(id)arg1 hasMore:(_Bool)arg2;
- (void)setNextCursor:(long long)arg1 hasMore:(_Bool)arg2;
- (void)neverLoadMore;
- (void)loadMoreControllerDidEndLoading;
- (void)runWhenScrollViewDidScroll:(id)arg1;
- (void)runWhenScrollViewDidScrollWithFrame:(struct CGRect)arg1 contentSize:(struct CGSize)arg2 contentOffset:(struct CGPoint)arg3 contentInset:(struct UIEdgeInsets)arg4;

@end

