//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "DTTableViewController.h"

@class DTAgentSettingsModel, DTBaseCellItem, DTCellItem, DTTableViewDataSource, DTTextFieldCellItem, NSDictionary, NSNumber, NSString;

@interface DTMailConfigtableviewController : DTTableViewController
{
    _Bool _fromLogin;
    _Bool _jumpOrgEmailManage;
    _Bool _isHiddenAdvanedSetting;
    _Bool _notValidDomain;
    DTAgentSettingsModel *_models;
    NSNumber *_orgID;
    NSDictionary *_queryParams;
    NSString *_username;
    NSString *_password;
    CDUnknownBlockType _completion;
    long long _editType;
    NSString *_domain;
    DTBaseCellItem *_recvAccountCell;
    DTCellItem *_recvPasswordCell;
    DTCellItem *_imapServerConfigCell;
    DTCellItem *_smtpServerConfigCell;
    DTTextFieldCellItem *_imapPortCell;
    DTTextFieldCellItem *_smtpPortCell;
    DTCellItem *_imapSSLCell;
    DTCellItem *_smtpSSLCell;
    DTTableViewDataSource *_fullDataSource;
}

@property(nonatomic) _Bool notValidDomain; // @synthesize notValidDomain=_notValidDomain;
@property(retain, nonatomic) DTTableViewDataSource *fullDataSource; // @synthesize fullDataSource=_fullDataSource;
@property(nonatomic) _Bool isHiddenAdvanedSetting; // @synthesize isHiddenAdvanedSetting=_isHiddenAdvanedSetting;
@property(retain, nonatomic) DTCellItem *smtpSSLCell; // @synthesize smtpSSLCell=_smtpSSLCell;
@property(retain, nonatomic) DTCellItem *imapSSLCell; // @synthesize imapSSLCell=_imapSSLCell;
@property(retain, nonatomic) DTTextFieldCellItem *smtpPortCell; // @synthesize smtpPortCell=_smtpPortCell;
@property(retain, nonatomic) DTTextFieldCellItem *imapPortCell; // @synthesize imapPortCell=_imapPortCell;
@property(retain, nonatomic) DTCellItem *smtpServerConfigCell; // @synthesize smtpServerConfigCell=_smtpServerConfigCell;
@property(retain, nonatomic) DTCellItem *imapServerConfigCell; // @synthesize imapServerConfigCell=_imapServerConfigCell;
@property(retain, nonatomic) DTCellItem *recvPasswordCell; // @synthesize recvPasswordCell=_recvPasswordCell;
@property(retain, nonatomic) DTBaseCellItem *recvAccountCell; // @synthesize recvAccountCell=_recvAccountCell;
@property(copy, nonatomic) NSString *domain; // @synthesize domain=_domain;
@property(nonatomic) long long editType; // @synthesize editType=_editType;
@property(copy, nonatomic) CDUnknownBlockType completion; // @synthesize completion=_completion;
@property(nonatomic) _Bool jumpOrgEmailManage; // @synthesize jumpOrgEmailManage=_jumpOrgEmailManage;
@property(nonatomic) _Bool fromLogin; // @synthesize fromLogin=_fromLogin;
@property(copy, nonatomic) NSString *password; // @synthesize password=_password;
@property(copy, nonatomic) NSString *username; // @synthesize username=_username;
@property(retain, nonatomic) NSDictionary *queryParams; // @synthesize queryParams=_queryParams;
@property(retain, nonatomic) NSNumber *orgID; // @synthesize orgID=_orgID;
@property(retain, nonatomic) DTAgentSettingsModel *models; // @synthesize models=_models;
- (void).cxx_destruct;
- (void)clickShowHideAdvancedSetting;
- (_Bool)checkInput;
- (void)setupDataSource:(id)arg1;
- (void)setupConfigIfNeeded:(id)arg1;
- (void)setupDomain:(id)arg1;
- (id)constructSettingModel;
- (void)updateConfigWithRole:(_Bool)arg1 account:(id)arg2;
- (void)updateConfigWithAccount:(id)arg1;
- (void)showAlertView:(id)arg1 password:(id)arg2 errorCode:(long long)arg3;
- (void)reloginFailureUserTrackWithError:(id)arg1 arg:(id)arg2 code:(long long)arg3;
- (void)reloginSuccessUserTrackWithArg:(id)arg1 code:(long long)arg2;
- (void)loginFailureUserTrackWithError:(id)arg1 arg:(id)arg2;
- (void)loginSuccessUserTrackWithArg:(id)arg1;
- (void)retryCheckUserConfigWithEmail:(id)arg1 withPwd:(id)arg2 withProtocol:(long long)arg3 code:(long long)arg4 withSetting:(id)arg5;
- (_Bool)shouldHandleUserConfigError:(id)arg1 userNameIMAP:(id)arg2 password:(id)arg3 withProtocol:(long long)arg4 settings:(id)arg5;
- (void)retryLoginAndBindImapMail:(id)arg1 password:(id)arg2 code:(long long)arg3 settings:(id)arg4;
- (_Bool)shouldHandleLoginError:(id)arg1 userNameIMAP:(id)arg2 password:(id)arg3 settings:(id)arg4;
- (void)rightBarBtnClicked;
- (id)calcDataSource:(_Bool)arg1;
- (void)tidyDataSource;
- (id)loadFourSection;
- (id)loadThirdSection;
- (id)loadSecondSection;
- (id)loadFirstSection;
- (id)sslCellItem:(long long)arg1;
- (id)portCellItem:(_Bool)arg1 agentType:(long long)arg2;
- (id)passwordCellItem:(_Bool)arg1;
- (id)mailAccountCellItem:(_Bool)arg1;
- (void)getCmailSettings;
- (void)setRightBarItem;
- (void)dealloc;
- (void)viewDidLoad;
- (id)initWithEditType:(long long)arg1;

@end

