//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class DTMessageControllerDataSource, NSMutableArray;

@interface DTMessagePerformBatchManager : NSObject
{
    int _lock;
    _Bool _performBatchIsDoing;
    DTMessageControllerDataSource *_dataSource;
    CDUnknownBlockType _insertCompleteBlock;
    NSMutableArray *_addQueue;
    NSMutableArray *_deleteQueue;
    NSMutableArray *_updateQueue;
}

@property(nonatomic) _Bool performBatchIsDoing; // @synthesize performBatchIsDoing=_performBatchIsDoing;
@property(retain, nonatomic) NSMutableArray *updateQueue; // @synthesize updateQueue=_updateQueue;
@property(retain, nonatomic) NSMutableArray *deleteQueue; // @synthesize deleteQueue=_deleteQueue;
@property(retain, nonatomic) NSMutableArray *addQueue; // @synthesize addQueue=_addQueue;
@property(copy, nonatomic) CDUnknownBlockType insertCompleteBlock; // @synthesize insertCompleteBlock=_insertCompleteBlock;
@property(nonatomic) __weak DTMessageControllerDataSource *dataSource; // @synthesize dataSource=_dataSource;
- (void).cxx_destruct;
- (void)deQueue;
- (void)enQueue:(id)arg1;
- (id)operationMessageInQueue:(id)arg1 mid:(unsigned long long)arg2;
- (void)updatePerformBatchWithOperations:(id)arg1;
- (void)deletePerformBatchWithOperations:(id)arg1;
- (void)addPerformBatchWithOperations:(id)arg1;
- (unsigned long long)insertIndexOfMessage:(id)arg1 messages:(id)arg2;
- (_Bool)receiveMessagesNeedToScrollBottom;
- (id)initWithDataSource:(id)arg1;

@end

