//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "Marshal.h"

@class NSNumber, NSString;

@interface DTMeetingRoomDevInfoModel : Marshal
{
    NSString *_sessionId;
    NSNumber *_devUid;
    NSString *_devIP;
}

@property(copy, nonatomic) NSString *devIP; // @synthesize devIP=_devIP;
@property(retain, nonatomic) NSNumber *devUid; // @synthesize devUid=_devUid;
@property(copy, nonatomic) NSString *sessionId; // @synthesize sessionId=_sessionId;
- (void).cxx_destruct;
- (id)filedsMeta__;
- (id)init;

@end

