//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSArray, NSMutableArray, POPBasicAnimation, UIImageView, UIScrollView;

@interface DTMenuView : UIView
{
    _Bool _isAnimating;
    _Bool _isMenuShowing;
    NSArray *_dataSource;
    UIScrollView *_container;
    NSMutableArray *_rows;
    UIView *_parentView;
    UIImageView *_header;
    UIImageView *_bg;
    NSMutableArray *_showAnimationList;
    NSMutableArray *_dismissAnimationList;
    POPBasicAnimation *_showMenuAlphaAnimation;
    POPBasicAnimation *_dismissMenuAlphaAnimation;
    CDUnknownBlockType _dismissBlock;
    NSMutableArray *_accessibilityElements;
}

+ (id)MenuViewWithView:(id)arg1 DataSource:(id)arg2 dismissBlock:(CDUnknownBlockType)arg3;
+ (id)MenuViewWithView:(id)arg1 DataSource:(id)arg2;
@property(retain, nonatomic) NSMutableArray *accessibilityElements; // @synthesize accessibilityElements=_accessibilityElements;
@property(nonatomic) _Bool isMenuShowing; // @synthesize isMenuShowing=_isMenuShowing;
@property(copy, nonatomic) CDUnknownBlockType dismissBlock; // @synthesize dismissBlock=_dismissBlock;
@property(retain, nonatomic) POPBasicAnimation *dismissMenuAlphaAnimation; // @synthesize dismissMenuAlphaAnimation=_dismissMenuAlphaAnimation;
@property(retain, nonatomic) POPBasicAnimation *showMenuAlphaAnimation; // @synthesize showMenuAlphaAnimation=_showMenuAlphaAnimation;
@property(retain, nonatomic) NSMutableArray *dismissAnimationList; // @synthesize dismissAnimationList=_dismissAnimationList;
@property(retain, nonatomic) NSMutableArray *showAnimationList; // @synthesize showAnimationList=_showAnimationList;
@property(retain, nonatomic) UIImageView *bg; // @synthesize bg=_bg;
@property(nonatomic) _Bool isAnimating; // @synthesize isAnimating=_isAnimating;
@property(retain, nonatomic) UIImageView *header; // @synthesize header=_header;
@property(nonatomic) __weak UIView *parentView; // @synthesize parentView=_parentView;
@property(retain, nonatomic) NSMutableArray *rows; // @synthesize rows=_rows;
@property(retain, nonatomic) UIScrollView *container; // @synthesize container=_container;
@property(copy, nonatomic) NSArray *dataSource; // @synthesize dataSource=_dataSource;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (_Bool)isShowing;
- (void)dismiss;
- (void)dismissWithTarget:(id)arg1 sel:(SEL)arg2;
- (void)show;
- (void)addAnimationForCell:(id)arg1 index:(int)arg2;
- (void)initMenuView;
- (id)initMenuViewWithView:(id)arg1 DataSource:(id)arg2;
- (id)initMenuViewWithView:(id)arg1 DataSource:(id)arg2 dismissBlock:(CDUnknownBlockType)arg3;

@end

