//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIButton.h>

@class DTMessagePopupActionItem, DTWebAnimatedImageView;

@interface DTMessagePopupActionButton : UIButton
{
    DTMessagePopupActionItem *_actionItem;
    DTWebAnimatedImageView *_iconFontImageView;
}

@property(retain, nonatomic) DTWebAnimatedImageView *iconFontImageView; // @synthesize iconFontImageView=_iconFontImageView;
@property(retain, nonatomic) DTMessagePopupActionItem *actionItem; // @synthesize actionItem=_actionItem;
- (void).cxx_destruct;
- (void)setHighlighted:(_Bool)arg1;
- (struct CGRect)titleRectForContentRect:(struct CGRect)arg1;
- (struct CGRect)backgroundRectForBounds:(struct CGRect)arg1;
- (struct CGRect)imageRectForContentRect:(struct CGRect)arg1;

@end

