//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class DTMessageBottomStatusCountDownModel, NSString, UIColor;

@interface DTMessageBottomStatusViewItem : NSObject
{
    _Bool _needShowUnreadAlert;
    _Bool _isSelf;
    _Bool _needShowStatus;
    _Bool _needShowDingConfirm;
    _Bool _isDing;
    _Bool _isOTO;
    _Bool _isSpaceFile;
    _Bool _messageTypeQuiet;
    _Bool _isLeftButtonEnable;
    NSString *_unreadAlertTitle;
    double _unreadAlertTop;
    double _unreadAlertRightMargin;
    unsigned long long _unreadAlertViewTag;
    long long _unreadCount;
    long long _totalCount;
    NSString *_atStatusString;
    UIColor *_atStatusStringColor;
    unsigned long long _sendStatus;
    DTMessageBottomStatusCountDownModel *_countDownModel;
    NSString *_leftButtonTitle;
    UIColor *_leftButtonColor;
}

+ (_Bool)needShowBottomStatusWithMessage:(id)arg1 conversation:(id)arg2;
+ (void)buildWithMessage:(id)arg1 conversation:(id)arg2 bizDing:(id)arg3 syncResult:(CDUnknownBlockType)arg4 asyncResultIfNeeded:(CDUnknownBlockType)arg5;
+ (void)configMessageUnreadStatusAlertNeedShowWithMessage:(id)arg1 conversation:(id)arg2 forItem:(id)arg3;
@property(retain, nonatomic) UIColor *leftButtonColor; // @synthesize leftButtonColor=_leftButtonColor;
@property(copy, nonatomic) NSString *leftButtonTitle; // @synthesize leftButtonTitle=_leftButtonTitle;
@property(nonatomic) _Bool isLeftButtonEnable; // @synthesize isLeftButtonEnable=_isLeftButtonEnable;
@property(retain, nonatomic) DTMessageBottomStatusCountDownModel *countDownModel; // @synthesize countDownModel=_countDownModel;
@property(nonatomic) unsigned long long sendStatus; // @synthesize sendStatus=_sendStatus;
@property(retain, nonatomic) UIColor *atStatusStringColor; // @synthesize atStatusStringColor=_atStatusStringColor;
@property(copy) NSString *atStatusString; // @synthesize atStatusString=_atStatusString;
@property(nonatomic) _Bool messageTypeQuiet; // @synthesize messageTypeQuiet=_messageTypeQuiet;
@property(nonatomic) _Bool isSpaceFile; // @synthesize isSpaceFile=_isSpaceFile;
@property(nonatomic) _Bool isOTO; // @synthesize isOTO=_isOTO;
@property(nonatomic) _Bool isDing; // @synthesize isDing=_isDing;
@property(nonatomic) _Bool needShowDingConfirm; // @synthesize needShowDingConfirm=_needShowDingConfirm;
@property(nonatomic) long long totalCount; // @synthesize totalCount=_totalCount;
@property(nonatomic) long long unreadCount; // @synthesize unreadCount=_unreadCount;
@property(nonatomic) _Bool needShowStatus; // @synthesize needShowStatus=_needShowStatus;
@property(nonatomic) _Bool isSelf; // @synthesize isSelf=_isSelf;
@property(nonatomic) unsigned long long unreadAlertViewTag; // @synthesize unreadAlertViewTag=_unreadAlertViewTag;
@property(nonatomic) double unreadAlertRightMargin; // @synthesize unreadAlertRightMargin=_unreadAlertRightMargin;
@property(nonatomic) double unreadAlertTop; // @synthesize unreadAlertTop=_unreadAlertTop;
@property(copy, nonatomic) NSString *unreadAlertTitle; // @synthesize unreadAlertTitle=_unreadAlertTitle;
@property(nonatomic) _Bool needShowUnreadAlert; // @synthesize needShowUnreadAlert=_needShowUnreadAlert;
- (void).cxx_destruct;

@end

