//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "DTBaseCellItem.h"

@class UIColor, UIFont;

@interface DTMergeMessageTimeLineItem : DTBaseCellItem
{
    long long _startTime;
    long long _endTime;
    UIFont *_timeFont;
    UIColor *_lineColor;
}

+ (double)heightWithItem:(id)arg1;
@property(retain, nonatomic) UIColor *lineColor; // @synthesize lineColor=_lineColor;
@property(retain, nonatomic) UIFont *timeFont; // @synthesize timeFont=_timeFont;
@property(nonatomic) long long endTime; // @synthesize endTime=_endTime;
@property(nonatomic) long long startTime; // @synthesize startTime=_startTime;
- (void).cxx_destruct;
- (double)heightForCell;
- (id)reuseIdentifier;
- (id)cellForItem;
- (id)timeString;

@end

