//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "DTBubbleAudioItem.h"

@class DTBizMessage;

@interface DTMessageBubbleAudioItem : DTBubbleAudioItem
{
    _Bool _isEncrypt;
    DTBizMessage *_message;
}

+ (id)buildWithMessage:(id)arg1 playStatus:(long long)arg2;
@property(nonatomic) _Bool isEncrypt; // @synthesize isEncrypt=_isEncrypt;
@property(nonatomic) __weak DTBizMessage *message; // @synthesize message=_message;
- (void).cxx_destruct;

@end

