//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "DTBaseCellItem.h"

@class DTAvatarModel, DTBaseCellViewsHorizontalMargins, DTBaseCellViewsMargins, DTBaseUserCellNameModel, DTBizConversation, DTBizMessage, DTMediaAuthInfo, DTMergeMessageCell;

@interface DTMergeMessageItem : DTBaseCellItem
{
    _Bool _isContinuous;
    DTBaseUserCellNameModel *_nameModel;
    DTAvatarModel *_avatarModel;
    long long _avatarSize;
    DTBaseCellViewsHorizontalMargins *_avatarMargin;
    double _nameHeight;
    DTBaseCellViewsMargins *_nameMargin;
    DTBizMessage *_message;
    DTBizConversation *_conversation;
    DTMediaAuthInfo *_authInfo;
    unsigned long long _layoutStyle;
    CDUnknownBlockType _bubbleTap;
    CDUnknownBlockType _didTapOnAvatar;
    CDUnknownBlockType _tapTextLink;
    CDUnknownBlockType _tapTextPhone;
    CDUnknownBlockType _reactionLike;
    CDUnknownBlockType _reactionComment;
    DTMergeMessageCell *_itemCell;
    struct CGSize _maxNameSize;
    struct UIEdgeInsets _contentInsets;
}

+ (double)heightWithItem:(id)arg1;
+ (double)bubbleMaxminWidth:(id)arg1;
+ (double)avatarSize:(unsigned long long)arg1;
+ (id)buildWithMessage:(id)arg1;
@property(nonatomic) __weak DTMergeMessageCell *itemCell; // @synthesize itemCell=_itemCell;
@property(copy, nonatomic) CDUnknownBlockType reactionComment; // @synthesize reactionComment=_reactionComment;
@property(copy, nonatomic) CDUnknownBlockType reactionLike; // @synthesize reactionLike=_reactionLike;
@property(copy, nonatomic) CDUnknownBlockType tapTextPhone; // @synthesize tapTextPhone=_tapTextPhone;
@property(copy, nonatomic) CDUnknownBlockType tapTextLink; // @synthesize tapTextLink=_tapTextLink;
@property(copy, nonatomic) CDUnknownBlockType didTapOnAvatar; // @synthesize didTapOnAvatar=_didTapOnAvatar;
@property(copy, nonatomic) CDUnknownBlockType bubbleTap; // @synthesize bubbleTap=_bubbleTap;
@property(nonatomic) unsigned long long layoutStyle; // @synthesize layoutStyle=_layoutStyle;
@property(nonatomic) _Bool isContinuous; // @synthesize isContinuous=_isContinuous;
@property(retain, nonatomic) DTMediaAuthInfo *authInfo; // @synthesize authInfo=_authInfo;
@property(retain, nonatomic) DTBizConversation *conversation; // @synthesize conversation=_conversation;
@property(retain, nonatomic) DTBizMessage *message; // @synthesize message=_message;
@property(retain, nonatomic) DTBaseCellViewsMargins *nameMargin; // @synthesize nameMargin=_nameMargin;
@property(nonatomic) double nameHeight; // @synthesize nameHeight=_nameHeight;
@property(retain, nonatomic) DTBaseCellViewsHorizontalMargins *avatarMargin; // @synthesize avatarMargin=_avatarMargin;
@property(nonatomic) long long avatarSize; // @synthesize avatarSize=_avatarSize;
@property(retain, nonatomic) DTAvatarModel *avatarModel; // @synthesize avatarModel=_avatarModel;
@property(nonatomic) struct UIEdgeInsets contentInsets; // @synthesize contentInsets=_contentInsets;
@property(nonatomic) struct CGSize maxNameSize; // @synthesize maxNameSize=_maxNameSize;
- (void).cxx_destruct;
- (double)heightForCell;
- (id)reuseIdentifier;
- (id)cellForItem;
@property(retain, nonatomic) DTBaseUserCellNameModel *nameModel; // @synthesize nameModel=_nameModel;
- (id)init;

@end

