//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "DTMessageBubbleAttachmentProtocol-Protocol.h"

@class DTBizAttachmentLink, NSString;
@protocol DTMessageBubbleAttachmentFeedCardViewProtocol, DTMessageCollectionViewCellAttachmentProtocol;

@interface DTMessageBubbleAttachmentFeedCardView : UIView <DTMessageBubbleAttachmentProtocol>
{
    DTBizAttachmentLink *_currentLink;
    id <DTMessageBubbleAttachmentFeedCardViewProtocol> _delegate;
    UIView *_headerLinkView;
    UIView *_plusLinksView;
    UIView *_cornerImageView;
    UIView *_longPressMaskView;
}

+ (struct CGSize)calculateSizeWithItem:(id)arg1 constraintsSize:(struct CGSize)arg2;
@property(retain, nonatomic) UIView *longPressMaskView; // @synthesize longPressMaskView=_longPressMaskView;
@property(retain, nonatomic) UIView *cornerImageView; // @synthesize cornerImageView=_cornerImageView;
@property(retain, nonatomic) UIView *plusLinksView; // @synthesize plusLinksView=_plusLinksView;
@property(retain, nonatomic) UIView *headerLinkView; // @synthesize headerLinkView=_headerLinkView;
@property(nonatomic) __weak id <DTMessageBubbleAttachmentFeedCardViewProtocol> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)favorite;
- (void)transmit;
- (void)willHideEditMenu:(id)arg1;
- (void)showMenuForView:(id)arg1 forLink:(id)arg2;
- (id)generateFeedCardRecognizeViewWithFrame:(struct CGRect)arg1 link:(id)arg2;
- (void)configWithItem:(id)arg1 complete:(CDUnknownBlockType)arg2;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(nonatomic) __weak id <DTMessageCollectionViewCellAttachmentProtocol> attachmentDelegate;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

