//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface DTMicroAppErrorHelper : NSObject
{
}

+ (void)popMicroAppOpenFailedWithoutPhoneNumber:(id)arg1 content:(id)arg2;
+ (void)popMicroAppOpenFailedWithoutPhoneNumber;
+ (void)popMicroAppOpenFailedWithPhoneNumber:(id)arg1 title:(id)arg2 content:(id)arg3;
+ (void)popMicroAppOpenFailedWithPhoneNumber:(id)arg1;
+ (void)showMicroAppOpenFailedWithAppId:(id)arg1 holderView:(id)arg2;

@end

