//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class DTMobileAdsUITreeNode;

@interface DTMobileAdsUITree : NSObject
{
    DTMobileAdsUITreeNode *_rootNode;
}

+ (id)buildTreeNodeWithBody:(id)arg1 parentNode:(id)arg2;
+ (id)mobileAdsUITreeWithPath:(id)arg1;
@property(readonly, nonatomic) DTMobileAdsUITreeNode *rootNode; // @synthesize rootNode=_rootNode;
- (void).cxx_destruct;
- (id)findAllExpiredNodes:(CDUnknownBlockType)arg1;
- (_Bool)hasMobileAdsBaseOnNode:(id)arg1 recursive:(_Bool)arg2;
- (_Bool)hasMobileAdsWithWidgetId:(id)arg1 recursive:(_Bool)arg2;
- (id)findAllLinkedNodesWithAdId:(id)arg1;
- (id)findAllLinkedNodesWithWidgetId:(id)arg1;
- (id)findAllLinkedNodesWithNode:(id)arg1;
- (id)findNodeWithAdId:(id)arg1;
- (id)findNodeWithWidgetId:(id)arg1;
- (id)findNodeBaseOn:(id)arg1 matchingBlock:(CDUnknownBlockType)arg2;
- (id)initWithRootNode:(id)arg1;

@end

