//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "DTViewController.h"

@class NSString, UITextField, UIView;

@interface DTNewDentryFolderViewController : DTViewController
{
    CDUnknownBlockType _completion;
    CDUnknownBlockType _cancel;
    NSString *_topPrompt;
    UITextField *_nameField;
    UIView *_fieldBackgroundView;
}

@property(retain, nonatomic) UIView *fieldBackgroundView; // @synthesize fieldBackgroundView=_fieldBackgroundView;
@property(retain, nonatomic) UITextField *nameField; // @synthesize nameField=_nameField;
@property(retain, nonatomic) NSString *topPrompt; // @synthesize topPrompt=_topPrompt;
@property(copy, nonatomic) CDUnknownBlockType cancel; // @synthesize cancel=_cancel;
@property(copy, nonatomic) CDUnknownBlockType completion; // @synthesize completion=_completion;
- (void).cxx_destruct;
- (void)doneClicked:(id)arg1;
- (void)textFieldTextChanged:(id)arg1;
- (void)dentryPopBack:(id)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)createFolderFailed:(id)arg1;
- (void)addNotification;
- (void)viewDidLoad;
- (void)dealloc;

@end

