//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "Marshal.h"

@class NSArray, NSNumber, NSString;

@interface DTOANotifyPushModel : Marshal
{
    _Bool _alwaysShow;
    NSString *_notifyId;
    NSString *_icon;
    NSString *_title;
    NSString *_content;
    NSString *_url;
    NSNumber *_audio;
    NSString *_source;
    NSNumber *_planId;
    NSString *_corpId;
    NSNumber *_interval;
    NSArray *_actions;
}

@property(copy, nonatomic) NSArray *actions; // @synthesize actions=_actions;
@property(retain, nonatomic) NSNumber *interval; // @synthesize interval=_interval;
@property(nonatomic) _Bool alwaysShow; // @synthesize alwaysShow=_alwaysShow;
@property(copy, nonatomic) NSString *corpId; // @synthesize corpId=_corpId;
@property(retain, nonatomic) NSNumber *planId; // @synthesize planId=_planId;
@property(copy, nonatomic) NSString *source; // @synthesize source=_source;
@property(retain, nonatomic) NSNumber *audio; // @synthesize audio=_audio;
@property(copy, nonatomic) NSString *url; // @synthesize url=_url;
@property(copy, nonatomic) NSString *content; // @synthesize content=_content;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(copy, nonatomic) NSString *icon; // @synthesize icon=_icon;
@property(copy, nonatomic) NSString *notifyId; // @synthesize notifyId=_notifyId;
- (void).cxx_destruct;
- (id)filedsMeta__;
- (id)init;

@end

