//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSString;

@interface DTOAPopViewItem : NSObject
{
    NSString *_imageString;
    NSString *_titleString;
    NSString *_contentString;
}

@property(copy, nonatomic) NSString *contentString; // @synthesize contentString=_contentString;
@property(copy, nonatomic) NSString *titleString; // @synthesize titleString=_titleString;
@property(copy, nonatomic) NSString *imageString; // @synthesize imageString=_imageString;
- (void).cxx_destruct;

@end

