//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "DTOACalendarPikcerComponentProtocol-Protocol.h"
#import "FSCalendarDataSource-Protocol.h"
#import "FSCalendarDelegate-Protocol.h"
#import "FSCalendarDelegateAppearance-Protocol.h"

@class FSCalendar, NSArray, NSDate, NSDateFormatter, NSString;
@protocol DTOACalendarPikcerComponentDelegate;

@interface DTOACalendarView : UIView <DTOACalendarPikcerComponentProtocol, FSCalendarDataSource, FSCalendarDelegate, FSCalendarDelegateAppearance>
{
    NSString *_corpId;
    id <DTOACalendarPikcerComponentDelegate> _delegate;
    NSArray *_bizTypes;
    NSDate *_currentDate;
    FSCalendar *_calendarView;
    NSDateFormatter *_dateFormatter;
    NSArray *_monthArray;
}

@property(retain, nonatomic) NSArray *monthArray; // @synthesize monthArray=_monthArray;
@property(retain, nonatomic) NSDateFormatter *dateFormatter; // @synthesize dateFormatter=_dateFormatter;
@property(retain, nonatomic) FSCalendar *calendarView; // @synthesize calendarView=_calendarView;
@property(retain, nonatomic) NSDate *currentDate; // @synthesize currentDate=_currentDate;
@property(copy, nonatomic) NSArray *bizTypes; // @synthesize bizTypes=_bizTypes;
@property(nonatomic) __weak id <DTOACalendarPikcerComponentDelegate> delegate; // @synthesize delegate=_delegate;
@property(copy, nonatomic) NSString *corpId; // @synthesize corpId=_corpId;
- (void).cxx_destruct;
- (_Bool)currentMonth:(id)arg1 inCalendar:(id)arg2;
- (_Bool)monthStart:(id)arg1 inCalendar:(id)arg2;
- (id)hintForCalendarPikcerComponentDate:(id)arg1;
- (void)setCalendarPikcerComponentSelectedDate:(id)arg1;
- (void)callBackSelectUpdate:(_Bool)arg1;
- (id)calendar:(id)arg1 appearance:(id)arg2 subtitleSelectionColorForDate:(id)arg3;
- (id)calendar:(id)arg1 appearance:(id)arg2 subtitleDefaultColorForDate:(id)arg3;
- (id)calendar:(id)arg1 appearance:(id)arg2 titleSelectionColorForDate:(id)arg3;
- (id)calendar:(id)arg1 appearance:(id)arg2 titleDefaultColorForDate:(id)arg3;
- (id)calendar:(id)arg1 appearance:(id)arg2 fillSelectionColorForDate:(id)arg3;
- (id)calendar:(id)arg1 appearance:(id)arg2 fillDefaultColorForDate:(id)arg3;
- (id)calendar:(id)arg1 appearance:(id)arg2 eventSelectionColorsForDate:(id)arg3;
- (id)calendar:(id)arg1 appearance:(id)arg2 eventDefaultColorsForDate:(id)arg3;
- (id)calendar:(id)arg1 subtitleForDate:(id)arg2;
- (id)calendar:(id)arg1 titleForDate:(id)arg2;
- (long long)calendar:(id)arg1 numberOfEventsForDate:(id)arg2;
- (void)calendarCurrentPageDidChange:(id)arg1;
- (void)calendar:(id)arg1 didSelectDate:(id)arg2;
- (void)calendar:(id)arg1 boundingRectWillChange:(struct CGRect)arg2 animated:(_Bool)arg3;
- (void)layoutSubviews;
- (void)loadComponents;
- (id)initWithFrame:(struct CGRect)arg1 corpId:(id)arg2 bizTypes:(id)arg3 delegate:(id)arg4;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

