//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSMutableArray, NSMutableDictionary, NSMutableSet;
@protocol OS_dispatch_semaphore;

@interface DTObjectProgressManager : NSObject
{
    NSMutableSet *_finishedSet;
    NSMutableDictionary *_progressCaches;
    NSObject<OS_dispatch_semaphore> *_lock;
    NSMutableArray *_observerInfos;
    _Bool _observing;
}

+ (id)shareInstance;
- (void).cxx_destruct;
- (void)removeProgressObserver:(id)arg1;
- (void)addProgressObserver:(id)arg1;
- (void)callbackObserverInfosForKey:(id)arg1 progress:(id)arg2 userInfo:(id)arg3;
- (void)finishProgressForKey:(id)arg1;
- (void)beginProgresssForKey:(id)arg1;
- (void)removeProgressForKey:(id)arg1;
- (void)setProgress:(id)arg1 forKey:(id)arg2 userInfo:(id)arg3;
- (id)progressForKey:(id)arg1;
- (void)onProgressChanged:(id)arg1;
- (void)onFailed:(id)arg1;
- (void)onSuccess:(id)arg1;
- (id)init;
- (void)dealloc;

@end

