//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSMutableDictionary;

@interface DTPasswordErrorManager : NSObject
{
    long long _alertCount;
    NSMutableDictionary *_pageCache;
}

+ (id)sharedInstance;
@property(retain, nonatomic) NSMutableDictionary *pageCache; // @synthesize pageCache=_pageCache;
@property(nonatomic) long long alertCount; // @synthesize alertCount=_alertCount;
- (void).cxx_destruct;
- (void)cleanAlertCount;
- (void)showPasswordErrorWithClassName:(id)arg1 error:(id)arg2 isPasswordIncorrect:(_Bool)arg3 completionBlock:(CDUnknownBlockType)arg4;
- (void)showPasswordCheckViewWithViewController:(id)arg1 CorrectBlock:(CDUnknownBlockType)arg2 completionBlock:(CDUnknownBlockType)arg3;
- (id)init;

@end

