//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class DTImageDataAccessRule, NSString, UIImage;

@interface DTPhotoBrowerItem : NSObject
{
    NSString *_identify;
    NSString *_mediaId;
    DTImageDataAccessRule *_imageAccessRule;
    long long _orientation;
    long long _imageBytesSize;
    long long _picType;
    NSString *_conversationId;
    UIImage *_image;
    NSString *_spaceId;
    NSString *_itemId;
    id _userInfo;
}

+ (id)buildPhotoBrowerItemWithIdentify:(id)arg1 mediaId:(id)arg2 imageAccessRule:(id)arg3 image:(id)arg4 orientation:(long long)arg5 imageBytesSize:(long long)arg6 picType:(long long)arg7 spaceId:(id)arg8 itemId:(id)arg9;
@property(retain, nonatomic) id userInfo; // @synthesize userInfo=_userInfo;
@property(copy, nonatomic) NSString *itemId; // @synthesize itemId=_itemId;
@property(copy, nonatomic) NSString *spaceId; // @synthesize spaceId=_spaceId;
@property(retain, nonatomic) UIImage *image; // @synthesize image=_image;
@property(copy, nonatomic) NSString *conversationId; // @synthesize conversationId=_conversationId;
@property(nonatomic) long long picType; // @synthesize picType=_picType;
@property(nonatomic) long long imageBytesSize; // @synthesize imageBytesSize=_imageBytesSize;
@property(nonatomic) long long orientation; // @synthesize orientation=_orientation;
@property(retain, nonatomic) DTImageDataAccessRule *imageAccessRule; // @synthesize imageAccessRule=_imageAccessRule;
@property(retain, nonatomic) NSString *mediaId; // @synthesize mediaId=_mediaId;
@property(retain, nonatomic) NSString *identify; // @synthesize identify=_identify;
- (void).cxx_destruct;
- (_Bool)isSpaceImage;

@end

