//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIButton.h>

#import "UITextFieldDelegate-Protocol.h"

@class NSString, UIActivityIndicatorView, UIImageView, UILabel, UITextField;

@interface DTProjectorSelectionButton : UIButton <UITextFieldDelegate>
{
    long long _mode;
    UIImageView *_customBgImageView;
    UIImageView *_iconImageView;
    UIImageView *_indicatorImageView;
    UITextField *_projectorNameTextField;
    UILabel *_projectorNameLabel;
    UILabel *_recommendProjectorLabel;
    UILabel *_localProjectorFlagLabel;
    UILabel *_statusLabel;
    UIActivityIndicatorView *_indicatorView;
    _Bool _localProject;
    long long _status;
    NSString *_projectorName;
    NSString *_recommendDeviceDescription;
    CDUnknownBlockType _projectorNameInputDidChangedBlock;
    CDUnknownBlockType _projectorNameButtonTapedBlock;
    CDUnknownBlockType _actionProjecteBlock;
}

@property(copy, nonatomic) CDUnknownBlockType actionProjecteBlock; // @synthesize actionProjecteBlock=_actionProjecteBlock;
@property(copy, nonatomic) CDUnknownBlockType projectorNameButtonTapedBlock; // @synthesize projectorNameButtonTapedBlock=_projectorNameButtonTapedBlock;
@property(copy, nonatomic) CDUnknownBlockType projectorNameInputDidChangedBlock; // @synthesize projectorNameInputDidChangedBlock=_projectorNameInputDidChangedBlock;
@property(copy, nonatomic) NSString *recommendDeviceDescription; // @synthesize recommendDeviceDescription=_recommendDeviceDescription;
@property(copy, nonatomic) NSString *projectorName; // @synthesize projectorName=_projectorName;
@property(nonatomic) long long status; // @synthesize status=_status;
@property(nonatomic) _Bool localProject; // @synthesize localProject=_localProject;
- (void).cxx_destruct;
- (void)textFieldDidChanged:(id)arg1;
- (_Bool)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (_Bool)resignFirstResponder;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1 mode:(long long)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

