//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "DTPushHandlerProtocol-Protocol.h"

@class DTWebPersistence, NSString;

@interface DTPushOAHostHandler : NSObject <DTPushHandlerProtocol>
{
    DTWebPersistence *_webPersistence;
}

@property(retain, nonatomic) DTWebPersistence *webPersistence; // @synthesize webPersistence=_webPersistence;
- (void).cxx_destruct;
- (void)handleCheckInPushClientValue:(id)arg1;
- (void)handleOAHostPush:(id)arg1;
- (void)pushCaught:(id)arg1 error:(id)arg2;
- (void)pushReceived:(id)arg1 value:(id)arg2;
- (Class)returnedValueClass;
- (id)topicName;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

