//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "DTViewController.h"

@class DTIconNameView, DTQRCardView, DTQRNoticeView, DTQROwnerInfoView, DTShareJSInfoModel, NSString, UIButton, UIImage, UIScrollView, UTShareContent;

@interface DTQRCodeCardController : DTViewController
{
    NSString *_qrcodeString;
    DTQRNoticeView *_noticeView;
    UIScrollView *_contentView;
    DTQRCardView *_orgCardView;
    UIImage *_qrCodeImage;
    UIImage *_qrSaveImage;
    UIButton *_saveButton;
    UIButton *_shareButton;
    UTShareContent *_shareContent;
    DTShareJSInfoModel *_shareInfo;
}

@property(retain, nonatomic) DTShareJSInfoModel *shareInfo; // @synthesize shareInfo=_shareInfo;
@property(retain, nonatomic) UTShareContent *shareContent; // @synthesize shareContent=_shareContent;
@property(retain, nonatomic) UIButton *shareButton; // @synthesize shareButton=_shareButton;
@property(retain, nonatomic) UIButton *saveButton; // @synthesize saveButton=_saveButton;
@property(retain, nonatomic) UIImage *qrSaveImage; // @synthesize qrSaveImage=_qrSaveImage;
@property(retain, nonatomic) UIImage *qrCodeImage; // @synthesize qrCodeImage=_qrCodeImage;
@property(retain, nonatomic) DTQRCardView *orgCardView; // @synthesize orgCardView=_orgCardView;
@property(retain, nonatomic) UIScrollView *contentView; // @synthesize contentView=_contentView;
@property(retain, nonatomic) DTQRNoticeView *noticeView; // @synthesize noticeView=_noticeView;
@property(copy, nonatomic) NSString *qrcodeString; // @synthesize qrcodeString=_qrcodeString;
- (void).cxx_destruct;
- (id)createOwnerInfoView;
- (void)shareToDTFriend;
- (void)didTapOnShare:(id)arg1;
- (void)didTapOnSave:(id)arg1;
- (void)StatisticsEventWithArg:(id)arg1;
- (void)showShareMenu;
- (id)sharePanelTitle;
- (void)image:(id)arg1 didFinishSavingWithError:(id)arg2 contextInfo:(void *)arg3;
- (void)saveToAlumb;
- (void)layoutBottomActionButtons;
- (void)viewWillLayoutSubviews;
- (double)qrcodeWidth;
@property(readonly, nonatomic) DTIconNameView *tipInfoView;
@property(readonly, nonatomic) DTQROwnerInfoView *ownerInfoView;
- (void)viewDidLoad;

@end

