//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "Marshal.h"

@class NSArray, NSString;

@interface DTQuickReplyModel : Marshal
{
    _Bool _needUpdate;
    NSArray *_contentList;
    NSString *_latestId;
}

@property(nonatomic) _Bool needUpdate; // @synthesize needUpdate=_needUpdate;
@property(copy, nonatomic) NSString *latestId; // @synthesize latestId=_latestId;
@property(copy, nonatomic) NSArray *contentList; // @synthesize contentList=_contentList;
- (void).cxx_destruct;
- (id)filedsMeta__;
- (id)init;

@end

