//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class DTRedEnvelopeSubscribeLifecycleModel, NSArray, NSString;

@protocol DTRedEnvelopServiceNetworkProtocol <NSObject>
- (void)checkArguments:(NSString *)arg1 size:(long long)arg2 type:(long long)arg3 pickPlanTime:(long long)arg4 successBlock:(void (^)(void))arg5 failureBlock:(void (^)(DTError *))arg6;
- (void)alipayAuthSign:(NSString *)arg1 successBlock:(void (^)(NSString *))arg2 failureBlock:(void (^)(DTError *))arg3;
- (void)alipaySign:(NSString *)arg1 signType:(NSString *)arg2 successBlock:(void (^)(NSString *))arg3 failureBlock:(void (^)(DTError *))arg4;
- (void)queryAcquireResult:(NSString *)arg1 successBlock:(void (^)(DTAcquireResultModel *))arg2 failureBlock:(void (^)(DTError *))arg3;
- (void)getBindAlipaySuccessBlock:(void (^)(NSString *))arg1 failureBlock:(void (^)(DTError *))arg2;
- (void)unbindAlipaySuccessBlock:(void (^)(void))arg1 failureBlock:(void (^)(DTError *))arg2;
- (void)bindAlipay:(NSString *)arg1 authCode:(NSString *)arg2 signString:(NSString *)arg3 signType:(NSString *)arg4 successBlock:(void (^)(void))arg5 failureBlock:(void (^)(DTError *))arg6;
- (void)subscribePlan:(long long)arg1 clusterId:(NSString *)arg2 open:(_Bool)arg3 successBlock:(void (^)(void))arg4 failureBlock:(void (^)(DTError *))arg5;
- (void)calGoodTimeSuccessBlock:(void (^)(DTRedEnvelopGoodTimeModel *))arg1 failureBlock:(void (^)(DTError *))arg2;
- (void)fetchBalanceSuccessBlock:(void (^)(NSString *))arg1 failureBlock:(void (^)(DTError *))arg2;
- (void)queryRedEnvelopCluster:(long long)arg1 clusterId:(NSString *)arg2 startTime:(long long)arg3 size:(int)arg4 flowId:(long long)arg5 successBlock:(void (^)(DTRedEnvelopClusterDetailModel *))arg6 failureBlock:(void (^)(DTError *))arg7;
- (void)queryReceivedRedEnvelops:(int)arg1 start:(int)arg2 size:(int)arg3 successBlock:(void (^)(DTRedEnvelopReceivedListModel *))arg4 failureBlock:(void (^)(DTError *))arg5;
- (void)querySentRedEnvelopClusters:(int)arg1 start:(int)arg2 size:(int)arg3 successBlock:(void (^)(DTRedEnvelopClusterSentListModel *))arg4 failureBlock:(void (^)(DTError *))arg5;
- (void)leaveMessageToRedEnvelopFlow:(long long)arg1 clusterId:(NSString *)arg2 flowId:(int)arg3 leaveMessage:(NSString *)arg4 successBlock:(void (^)(void))arg5 failureBlock:(void (^)(DTError *))arg6;
- (void)pickRedEnvelopClusterV2:(long long)arg1 clusterId:(NSString *)arg2 wua:(NSString *)arg3 umidToken:(NSString *)arg4 successBlock:(void (^)(DTRedEnvelopClusterPickingStatusModel *))arg5 failureBlock:(void (^)(DTError *))arg6;
- (void)pickRedEnvelopCluster:(long long)arg1 clusterId:(NSString *)arg2 successBlock:(void (^)(DTRedEnvelopClusterPickingStatusModel *))arg3 failureBlock:(void (^)(DTError *))arg4;
- (void)checkRedEnvelopClusterPickingStatus:(long long)arg1 clusterId:(NSString *)arg2 successBlock:(void (^)(DTRedEnvelopClusterPickingStatusModel *))arg3 failureBlock:(void (^)(DTError *))arg4;
- (void)generateRedEnvelopClusterV4:(long long)arg1 clusterId:(NSString *)arg2 amount:(NSString *)arg3 size:(int)arg4 receivers:(NSArray *)arg5 type:(long long)arg6 cid:(NSString *)arg7 congratulations:(NSString *)arg8 oid:(long long)arg9 redEnvelopeSubscribeLifecycleModel:(DTRedEnvelopeSubscribeLifecycleModel *)arg10 pickPlanTime:(long long)arg11 ext:(NSString *)arg12 senderPayType:(long long)arg13 signString:(NSString *)arg14 signType:(NSString *)arg15 successBlock:(void (^)(DTRedEnvelopClusterModel *))arg16 failureBlock:(void (^)(DTError *))arg17;
- (void)generateRedEnvelopClusterV3:(long long)arg1 clusterId:(NSString *)arg2 amount:(NSString *)arg3 size:(int)arg4 receivers:(NSArray *)arg5 type:(long long)arg6 cid:(NSString *)arg7 congratulations:(NSString *)arg8 oid:(long long)arg9 redEnvelopeSubscribeLifecycleModel:(DTRedEnvelopeSubscribeLifecycleModel *)arg10 pickPlanTime:(long long)arg11 ext:(NSString *)arg12 signString:(NSString *)arg13 signType:(NSString *)arg14 successBlock:(void (^)(DTRedEnvelopClusterModel *))arg15 failureBlock:(void (^)(DTError *))arg16;
- (void)generateRedEnvelopClusterV2:(long long)arg1 clusterId:(NSString *)arg2 amount:(NSString *)arg3 size:(int)arg4 receivers:(NSArray *)arg5 type:(long long)arg6 cid:(NSString *)arg7 congratulations:(NSString *)arg8 oid:(long long)arg9 redEnvelopeSubscribeLifecycleModel:(DTRedEnvelopeSubscribeLifecycleModel *)arg10 signString:(NSString *)arg11 signType:(NSString *)arg12 successBlock:(void (^)(DTRedEnvelopClusterModel *))arg13 failureBlock:(void (^)(DTError *))arg14;
- (void)generateRedEnvelopCluster:(long long)arg1 clusterId:(NSString *)arg2 amount:(NSString *)arg3 size:(int)arg4 receivers:(NSArray *)arg5 type:(long long)arg6 cid:(NSString *)arg7 congratulations:(NSString *)arg8 oid:(long long)arg9 signString:(NSString *)arg10 signType:(NSString *)arg11 successBlock:(void (^)(DTRedEnvelopClusterModel *))arg12 failureBlock:(void (^)(DTError *))arg13;
@end

