//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class DTAttributedLabel, DTAvatarView, DTBizDingCommentModel, DTBizDingModel, DTDingListAttachAudioView, DTUserNameLabel, UIImageView, UILabel, UIView;

@interface DTReplayTableViewCell : UITableViewCell
{
    DTBizDingCommentModel *_commentModel;
    DTBizDingModel *_dingModel;
    DTAvatarView *_avatarView;
    DTUserNameLabel *_nameLabel;
    DTAttributedLabel *_textInfoLabel;
    UIView *_labelBgView;
    UIImageView *_separatorLine;
    UILabel *_attachTextView;
    DTDingListAttachAudioView *_audioView;
}

+ (double)replayCellHeight;
@property(retain, nonatomic) DTDingListAttachAudioView *audioView; // @synthesize audioView=_audioView;
@property(retain, nonatomic) UILabel *attachTextView; // @synthesize attachTextView=_attachTextView;
@property(retain, nonatomic) UIImageView *separatorLine; // @synthesize separatorLine=_separatorLine;
@property(retain, nonatomic) UIView *labelBgView; // @synthesize labelBgView=_labelBgView;
@property(retain, nonatomic) DTAttributedLabel *textInfoLabel; // @synthesize textInfoLabel=_textInfoLabel;
@property(retain, nonatomic) DTUserNameLabel *nameLabel; // @synthesize nameLabel=_nameLabel;
@property(retain, nonatomic) DTAvatarView *avatarView; // @synthesize avatarView=_avatarView;
@property(retain, nonatomic) DTBizDingModel *dingModel; // @synthesize dingModel=_dingModel;
@property(retain, nonatomic) DTBizDingCommentModel *commentModel; // @synthesize commentModel=_commentModel;
- (void).cxx_destruct;
- (void)dingModelUpdate:(id)arg1;
- (void)configWithDingModel:(id)arg1;
- (void)configWithCommentModel:(id)arg1;
- (void)layoutDingInfoFrame;
- (void)layoutSubviews;
- (void)loadSubviews;
- (void)dealloc;
- (void)addObservers;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

