//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class DTRightsLevelDetailItem, NSArray, UIButton, UILabel;

@interface DTRightsLevelDetailView : UIView
{
    UIButton *_singleButton;
    UILabel *_rightsTypeLabel;
    UILabel *_timeDescLabel;
    UILabel *_detailDescLabel;
    NSArray *_rightsInfoArray;
    DTRightsLevelDetailItem *_item;
}

+ (id)convertToTitleWithType:(unsigned long long)arg1 orgLevel:(long long)arg2;
+ (unsigned long long)indexByLevelType:(unsigned long long)arg1;
@property(retain, nonatomic) DTRightsLevelDetailItem *item; // @synthesize item=_item;
@property(retain, nonatomic) NSArray *rightsInfoArray; // @synthesize rightsInfoArray=_rightsInfoArray;
@property(retain, nonatomic) UILabel *detailDescLabel; // @synthesize detailDescLabel=_detailDescLabel;
@property(retain, nonatomic) UILabel *timeDescLabel; // @synthesize timeDescLabel=_timeDescLabel;
@property(retain, nonatomic) UILabel *rightsTypeLabel; // @synthesize rightsTypeLabel=_rightsTypeLabel;
@property(retain, nonatomic) UIButton *singleButton; // @synthesize singleButton=_singleButton;
- (void).cxx_destruct;
- (void)clickButton;
- (void)setCurrentRightsType:(unsigned long long)arg1 orgLevel:(long long)arg2;
- (void)setSelectedStatus:(_Bool)arg1;
- (void)configureWithItem:(id)arg1;
- (void)loadComponent;
- (void)layoutSubviews;
- (struct CGPoint)lineRightPoint;
- (struct CGPoint)lineLeftPoint;
- (void)setFrame:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

