//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class DTRoutePlanningViewController, MAAnnotationView, UIView;
@protocol MAAnnotation;

@protocol DTRoutePlanPanelDelegate <NSObject>
- (void)routePlanningViewController:(DTRoutePlanningViewController *)arg1 routePlanningType:(long long)arg2 selectCourseIndex:(unsigned long long)arg3 courseAmount:(unsigned long long)arg4 distance:(long long)arg5 duration:(long long)arg6;
- (struct CLLocationCoordinate2D)destinationCoordinateForController:(DTRoutePlanningViewController *)arg1;
- (struct CLLocationCoordinate2D)startCoordinateForController:(DTRoutePlanningViewController *)arg1;
- (long long)searchTypeForController:(DTRoutePlanningViewController *)arg1;
- (MAAnnotationView *)annotationView:(DTRoutePlanningViewController *)arg1 viewForAnnotation:(id <MAAnnotation>)arg2;
- (_Bool)useDefalutAnnotationViewsForController:(DTRoutePlanningViewController *)arg1;
- (UIView *)customControlPaneForController:(DTRoutePlanningViewController *)arg1;
- (_Bool)useDefalutControlPaneForController:(DTRoutePlanningViewController *)arg1;
@end

