//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SClient.h"

@interface DTSafeIService : SClient
{
}

+ (id)_appname__;
+ (id)_serviceKey__;
- (void)checkCalendar:(id)arg1 callback:(id)arg2;
- (void)reportAfterProcessStart:(id)arg1 callback:(id)arg2;
- (void)reportSecurityData:(id)arg1 callback:(id)arg2;
- (void)queryMsgSaveTime:(id)arg1 callback:(id)arg2;
- (void)checkSimulator:(id)arg1 callback:(id)arg2;
- (void)advert:(id)arg1 callback:(id)arg2;
- (void)suggest:(id)arg1 callback:(id)arg2;
- (void)oplog:(id)arg1 type:(id)arg2 source:(id)arg3 callback:(id)arg4;

@end

