//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class DTCalendarEvent, EKEvent, UILabel, UIView;

@interface DTScheduleDetailContentCell : UITableViewCell
{
    DTCalendarEvent *_calendarEvent;
    EKEvent *_systemEvent;
    UILabel *_contentLabel;
    UIView *_otherLabelsContainerView;
}

@property(retain, nonatomic) UIView *otherLabelsContainerView; // @synthesize otherLabelsContainerView=_otherLabelsContainerView;
@property(retain, nonatomic) UILabel *contentLabel; // @synthesize contentLabel=_contentLabel;
@property(retain, nonatomic) EKEvent *systemEvent; // @synthesize systemEvent=_systemEvent;
@property(retain, nonatomic) DTCalendarEvent *calendarEvent; // @synthesize calendarEvent=_calendarEvent;
- (void).cxx_destruct;
- (id)formattedDateStringFromMillisecond:(double)arg1 showsHour:(_Bool)arg2;
- (id)formattedDateStringFromEndTime:(double)arg1 showsHour:(_Bool)arg2 showsPrefix:(_Bool)arg3;
- (id)formattedDateStringFromStartTime:(double)arg1 showsHour:(_Bool)arg2 showsPrefix:(_Bool)arg3;
- (id)formattedDateStringFromStartTime:(double)arg1 toEndTime:(double)arg2;
- (_Bool)isDate:(id)arg1 inSameDayAsDate:(id)arg2;
- (id)labelsWithStartDate:(id)arg1 endDate:(id)arg2 isAllDay:(_Bool)arg3;
- (void)locationDidTapHandler:(id)arg1;
- (id)locationAttributedStringWithString:(id)arg1;
- (id)locationLabelWithSystemEvent:(id)arg1;
- (id)repeatLabelWithSystemEvent:(id)arg1;
- (id)repeatLabelWithCalendarEvent:(id)arg1;
- (void)removeOtherLabelsContainerSubviews;
- (void)addOtherLabelsToContainerView:(id)arg1;
- (id)createOtherLabel;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

