//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSMutableArray, UIButton, UIImageView, UILabel, UITextView;

@interface DTScaleDevView : UIView
{
    UIImageView *_line;
    UILabel *_titleLabel;
    UIView *_ruler;
    UIImageView *_rulerLine;
    NSMutableArray *_scaleArray;
    UIImageView *_pointer;
    UILabel *_label;
    UIImageView *_bottomLine;
    UIButton *_openBtn;
    UIView *_bgView;
    UITextView *_logTextView;
    UIButton *_textViewCloseBtn;
    UIButton *_textViewClearBtn;
    UIView *_bgColorView;
    UIButton *_printVCBtn;
    UIButton *_dragBtn;
}

@property(retain, nonatomic) UIButton *dragBtn; // @synthesize dragBtn=_dragBtn;
@property(retain, nonatomic) UIButton *printVCBtn; // @synthesize printVCBtn=_printVCBtn;
@property(retain, nonatomic) UIView *bgColorView; // @synthesize bgColorView=_bgColorView;
@property(retain, nonatomic) UIButton *textViewClearBtn; // @synthesize textViewClearBtn=_textViewClearBtn;
@property(retain, nonatomic) UIButton *textViewCloseBtn; // @synthesize textViewCloseBtn=_textViewCloseBtn;
@property(retain, nonatomic) UITextView *logTextView; // @synthesize logTextView=_logTextView;
@property(retain, nonatomic) UIView *bgView; // @synthesize bgView=_bgView;
@property(retain, nonatomic) UIButton *openBtn; // @synthesize openBtn=_openBtn;
@property(retain, nonatomic) UIImageView *bottomLine; // @synthesize bottomLine=_bottomLine;
@property(retain, nonatomic) UILabel *label; // @synthesize label=_label;
@property(retain, nonatomic) UIImageView *pointer; // @synthesize pointer=_pointer;
@property(retain, nonatomic) NSMutableArray *scaleArray; // @synthesize scaleArray=_scaleArray;
@property(retain, nonatomic) UIImageView *rulerLine; // @synthesize rulerLine=_rulerLine;
@property(retain, nonatomic) UIView *ruler; // @synthesize ruler=_ruler;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) UIImageView *line; // @synthesize line=_line;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (void)closeUtil;
- (void)printVC;
- (void)handleTouchInPoint:(struct CGPoint)arg1;
- (void)openUtil;
- (void)clearTextView;
- (void)closeTextView;
- (void)logInfo:(id)arg1;
- (void)minimizeUtil;
- (void)handleOpenBtnDrag:(id)arg1;
- (void)handleDrag:(id)arg1;
- (void)handleTap:(id)arg1;
- (void)handlePan:(id)arg1;
- (void)loadComponents;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

