//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "DTViewController.h"

#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class DTCalendarEvent, NSDate, NSString, UIBarButtonItem, UITableView;

@interface DTScheduleDetailViewController : DTViewController <UITableViewDelegate, UITableViewDataSource>
{
    DTCalendarEvent *_calendarEvent;
    NSDate *_currentDate;
    UITableView *_tableView;
    UIBarButtonItem *_moreBarButtonItem;
}

@property(retain, nonatomic) UIBarButtonItem *moreBarButtonItem; // @synthesize moreBarButtonItem=_moreBarButtonItem;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
@property(readonly, nonatomic) NSDate *currentDate; // @synthesize currentDate=_currentDate;
@property(readonly, nonatomic) DTCalendarEvent *calendarEvent; // @synthesize calendarEvent=_calendarEvent;
- (void).cxx_destruct;
- (long long)alertModeByUrgentType:(long long)arg1;
- (long long)alertTimeByUrgentType:(long long)arg1;
- (long long)urgentTypeByAlertMode:(long long)arg1;
- (long long)remindTypeByAlertTime:(long long)arg1;
- (_Bool)showsNotes;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)registerCells;
- (void)popViewController;
- (void)pushRemindPickerViewController;
- (void)presentDeleteAlertController;
- (void)presentEditAlertController;
- (void)updateCalendarEvent:(id)arg1 currentDate:(id)arg2;
- (void)updateCalendarAlertWithAlertTime:(long long)arg1;
- (void)deleteAllFutureSchedules;
- (void)deleteThisScheduleOnly;
- (void)moreItemDidTapHandler:(id)arg1;
- (void)setupBarButtonItems;
- (void)viewDidLoad;
- (id)initWithCalendarEvent:(id)arg1 currentDate:(id)arg2;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

