//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSAttributedString, NSString;

@interface DTSearchUser : NSObject
{
    NSString *_userIdentifier;
    long long _uid;
    NSString *_avatarMediaId;
    NSString *_name;
    NSAttributedString *_attrName;
    NSString *_orgInfo;
    NSAttributedString *_attrOrgInfo;
    NSString *_comment;
    NSAttributedString *_attrComment;
    NSString *_mobile;
    NSString *_email;
    NSString *_dingAccount;
    long long _orgId;
    NSString *_staffId;
    unsigned long long _source;
    CDUnknownBlockType _infoDidUpdateBlock;
    unsigned long long _callbackMode;
}

+ (unsigned long long)callbackModeFromString:(id)arg1;
+ (id)userWithSearchRecommendUser:(id)arg1 searchText:(id)arg2;
+ (id)userWithUid:(long long)arg1 type:(unsigned long long)arg2 name:(id)arg3 orgInfo:(id)arg4 comment:(id)arg5 commentPrefix:(id)arg6 searchText:(id)arg7 callbackMode:(id)arg8;
+ (id)userWithUid:(long long)arg1 type:(unsigned long long)arg2 name:(id)arg3 orgInfo:(id)arg4 comment:(id)arg5 searchText:(id)arg6 callbackMode:(id)arg7;
@property(nonatomic) unsigned long long callbackMode; // @synthesize callbackMode=_callbackMode;
@property(copy, nonatomic) CDUnknownBlockType infoDidUpdateBlock; // @synthesize infoDidUpdateBlock=_infoDidUpdateBlock;
@property(nonatomic) unsigned long long source; // @synthesize source=_source;
@property(copy, nonatomic) NSString *staffId; // @synthesize staffId=_staffId;
@property(nonatomic) long long orgId; // @synthesize orgId=_orgId;
@property(copy, nonatomic) NSString *dingAccount; // @synthesize dingAccount=_dingAccount;
@property(copy, nonatomic) NSString *email; // @synthesize email=_email;
@property(copy, nonatomic) NSString *mobile; // @synthesize mobile=_mobile;
@property(copy, nonatomic) NSAttributedString *attrComment; // @synthesize attrComment=_attrComment;
@property(copy, nonatomic) NSString *comment; // @synthesize comment=_comment;
@property(copy, nonatomic) NSAttributedString *attrOrgInfo; // @synthesize attrOrgInfo=_attrOrgInfo;
@property(copy, nonatomic) NSString *orgInfo; // @synthesize orgInfo=_orgInfo;
@property(copy, nonatomic) NSAttributedString *attrName; // @synthesize attrName=_attrName;
@property(copy, nonatomic) NSString *name; // @synthesize name=_name;
@property(copy, nonatomic) NSString *avatarMediaId; // @synthesize avatarMediaId=_avatarMediaId;
@property(nonatomic) long long uid; // @synthesize uid=_uid;
@property(copy, nonatomic) NSString *userIdentifier; // @synthesize userIdentifier=_userIdentifier;
- (void).cxx_destruct;
- (id)recommendUser;
- (id)initWithExternalContact:(id)arg1;
- (long long)searchUserLogDataType;

@end

