//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSString, WKBizMessage;

@interface DTSendMessageContext : NSObject
{
    _Bool _needFilter;
    _Bool _needUploadAttachment;
    WKBizMessage *_msg;
    NSString *_cId;
    unsigned long long _spaceFileType;
}

+ (id)buildWithWKMessage:(id)arg1 cId:(id)arg2 needFilter:(_Bool)arg3;
@property(nonatomic) _Bool needUploadAttachment; // @synthesize needUploadAttachment=_needUploadAttachment;
@property(nonatomic) unsigned long long spaceFileType; // @synthesize spaceFileType=_spaceFileType;
@property(nonatomic) _Bool needFilter; // @synthesize needFilter=_needFilter;
@property(retain, nonatomic) NSString *cId; // @synthesize cId=_cId;
@property(retain, nonatomic) WKBizMessage *msg; // @synthesize msg=_msg;
- (void).cxx_destruct;

@end

