//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class DTSettingScoreItem, UIButton, UIImageView, UILabel;

@interface DTSettingScoreView : UIView
{
    UIImageView *_icon;
    UILabel *_scoreLabel;
    UIButton *_button;
    UIImageView *_scoreStateIcon;
    UIImageView *_badgeView;
    DTSettingScoreItem *_item;
}

@property(retain, nonatomic) DTSettingScoreItem *item; // @synthesize item=_item;
@property(retain, nonatomic) UIImageView *badgeView; // @synthesize badgeView=_badgeView;
@property(retain, nonatomic) UIImageView *scoreStateIcon; // @synthesize scoreStateIcon=_scoreStateIcon;
@property(retain, nonatomic) UIButton *button; // @synthesize button=_button;
@property(retain, nonatomic) UILabel *scoreLabel; // @synthesize scoreLabel=_scoreLabel;
@property(retain, nonatomic) UIImageView *icon; // @synthesize icon=_icon;
- (void).cxx_destruct;
- (id)accessibilityLabel;
- (_Bool)isAccessibilityElement;
- (void)buttonClick:(id)arg1;
- (void)refreshScoreViewWithShowRedDot:(_Bool)arg1;
- (void)refreshScoreViewWithItem:(id)arg1;
- (void)loadComponent;
- (id)initWithFrame:(struct CGRect)arg1;

@end

