//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSMutableDictionary;
@protocol OS_dispatch_semaphore;

@interface DTServiceManager : NSObject
{
    NSMutableDictionary *_serviceDict;
    NSObject<OS_dispatch_semaphore> *_lock;
}

- (void).cxx_destruct;
- (id)serviceInfoWithService:(id)arg1;
- (id)fetchService:(id)arg1;
- (void)unregisterService:(id)arg1;
- (void)registerService:(id)arg1 implBlock:(CDUnknownBlockType)arg2 callOnce:(_Bool)arg3;
- (void)registerService:(id)arg1 implInstance:(id)arg2;
- (void)registerService:(id)arg1 implClass:(Class)arg2;
- (void)handleProtocolAlreadyRegisteredCase:(id)arg1;
- (id)init;

@end

