//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "DTLoadMoreDelegate-Protocol.h"
#import "DTSearchHandlerProtocol-Protocol.h"

@class DTLoadMoreController, DTSearchConversationDataSource, DTSearchGlobalHomeView, DTSearchRecommendDataSource, DTSearchViewController, DTSectionItem, DTSingleLineUserCellItem, NSDictionary, NSString;

@interface DTSearchConversationHandler : NSObject <DTLoadMoreDelegate, DTSearchHandlerProtocol>
{
    _Bool _hasResult;
    DTSearchViewController *_searchVC;
    NSString *_searchText;
    DTLoadMoreController *_loadMoreController;
    DTSectionItem *_groupSection;
    DTSectionItem *_networkSearchSection;
    DTSectionItem *_recommendSection;
    DTSectionItem *_fuzzySearchResultSection;
    DTSingleLineUserCellItem *_networkSearchCellItem;
    DTSearchRecommendDataSource *_recommendDataSource;
    DTSearchConversationDataSource *_groupDataSource;
    DTSearchGlobalHomeView *_homeView;
    NSDictionary *_existConversationDic;
}

@property(nonatomic) _Bool hasResult; // @synthesize hasResult=_hasResult;
@property(copy, nonatomic) NSDictionary *existConversationDic; // @synthesize existConversationDic=_existConversationDic;
@property(retain, nonatomic) DTSearchGlobalHomeView *homeView; // @synthesize homeView=_homeView;
@property(retain, nonatomic) DTSearchConversationDataSource *groupDataSource; // @synthesize groupDataSource=_groupDataSource;
@property(retain, nonatomic) DTSearchRecommendDataSource *recommendDataSource; // @synthesize recommendDataSource=_recommendDataSource;
@property(retain, nonatomic) DTSingleLineUserCellItem *networkSearchCellItem; // @synthesize networkSearchCellItem=_networkSearchCellItem;
@property(retain, nonatomic) DTSectionItem *fuzzySearchResultSection; // @synthesize fuzzySearchResultSection=_fuzzySearchResultSection;
@property(retain, nonatomic) DTSectionItem *recommendSection; // @synthesize recommendSection=_recommendSection;
@property(retain, nonatomic) DTSectionItem *networkSearchSection; // @synthesize networkSearchSection=_networkSearchSection;
@property(retain, nonatomic) DTSectionItem *groupSection; // @synthesize groupSection=_groupSection;
@property(retain, nonatomic) DTLoadMoreController *loadMoreController; // @synthesize loadMoreController=_loadMoreController;
@property(copy, nonatomic) NSString *searchText; // @synthesize searchText=_searchText;
@property(nonatomic) __weak DTSearchViewController *searchVC; // @synthesize searchVC=_searchVC;
- (void).cxx_destruct;
- (id)recommendSectionItem;
- (void)searchGroupsWithSearchText:(id)arg1 searchController:(id)arg2 loadMoreController:(id)arg3 searchLog:(id)arg4 tabType:(long long)arg5;
- (void)loadMoreControllerWillBeginLoading:(id)arg1;
- (void)reloadSearchDataSource;
- (void)reloadHomeViewDatasource;
- (void)reloadDataSourceIfNeeded;
- (void)searchHistoryDidUpdatedWithType:(unsigned long long)arg1;
- (void)searchHistoryDidCleanWithType:(unsigned long long)arg1;
- (id)searchHomeViewWithContainViewFrame:(struct CGRect)arg1;
- (void)searchTableDidScroll:(id)arg1;
- (void)searchViewControllerWillHide;
- (void)searchViewControllerWillShow;
- (id)handlerTitle;
- (id)dataSourceWithSearchText:(id)arg1;
- (void)searchWithSearchText:(id)arg1 searchController:(id)arg2 searchLog:(id)arg3 tabType:(long long)arg4;
- (void)searchTextDidSearch:(id)arg1;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

