//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "DTViewController.h"

#import "UIScrollViewDelegate-Protocol.h"

@class DTContact, DTLabelCollectionViewDatasource, DTLabelItem, DTNameInputView, DTSelectionInputView, NSString, UIButton, UICollectionView, UIControl, UILabel, UIScrollView;

@interface DTSettingProfileViewController : DTViewController <UIScrollViewDelegate>
{
    NSString *_headerTitle;
    NSString *_headerDetail;
    NSString *_password;
    DTContact *_userProfile;
    CDUnknownBlockType _finishBlock;
    UIScrollView *_containerView;
    UIControl *_backgroundView;
    UILabel *_titleLabel;
    UILabel *_detailLabel;
    DTNameInputView *_nameView;
    DTSelectionInputView *_industryView;
    UILabel *_roleTitleLabel;
    UICollectionView *_rolesView;
    DTLabelCollectionViewDatasource *_labelDatasource;
    DTLabelItem *_editItem;
    UIButton *_doneButton;
    long long _industryCode;
}

@property(nonatomic) long long industryCode; // @synthesize industryCode=_industryCode;
@property(retain, nonatomic) UIButton *doneButton; // @synthesize doneButton=_doneButton;
@property(retain, nonatomic) DTLabelItem *editItem; // @synthesize editItem=_editItem;
@property(retain, nonatomic) DTLabelCollectionViewDatasource *labelDatasource; // @synthesize labelDatasource=_labelDatasource;
@property(retain, nonatomic) UICollectionView *rolesView; // @synthesize rolesView=_rolesView;
@property(retain, nonatomic) UILabel *roleTitleLabel; // @synthesize roleTitleLabel=_roleTitleLabel;
@property(retain, nonatomic) DTSelectionInputView *industryView; // @synthesize industryView=_industryView;
@property(retain, nonatomic) DTNameInputView *nameView; // @synthesize nameView=_nameView;
@property(retain, nonatomic) UILabel *detailLabel; // @synthesize detailLabel=_detailLabel;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) UIControl *backgroundView; // @synthesize backgroundView=_backgroundView;
@property(retain, nonatomic) UIScrollView *containerView; // @synthesize containerView=_containerView;
@property(copy, nonatomic) CDUnknownBlockType finishBlock; // @synthesize finishBlock=_finishBlock;
@property(retain, nonatomic) DTContact *userProfile; // @synthesize userProfile=_userProfile;
@property(copy, nonatomic) NSString *password; // @synthesize password=_password;
@property(copy, nonatomic) NSString *headerDetail; // @synthesize headerDetail=_headerDetail;
@property(copy, nonatomic) NSString *headerTitle; // @synthesize headerTitle=_headerTitle;
- (void).cxx_destruct;
- (void)showError:(id)arg1;
- (_Bool)validateContent;
- (void)updateDoneButtonState;
- (id)getDefaultModelList;
- (void)pickIndustry;
- (void)showRoles:(id)arg1;
- (void)fetchRoles;
- (void)configurePageContentSize;
- (void)doneButtonPressed:(id)arg1;
- (void)containerViewPressed:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)viewDidLayoutSubviews;
- (void)loadDatasource;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

