//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "DTConversationListController.h"

@class NSString;

@interface DTSecPageListController : DTConversationListController
{
    NSString *_parentTitle;
    NSString *_parentCid;
}

@property(copy, nonatomic) NSString *parentCid; // @synthesize parentCid=_parentCid;
@property(copy, nonatomic) NSString *parentTitle; // @synthesize parentTitle=_parentTitle;
- (void).cxx_destruct;
- (void)setting:(id)arg1;
- (void)didReceiveMemoryWarning;
- (void)loadSearchView;
- (void)loadTitleView;
- (void)assignmentDataSource;
- (void)loadComponents;
- (void)updateConnectionStatusTitle;
- (void)setRightNavigationItem;
- (void)setNavigationItem;
- (void)setUpDataSource;
- (void)showGuideView;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

@end

