//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "DTTableViewController.h"

@class DTSearchController;

@interface DTSearchBizViewController : DTTableViewController
{
    _Bool _showBackButton;
    _Bool _hasKeyboardShowed;
    _Bool _hasBackButtonShow;
    DTSearchController *_searchController;
}

@property(nonatomic) _Bool hasBackButtonShow; // @synthesize hasBackButtonShow=_hasBackButtonShow;
@property(nonatomic) _Bool hasKeyboardShowed; // @synthesize hasKeyboardShowed=_hasKeyboardShowed;
@property(nonatomic) _Bool showBackButton; // @synthesize showBackButton=_showBackButton;
@property(retain, nonatomic) DTSearchController *searchController; // @synthesize searchController=_searchController;
- (void).cxx_destruct;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)didMoveToParentViewController:(id)arg1;
- (void)willMoveToParentViewController:(id)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;

@end

