//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UICollectionViewCell.h>

@class DTSearchStickerViewModel, FLAnimatedImageView, HKCircularProgressView;

@interface DTSearchStickerCollectionViewCell : UICollectionViewCell
{
    float _previousProgress;
    DTSearchStickerViewModel *_stickerViewModel;
    FLAnimatedImageView *_animatedImageView;
    HKCircularProgressView *_progressView;
}

@property(retain, nonatomic) HKCircularProgressView *progressView; // @synthesize progressView=_progressView;
@property(retain, nonatomic) FLAnimatedImageView *animatedImageView; // @synthesize animatedImageView=_animatedImageView;
@property(retain, nonatomic) DTSearchStickerViewModel *stickerViewModel; // @synthesize stickerViewModel=_stickerViewModel;
- (void).cxx_destruct;
- (void)updateSticker;
- (void)updateAnimatedImageData:(id)arg1;
- (void)updateDownloadProgress:(float)arg1;
- (void)prepareForReuse;
- (void)layoutSubviews;
- (void)setupStickerCollectionViewCell;
- (id)initWithFrame:(struct CGRect)arg1;

@end

