//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSString;

@interface DTSearchQueryLogger : NSObject
{
    unsigned long long _searchSourceType;
    long long _searchDataType;
    long long _searchTabType;
    double _startTime;
    double _endTime;
    unsigned long long _count;
    NSString *_bucket;
    long long _errorCode;
    NSString *_errorReason;
}

+ (id)queryLogerKeyWithSearchDataType:(long long)arg1 sourceType:(unsigned long long)arg2 searchTabType:(long long)arg3 narrowString:(id)arg4;
@property(copy, nonatomic) NSString *errorReason; // @synthesize errorReason=_errorReason;
@property(nonatomic) long long errorCode; // @synthesize errorCode=_errorCode;
@property(copy, nonatomic) NSString *bucket; // @synthesize bucket=_bucket;
@property(nonatomic) unsigned long long count; // @synthesize count=_count;
@property(nonatomic) double endTime; // @synthesize endTime=_endTime;
@property(nonatomic) double startTime; // @synthesize startTime=_startTime;
@property(nonatomic) long long searchTabType; // @synthesize searchTabType=_searchTabType;
@property(nonatomic) long long searchDataType; // @synthesize searchDataType=_searchDataType;
@property(nonatomic) unsigned long long searchSourceType; // @synthesize searchSourceType=_searchSourceType;
- (void).cxx_destruct;
- (void)endSearchFailureWithSearchDataType:(long long)arg1 sourceType:(unsigned long long)arg2 searchTabType:(long long)arg3 errorCode:(long long)arg4 reason:(id)arg5;
@property(readonly, nonatomic) unsigned long long serverSearchCount;
@property(readonly, nonatomic) unsigned long long nativeSearchCount;
- (void)endSearchSuccessWithSearchDataType:(long long)arg1 sourceType:(unsigned long long)arg2 searchTabType:(long long)arg3 count:(unsigned long long)arg4 bucket:(id)arg5;
- (void)beginSearchWithSearchDataType:(long long)arg1 sourceType:(unsigned long long)arg2 searchTabType:(long long)arg3;
@property(readonly, nonatomic) double duration;
- (id)init;

@end

