//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "DTTableViewCell.h"

@class DTBadgeView, UIImageView, UILabel;

@interface DTSettingTableViewCell : DTTableViewCell
{
    UILabel *_titleLabel;
    UILabel *_detailLabel;
    UIImageView *_iconImage;
    UIImageView *_detailIconImage;
    UIImageView *_indicatorView;
    DTBadgeView *_badgeView;
    long long _index;
    long long _number;
}

@property(nonatomic) long long number; // @synthesize number=_number;
@property(nonatomic) long long index; // @synthesize index=_index;
@property(retain, nonatomic) DTBadgeView *badgeView; // @synthesize badgeView=_badgeView;
@property(retain, nonatomic) UIImageView *indicatorView; // @synthesize indicatorView=_indicatorView;
@property(retain, nonatomic) UIImageView *detailIconImage; // @synthesize detailIconImage=_detailIconImage;
@property(retain, nonatomic) UIImageView *iconImage; // @synthesize iconImage=_iconImage;
@property(retain, nonatomic) UILabel *detailLabel; // @synthesize detailLabel=_detailLabel;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
- (void).cxx_destruct;
- (void)configCell:(id)arg1;
- (void)setLocationOfCellAtIndex:(long long)arg1 inNumberOfRowsInSelfSection:(long long)arg2;
- (void)drawSeperaterLineOfCell;
- (void)layoutSubviews;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

