//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class OpenMDHandler;

@interface DTSearchHistory : NSObject
{
    OpenMDHandler *_searchHistoryHandler;
}

+ (id)sharedInstance;
@property(retain, nonatomic) OpenMDHandler *searchHistoryHandler; // @synthesize searchHistoryHandler=_searchHistoryHandler;
- (void).cxx_destruct;
- (void)saveHistoryModel:(id)arg1;
- (void)clearWithTypes:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)clearWithType:(unsigned long long)arg1 completion:(CDUnknownBlockType)arg2;
- (void)asyncSaveWord:(id)arg1 type:(unsigned long long)arg2 extra:(id)arg3 completion:(CDUnknownBlockType)arg4;
- (void)asyncSaveWord:(id)arg1 type:(unsigned long long)arg2 completion:(CDUnknownBlockType)arg3;
- (id)recentHistorysWithTypes:(id)arg1 size:(unsigned long long)arg2;
- (id)recentHistorysWithType:(unsigned long long)arg1 size:(unsigned long long)arg2;
- (void)onSignOut;
- (void)onSignIn;
- (void)dealloc;
- (id)init;

@end

