//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface DTShareModelService : NSObject
{
}

+ (id)sharedInstance;
- (void)checkShareApp:(id)arg1 identifier:(id)arg2 signature:(id)arg3 type:(id)arg4 shareModel:(id)arg5 ext:(id)arg6 successBlock:(CDUnknownBlockType)arg7 failureBlock:(CDUnknownBlockType)arg8;
- (void)loadShareModelWithURL:(id)arg1 hasWhiteListCheck:(_Bool)arg2 successBlock:(CDUnknownBlockType)arg3 failureBlock:(CDUnknownBlockType)arg4;

@end

