//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SClient.h"

@interface DTSmartDeviceIService : SClient
{
}

+ (id)_appname__;
+ (id)_serviceKey__;
- (void)getDeviceEndorsement:(id)arg1 devTypeCode:(id)arg2 devId:(id)arg3 major:(id)arg4 minor:(id)arg5 callback:(id)arg6;
- (void)getDeviceLiteAppUrl:(id)arg1 devId:(id)arg2 callback:(id)arg3;
- (void)bindAndActive:(id)arg1 callback:(id)arg2;
- (void)getDeviceSecret:(id)arg1 devId:(id)arg2 callback:(id)arg3;
- (void)updateDevcieNick:(id)arg1 devId:(id)arg2 nick:(id)arg3 callback:(id)arg4;
- (void)getDeviceInfo:(id)arg1 devId:(id)arg2 callback:(id)arg3;
- (void)listDevices:(id)arg1 deviceType:(id)arg2 size:(id)arg3 callback:(id)arg4;
- (void)unbindV2:(id)arg1 deviceType:(id)arg2 sn:(id)arg3 deviceUid:(id)arg4 callback:(id)arg5;
- (void)unbind:(id)arg1 deviceType:(id)arg2 sn:(id)arg3 activeCode:(id)arg4 callback:(id)arg5;
- (void)bind:(id)arg1 deviceType:(id)arg2 sn:(id)arg3 activeCode:(id)arg4 description:(id)arg5 nick:(id)arg6 callback:(id)arg7;
- (void)validForBind:(id)arg1 activeCode:(id)arg2 callback:(id)arg3;
- (void)report:(id)arg1 sn:(id)arg2 activeCode:(id)arg3 secret:(id)arg4 environment:(id)arg5 callback:(id)arg6;
- (void)active:(id)arg1 sn:(id)arg2 activeCode:(id)arg3 callback:(id)arg4;
- (void)provideActiveCode:(id)arg1 deviceKey:(id)arg2 callback:(id)arg3;

@end

