//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "DTPeripheralScanManagerDelegate-Protocol.h"
#import "DTSmartLocationServiceDelegate-Protocol.h"

@class DTSmartBroadcastClient, DTSmartEntityService, DTSmartLocationService, LWPQueue, NSString;

@interface DTSmartService : NSObject <DTSmartLocationServiceDelegate, DTPeripheralScanManagerDelegate>
{
    _Bool _backgroudMode;
    DTSmartBroadcastClient *_broadcastClient;
    LWPQueue *_smartQueue;
    DTSmartLocationService *_smartLocationManager;
    DTSmartEntityService *_smartEntityService;
}

+ (id)sharedService;
@property(retain, nonatomic) DTSmartEntityService *smartEntityService; // @synthesize smartEntityService=_smartEntityService;
@property(retain, nonatomic) DTSmartLocationService *smartLocationManager; // @synthesize smartLocationManager=_smartLocationManager;
@property(nonatomic) _Bool backgroudMode; // @synthesize backgroudMode=_backgroudMode;
@property(retain, nonatomic) LWPQueue *smartQueue; // @synthesize smartQueue=_smartQueue;
@property(retain, nonatomic) DTSmartBroadcastClient *broadcastClient; // @synthesize broadcastClient=_broadcastClient;
- (void).cxx_destruct;
- (void)didScanNoData:(id)arg1;
- (void)didDisableScan:(id)arg1;
- (void)didStopScan:(id)arg1;
- (_Bool)centralManager:(id)arg1 didDiscoverPeripheral:(id)arg2 advertisementData:(id)arg3 RSSI:(id)arg4;
- (void)didRangingBeacons:(id)arg1;
- (void)didExitRegion:(id)arg1;
- (void)didEnterRegion:(id)arg1;
- (void)stopBle;
- (void)startBle;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

