//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIImageView, UITableView;

@interface DTSortSelectionView : UIView
{
    UITableView *_leftTableView;
    UITableView *_rightTableView;
    CDUnknownBlockType _pressStaturBarBlock;
    UIImageView *_topLine;
}

@property(retain, nonatomic) UIImageView *topLine; // @synthesize topLine=_topLine;
@property(copy, nonatomic) CDUnknownBlockType pressStaturBarBlock; // @synthesize pressStaturBarBlock=_pressStaturBarBlock;
@property(retain, nonatomic) UITableView *rightTableView; // @synthesize rightTableView=_rightTableView;
@property(retain, nonatomic) UITableView *leftTableView; // @synthesize leftTableView=_leftTableView;
- (void).cxx_destruct;
- (void)reload;
- (void)removeDataSourceAndDelegate;
- (void)setDataSourceAndDelegate:(id)arg1;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

