//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "DTViewController.h"

#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class DTSpaceCollectFileEmptyView, NSArray, NSString, UITableView;

@interface DTSpaceHomeworkListViewController : DTViewController <UITableViewDelegate, UITableViewDataSource>
{
    NSArray *_folders;
    NSString *_token;
    NSString *_cid;
    UITableView *_tableView;
    DTSpaceCollectFileEmptyView *_emptyView;
}

@property(retain, nonatomic) DTSpaceCollectFileEmptyView *emptyView; // @synthesize emptyView=_emptyView;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
@property(copy, nonatomic) NSString *cid; // @synthesize cid=_cid;
@property(copy, nonatomic) NSString *token; // @synthesize token=_token;
@property(copy, nonatomic) NSArray *folders; // @synthesize folders=_folders;
- (void).cxx_destruct;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)gotoFolderList:(id)arg1;
- (void)setupConstraints;
- (void)openWebViewWithUrlString:(id)arg1 showRightBarButton:(_Bool)arg2;
- (void)createCollectFile;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

