//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@protocol DTBizConversation, DTBizMessage;

@protocol DTSpaceSwitcherProtocol <NSObject>
- (_Bool)needShowTipsForInviteOnlineDocMemberV1:(id <DTBizMessage>)arg1 fromConversation:(id <DTBizConversation>)arg2;
- (void)setShowTipsForInviteOnlineDocMember:(_Bool)arg1;
- (_Bool)needShowTipsForInviteOnlineDocMember:(id <DTBizMessage>)arg1 fromConversation:(id <DTBizConversation>)arg2;
- (_Bool)needShowTipsForUneditListV1:(id <DTBizMessage>)arg1 fromConversation:(id <DTBizConversation>)arg2;
- (void)setShowTipsForUneditList:(_Bool)arg1;
- (_Bool)needShowTipsForUneditList:(id <DTBizMessage>)arg1 fromConversation:(id <DTBizConversation>)arg2;
- (_Bool)hasClickedCollectFileInMeesageInput;
- (void)setClickedCollectFileInMeesageInput;
- (_Bool)isFileCopyOnSameSpaceEnable;
- (_Bool)isBatchSaveImagesEnabled;
- (_Bool)isFolderMessageEnabled;
- (_Bool)isOnlineEditEnable;
- (_Bool)isCollectFileEnabled;
@end

