//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "DTTableViewController.h"

@class DTAtInputManager, DTSpaceOnlineDocAddEditorPresenter, NSString;

@interface DTSpaceOnlineDocAddEditorViewController : DTTableViewController
{
    long long _spaceId;
    NSString *_dentryId;
    NSString *_conversationId;
    long long _messageId;
    CDUnknownBlockType _completeHandler;
    DTSpaceOnlineDocAddEditorPresenter *_presenter;
    DTAtInputManager *_atInputManager;
}

@property(retain, nonatomic) DTAtInputManager *atInputManager; // @synthesize atInputManager=_atInputManager;
@property(retain, nonatomic) DTSpaceOnlineDocAddEditorPresenter *presenter; // @synthesize presenter=_presenter;
@property(copy, nonatomic) CDUnknownBlockType completeHandler; // @synthesize completeHandler=_completeHandler;
@property(nonatomic) long long messageId; // @synthesize messageId=_messageId;
@property(copy, nonatomic) NSString *conversationId; // @synthesize conversationId=_conversationId;
@property(copy, nonatomic) NSString *dentryId; // @synthesize dentryId=_dentryId;
@property(nonatomic) long long spaceId; // @synthesize spaceId=_spaceId;
- (void).cxx_destruct;
- (void)addEditors;
- (void)processEditors:(id)arg1;
- (void)fetchEditors;
- (void)viewDidLoad;

@end

