//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SClient.h"

@interface DTSWCommonIService : SClient
{
}

+ (id)_appname__;
+ (id)_serviceKey__;
- (void)getShortcut:(id)arg1 etag:(id)arg2 callback:(id)arg3;
- (void)drawLottery:(id)arg1 callback:(id)arg2;
- (void)getQuitInfo:(id)arg1 uid:(id)arg2 callback:(id)arg3;
- (void)getHireInfo:(id)arg1 callback:(id)arg2;
- (void)getUserSummaryByOrg:(id)arg1 callback:(id)arg2;
- (void)getUserSummary:(id)arg1 callback:(id)arg2;

@end

