//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "DTLocalJSInjectProcessorDelegate-Protocol.h"

@class DTLocalJSInjectProcessor, DTWKWebViewRequestProcessor, LWHttpDNSInterceptor, LWURLCacheInterceptor, LWWebPProcessor, NSString;

@interface DTURLInterceptorInit : NSObject <DTLocalJSInjectProcessorDelegate>
{
    LWHttpDNSInterceptor *_httpDNSInterceptor;
    LWURLCacheInterceptor *_urlCacheInterceptor;
    LWWebPProcessor *_webpProcessor;
    DTLocalJSInjectProcessor *_jsInjectProcessor;
    DTWKWebViewRequestProcessor *_wkWebViewProcessor;
}

+ (id)sharedInstance;
@property(retain, nonatomic) DTWKWebViewRequestProcessor *wkWebViewProcessor; // @synthesize wkWebViewProcessor=_wkWebViewProcessor;
@property(retain, nonatomic) DTLocalJSInjectProcessor *jsInjectProcessor; // @synthesize jsInjectProcessor=_jsInjectProcessor;
@property(retain, nonatomic) LWWebPProcessor *webpProcessor; // @synthesize webpProcessor=_webpProcessor;
@property(retain, nonatomic) LWURLCacheInterceptor *urlCacheInterceptor; // @synthesize urlCacheInterceptor=_urlCacheInterceptor;
@property(retain, nonatomic) LWHttpDNSInterceptor *httpDNSInterceptor; // @synthesize httpDNSInterceptor=_httpDNSInterceptor;
- (void).cxx_destruct;
- (_Bool)shoulInjectForURL:(id)arg1;
- (id)js2InjectForProcessor:(id)arg1 URL:(id)arg2;
- (_Bool)isSupportDetailLog;
- (void)configFilteredHosts;
- (id)ipFromHttpDNSByHost:(id)arg1;
- (void)configURLInterceptors;
- (id)customProtocolClasses;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

