//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UICollectionViewCell.h>

@class CAShapeLayer, DTAvatarImageView, DTDisplayView, DTVideoConferenceMemberModel, UIImageView, UILabel;

@interface DTVideoConferenceCollectionCell : UICollectionViewCell
{
    _Bool _hideDisplayLabel;
    long long _index;
    DTVideoConferenceMemberModel *_currentMemberModel;
    DTDisplayView *_displayView;
    DTAvatarImageView *_avater;
    UILabel *_titleLabel;
    UILabel *_addTitleLabel;
    CAShapeLayer *_dashBorder;
    UILabel *_statusLabel;
    UILabel *_displayLabel;
    UIImageView *_audioOffImageView;
}

@property(retain, nonatomic) UIImageView *audioOffImageView; // @synthesize audioOffImageView=_audioOffImageView;
@property(retain, nonatomic) UILabel *displayLabel; // @synthesize displayLabel=_displayLabel;
@property(retain, nonatomic) UILabel *statusLabel; // @synthesize statusLabel=_statusLabel;
@property(retain, nonatomic) CAShapeLayer *dashBorder; // @synthesize dashBorder=_dashBorder;
@property(retain, nonatomic) UILabel *addTitleLabel; // @synthesize addTitleLabel=_addTitleLabel;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) DTAvatarImageView *avater; // @synthesize avater=_avater;
@property(retain, nonatomic) DTDisplayView *displayView; // @synthesize displayView=_displayView;
@property(copy, nonatomic) DTVideoConferenceMemberModel *currentMemberModel; // @synthesize currentMemberModel=_currentMemberModel;
@property(nonatomic) _Bool hideDisplayLabel; // @synthesize hideDisplayLabel=_hideDisplayLabel;
@property(nonatomic) long long index; // @synthesize index=_index;
- (void).cxx_destruct;
- (void)_hideDisplayLabel;
- (void)prepareForReuse;
- (void)layoutSubviews;
- (void)resetUI;
- (void)refreshShowTitle:(id)arg1;
- (void)stopAudio:(unsigned long long)arg1 member:(id)arg2;
- (void)stopVideo:(unsigned long long)arg1 member:(id)arg2;
- (void)stopProcess;
- (void)displayProcess:(struct _MSPicture)arg1 filp:(_Bool)arg2 isSpeaker:(_Bool)arg3 full:(_Bool)arg4 key:(id)arg5;
- (void)refreshAvatar:(id)arg1;
- (id)getShortName:(id)arg1 attributeDic:(id)arg2;
- (void)loadCompoment;
- (id)initWithFrame:(struct CGRect)arg1;

@end

