//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "UIViewControllerTransitioningDelegate-Protocol.h"

@class NSString, UIImage, UINavigationController, UIView;

@interface DTViewController : UIViewController <UIViewControllerTransitioningDelegate>
{
    _Bool _showNavBottomLine;
    _Bool _hideStatusBar;
    _Bool _animating;
    _Bool _needAnalytics;
    _Bool _bePresentedFullScreen;
    _Bool _disableSwipBack;
    UIImage *_navigationBackgroundImage;
    long long _statusBarStyle;
    UINavigationController *_innerNavController;
    UIView *_navigationBarBottomLine;
}

@property(retain, nonatomic) UIView *navigationBarBottomLine; // @synthesize navigationBarBottomLine=_navigationBarBottomLine;
@property(nonatomic) __weak UINavigationController *innerNavController; // @synthesize innerNavController=_innerNavController;
@property(nonatomic) _Bool disableSwipBack; // @synthesize disableSwipBack=_disableSwipBack;
@property(nonatomic) _Bool bePresentedFullScreen; // @synthesize bePresentedFullScreen=_bePresentedFullScreen;
@property(nonatomic) _Bool needAnalytics; // @synthesize needAnalytics=_needAnalytics;
@property(nonatomic) _Bool animating; // @synthesize animating=_animating;
@property(nonatomic) _Bool hideStatusBar; // @synthesize hideStatusBar=_hideStatusBar;
@property(nonatomic) long long statusBarStyle; // @synthesize statusBarStyle=_statusBarStyle;
@property(retain, nonatomic) UIImage *navigationBackgroundImage; // @synthesize navigationBackgroundImage=_navigationBackgroundImage;
- (void).cxx_destruct;
- (void)hideNavigationBarBottomLine;
- (void)showNavigationBarBottomLine;
- (void)fixNavigationBarBottomLineForiOS10;
- (_Bool)accessibilityPerformEscape;
- (void)onBackButtonTapped:(id)arg1;
- (id)backButtonTitle;
- (_Bool)shouldOverrideBackButton;
- (unsigned long long)supportedInterfaceOrientations;
- (_Bool)shouldAutorotate;
- (_Bool)isModal;
- (void)hidesNavigationBarBackground;
- (void)showsNavigationBarBackground;
- (void)didReceiveMemoryWarning;
- (void)restoreStatusBarStyle;
- (void)restoreNavigationBarStyle;
- (void)willMoveToParentViewController:(id)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)updateNavigationBackgroundImage;
- (void)checkBackBarItem;
- (void)viewWillAppear:(_Bool)arg1;
- (void)loadView;
- (void)dealloc;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)dt_jumpToGuideWithUrl:(id)arg1;
- (void)dt_configGuideTitleViewWithTitle:(id)arg1 guideURL:(id)arg2;
- (id)presentationControllerForPresentedViewController:(id)arg1 presentingViewController:(id)arg2 sourceViewController:(id)arg3;
- (id)animationControllerForDismissedController:(id)arg1;
- (id)animationControllerForPresentedController:(id)arg1 presentingController:(id)arg2 sourceController:(id)arg3;
- (id)presentationAnimator;
- (void)presentViewController:(id)arg1 animated:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

