//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "DTViewLuckyMoneyViewController.h"

@interface DTViewNormalLuckyMoneyViewController : DTViewLuckyMoneyViewController
{
}

- (id)convertFlowToFlowCellItem:(id)arg1;
- (void)fillData:(id)arg1;
- (void)fillHeaderData:(id)arg1;
- (_Bool)shouldAnimated;
- (id)titleForHeaderInLuckyMoneyFlow;
- (double)readjustTableFooterView;
- (double)readjustTableHeaderView;
- (id)tableFooterView;
- (id)tableHeaderView;
- (void)didReceiveMemoryWarning;

@end

