//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "Marshal.h"

@class NSString;

@interface DTVisitRecordRequestModel : Marshal
{
    NSString *_corpId;
    NSString *_ownerStaffId;
    NSString *_targetStaffId;
    NSString *_targetName;
}

@property(copy, nonatomic) NSString *targetName; // @synthesize targetName=_targetName;
@property(copy, nonatomic) NSString *targetStaffId; // @synthesize targetStaffId=_targetStaffId;
@property(copy, nonatomic) NSString *ownerStaffId; // @synthesize ownerStaffId=_ownerStaffId;
@property(copy, nonatomic) NSString *corpId; // @synthesize corpId=_corpId;
- (void).cxx_destruct;
- (id)filedsMeta__;
- (id)init;

@end

