//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "BLBaseEditorViewController.h"

#import "DTCMailAttachListViewDelegate-Protocol.h"
#import "DTMessagePopupAlbumMenuViewDelegate-Protocol.h"
#import "ELCImagePickerControllerDelegate-Protocol.h"

@class DTCMailAttachListView, DTWebEditorHeaderView, DTWebEditorToolBar, NSMutableArray, NSString, UIButton;

@interface DTWebEditorViewController : BLBaseEditorViewController <DTMessagePopupAlbumMenuViewDelegate, ELCImagePickerControllerDelegate, DTCMailAttachListViewDelegate>
{
    struct {
        unsigned int shouldWebViewBecomeFirstResponder:1;
        unsigned int isEditingSubjectField:1;
        unsigned int isEditingExtendTextField:1;
    } _flags;
    CDUnknownBlockType _finishBlock;
    CDUnknownBlockType _cancelBlock;
    DTWebEditorHeaderView *_headerView;
    DTWebEditorToolBar *_actionToolBar;
    DTCMailAttachListView *_mailAttachListView;
    UIButton *_toggleAttachmentButton;
    NSMutableArray *_attachmentList;
    NSMutableArray *_attachmentVOList;
}

@property(retain, nonatomic) NSMutableArray *attachmentVOList; // @synthesize attachmentVOList=_attachmentVOList;
@property(retain, nonatomic) NSMutableArray *attachmentList; // @synthesize attachmentList=_attachmentList;
@property(retain, nonatomic) UIButton *toggleAttachmentButton; // @synthesize toggleAttachmentButton=_toggleAttachmentButton;
@property(retain, nonatomic) DTCMailAttachListView *mailAttachListView; // @synthesize mailAttachListView=_mailAttachListView;
@property(retain, nonatomic) DTWebEditorToolBar *actionToolBar; // @synthesize actionToolBar=_actionToolBar;
@property(nonatomic) __weak DTWebEditorHeaderView *headerView; // @synthesize headerView=_headerView;
@property(copy, nonatomic) CDUnknownBlockType cancelBlock; // @synthesize cancelBlock=_cancelBlock;
@property(copy, nonatomic) CDUnknownBlockType finishBlock; // @synthesize finishBlock=_finishBlock;
- (void).cxx_destruct;
- (unsigned long long)supportedInterfaceOrientations;
- (_Bool)shouldAutorotate;
- (_Bool)isModal;
- (void)attachmentListView:(id)arg1 willDeleteElementAtIndex:(unsigned long long)arg2;
- (void)attachmentListView:(id)arg1 willPreviewElementAtIndex:(unsigned long long)arg2;
- (double)distanceBetweenElementsInAttachmentListView:(id)arg1;
- (double)elementRightPaddingForAttachmentListView:(id)arg1;
- (double)elementLeftPaddingForAttachmentListView:(id)arg1;
- (double)elementHeightForAttachmentListView:(id)arg1;
- (double)elementTopPaddingForAttachmentListView:(id)arg1;
- (double)elementWidthForAttachmentListView:(id)arg1;
- (id)attachmentListView:(id)arg1 elementViewAtIndex:(unsigned long long)arg2 withFrame:(struct CGRect)arg3;
- (void)keyboardDidShowAtOffset:(double)arg1;
- (void)handleWillChangeKeyboardFrame:(id)arg1;
- (void)handleWillHideKeyboard:(id)arg1;
- (void)handleWillShowKeyboard:(id)arg1;
- (id)urlsWithFileResults:(id)arg1;
- (void)checkAndUploadImages:(id)arg1 complete:(CDUnknownBlockType)arg2;
- (void)processAttachmentsWithFinishBlock:(CDUnknownBlockType)arg1;
- (void)onEditorComplete;
- (_Bool)checkHtmlValidity:(id)arg1;
- (id)getCurrentHtmlContent;
- (void)addAttachmentsWithDentrys:(id)arg1;
- (void)addAttachmentsWithImages:(id)arg1;
- (void)addAttachmentsWithAssets:(id)arg1;
- (void)rebuildAttachmentButtonText;
- (void)onToggleAttachmnentClicked:(id)arg1;
- (void)adjustSubviewsToFit;
- (void)elcImagePickerControllerDidCancel:(id)arg1;
- (void)elcImagePickerController:(id)arg1 didFinishPickingMediaWithInfo:(id)arg2;
- (void)loadItem:(id)arg1 withSuccessBlock:(CDUnknownBlockType)arg2 andFailureBlock:(CDUnknownBlockType)arg3;
- (void)handleSelectedPhotos:(id)arg1 isOriginal:(_Bool)arg2;
- (void)didCancelOnPopupAlbumMenuView:(id)arg1;
- (void)didOpenedAlbumOnPopupAlbumMenuView:(id)arg1;
- (void)didOpenedCameraOnPopupAlbumMenuView:(id)arg1;
- (void)didSelectedPhotosInAlbumWithViewModels:(id)arg1 isOriginal:(_Bool)arg2;
- (void)showPopupAlbumMenuView;
- (void)insertImageFromMenuItem:(id)arg1;
- (void)removeMenuItems;
- (void)addMenuItems;
- (void)openCSpacePickerView;
- (void)editorObtainKeyboard;
- (_Bool)textFieldShouldReturn:(id)arg1;
- (_Bool)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (void)textFieldDidEndEditing:(id)arg1;
- (_Bool)checkWebViewResponder;
- (_Bool)textFieldShouldEndEditing:(id)arg1;
- (void)textFieldDidBeginEditing:(id)arg1;
- (_Bool)textFieldShouldBeginEditing:(id)arg1;
- (void)webEditorToolBar:(id)arg1 didClickAtIndex:(long long)arg2;
- (id)buttonInfoDictForIndex:(long long)arg1;
- (long long)numberOfToolBarItems;
- (void)reloadAttachmentView;
- (void)dismissAndQuit;
- (void)onLeftButtonAction:(id)arg1;
- (void)onRightButtonAction:(id)arg1;
- (void)setupBarButtonItems;
- (void)initAttachmentListView;
- (void)initBottomView;
- (void)initWebView;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

