//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class DTWorkCalendarCellModel, UIImageView;

@interface DTWorkCalendarCell : UITableViewCell
{
    long long _cellType;
    DTWorkCalendarCellModel *_cellModel;
    UIImageView *_topLine;
    UIImageView *_bottomLine;
    long long _cellSection;
    long long _cellRow;
    long long _countOfRowsInSection;
    long long _countOfSection;
    double _cellSeperatorLeftSpace;
}

+ (id)cellIdentifier;
+ (double)cellHeightForCellModel:(id)arg1 cellWidth:(double)arg2;
+ (Class)cellClassWithStyle:(long long)arg1;
@property(nonatomic) double cellSeperatorLeftSpace; // @synthesize cellSeperatorLeftSpace=_cellSeperatorLeftSpace;
@property(nonatomic) long long countOfSection; // @synthesize countOfSection=_countOfSection;
@property(nonatomic) long long countOfRowsInSection; // @synthesize countOfRowsInSection=_countOfRowsInSection;
@property(nonatomic) long long cellRow; // @synthesize cellRow=_cellRow;
@property(nonatomic) long long cellSection; // @synthesize cellSection=_cellSection;
@property(readonly, nonatomic) DTWorkCalendarCellModel *cellModel; // @synthesize cellModel=_cellModel;
- (void).cxx_destruct;
- (void)hiddenBottomSeparator;
- (void)hiddenTopSeparator;
- (void)layoutSeparator;
- (void)setCellIndexPath:(id)arg1 countOfRowsInSection:(long long)arg2 countOfSection:(long long)arg3;
- (void)setCellModel:(id)arg1;
- (id)initWithCellStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

