//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "DTWorkCalendarCellModel.h"

@class NSString;

@interface DTWorkCalendarMergeTextCellModel : DTWorkCalendarCellModel
{
    NSString *_title;
    NSString *_highLightColor;
    NSString *_highLightText;
    NSString *_unitText;
}

@property(copy, nonatomic) NSString *unitText; // @synthesize unitText=_unitText;
@property(copy, nonatomic) NSString *highLightText; // @synthesize highLightText=_highLightText;
@property(copy, nonatomic) NSString *highLightColor; // @synthesize highLightColor=_highLightColor;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
- (void).cxx_destruct;
- (void)paddingDataWithIDLModel:(id)arg1;

@end

