//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class DTWorkItemModel, NSArray, NSString;

@interface DTWorkItemConvertModel : NSObject
{
    DTWorkItemModel *_model;
    long long _itemModelId;
    long long _orgId;
    long long _createAt;
    NSString *_icon;
    NSString *_title;
    NSArray *_formItemList;
    NSString *_url;
    NSArray *_actions;
}

+ (id)convertWithWorkItemModel:(id)arg1;
+ (id)actionConvertModelList:(id)arg1;
@property(copy, nonatomic) NSArray *actions; // @synthesize actions=_actions;
@property(copy, nonatomic) NSString *url; // @synthesize url=_url;
@property(retain, nonatomic) NSArray *formItemList; // @synthesize formItemList=_formItemList;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(copy, nonatomic) NSString *icon; // @synthesize icon=_icon;
@property(nonatomic) long long createAt; // @synthesize createAt=_createAt;
@property(nonatomic) long long orgId; // @synthesize orgId=_orgId;
@property(nonatomic) long long itemModelId; // @synthesize itemModelId=_itemModelId;
@property(retain, nonatomic) DTWorkItemModel *model; // @synthesize model=_model;
- (void).cxx_destruct;

@end

