//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface DTWorkAPIServices : NSObject
{
}

+ (void)checkCustomWorkTabWithParams:(id)arg1 oaTitle:(id)arg2 oaUrl:(id)arg3 suiteKey:(id)arg4 redirectUri:(id)arg5 state:(id)arg6 nonceStr:(id)arg7 timestamp:(id)arg8 sign:(id)arg9 successBlock:(CDUnknownBlockType)arg10 failureBlock:(CDUnknownBlockType)arg11;
+ (void)setCustomWorkTabWithOrgId:(long long)arg1 oaTitle:(id)arg2 oaUrl:(id)arg3 successBlock:(CDUnknownBlockType)arg4 failureBlock:(CDUnknownBlockType)arg5;
+ (void)getUserNodesFromCurDeptOneDayWithOrgId:(long long)arg1 deptId:(long long)arg2 dateVar:(long long)arg3 appId:(id)arg4 subAppId:(id)arg5 itemType:(long long)arg6 start:(long long)arg7 size:(long long)arg8 containSubDepts:(_Bool)arg9 successBlock:(CDUnknownBlockType)arg10 failureBlock:(CDUnknownBlockType)arg11;
+ (void)getNodesFromDirectDeptOneDayWitOrgId:(long long)arg1 deptId:(long long)arg2 dateVar:(long long)arg3 appId:(id)arg4 subAppId:(id)arg5 itemType:(long long)arg6 start:(long long)arg7 size:(long long)arg8 successBlock:(CDUnknownBlockType)arg9 failureBlock:(CDUnknownBlockType)arg10;
+ (void)getPersonalAttendanceDatailWithOrgId:(long long)arg1 staffId:(id)arg2 appId:(id)arg3 subAppId:(id)arg4 dateVar:(long long)arg5 successBlock:(CDUnknownBlockType)arg6 failureBlock:(CDUnknownBlockType)arg7;
+ (void)managerCalDayFullInfosWithDateVar:(long long)arg1 successBlock:(CDUnknownBlockType)arg2 failureBlock:(CDUnknownBlockType)arg3;
+ (void)cancelSubscribeOrgEmpMessagePushWithOrgId:(long long)arg1 successBlock:(CDUnknownBlockType)arg2 failureBlock:(CDUnknownBlockType)arg3;
+ (void)subscribeOrgEmpMessagePushWithOrgId:(long long)arg1 successBlock:(CDUnknownBlockType)arg2 failureBlock:(CDUnknownBlockType)arg3;
+ (void)getManageCalSettingWithOrgId:(long long)arg1 successBlock:(CDUnknownBlockType)arg2 failureBlock:(CDUnknownBlockType)arg3;
+ (void)updateOrgMicroAppScopes:(long long)arg1 userVisibleScopes:(id)arg2 deptVisibleScopes:(id)arg3 successBlock:(CDUnknownBlockType)arg4 failureBlock:(CDUnknownBlockType)arg5;
+ (void)queryUserAuthorityWithOrgId:(long long)arg1 appId:(long long)arg2 successBlock:(CDUnknownBlockType)arg3 failureBlock:(CDUnknownBlockType)arg4;
+ (void)oAMessageActionACK:(long long)arg1 action:(id)arg2 successBlock:(CDUnknownBlockType)arg3 failedBlock:(CDUnknownBlockType)arg4;
+ (void)manageCalendarOrgDataWithOrgId:(long long)arg1 dateVar:(long long)arg2 successBlock:(CDUnknownBlockType)arg3 failureBlock:(CDUnknownBlockType)arg4;
+ (void)dayManagerCalDetailsWithOrgId:(long long)arg1 deptId:(long long)arg2 dateVar:(long long)arg3 appId:(id)arg4 subAppId:(id)arg5 itemType:(long long)arg6 start:(long long)arg7 size:(long long)arg8 containSubDepts:(_Bool)arg9 successBlock:(CDUnknownBlockType)arg10 failureBlock:(CDUnknownBlockType)arg11;
+ (void)daySubDeptManagerCalStatisticsWithOrgId:(long long)arg1 deptId:(long long)arg2 dateVar:(long long)arg3 appId:(id)arg4 subAppId:(id)arg5 itemType:(long long)arg6 start:(long long)arg7 size:(long long)arg8 successBlock:(CDUnknownBlockType)arg9 failureBlock:(CDUnknownBlockType)arg10;
+ (void)managerCalDayFullInfosWithOrgId:(long long)arg1 dateVar:(long long)arg2 deptId:(long long)arg3 successBlock:(CDUnknownBlockType)arg4 failureBlock:(CDUnknownBlockType)arg5;
+ (void)manageCalenderFullInfosWithOrgId:(long long)arg1 startTime:(long long)arg2 endTime:(long long)arg3 currentTime:(long long)arg4 deptId:(long long)arg5 successBlock:(CDUnknownBlockType)arg6 failureBlock:(CDUnknownBlockType)arg7;

@end

