//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "DTWorkCalendarCellModel.h"

@class NSMutableArray, NSString;

@interface DTWorkCalendarFormCellModel : DTWorkCalendarCellModel
{
    NSString *_title;
    NSMutableArray *_formList;
}

@property(retain, nonatomic) NSMutableArray *formList; // @synthesize formList=_formList;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
- (void).cxx_destruct;
- (void)paddingDataWithIDLModel:(id)arg1;

@end

