//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIActivityIndicatorView;
@protocol EGORefreshTableHeaderDelegate;

@interface EGORefreshTableHeaderView : UIView
{
    int _state;
    UIActivityIndicatorView *_activityView;
    _Bool _endDragging;
    struct UIEdgeInsets defaultScrollEdgeInsets;
    id <EGORefreshTableHeaderDelegate> _delegate;
    unsigned long long _style;
}

@property(nonatomic) unsigned long long style; // @synthesize style=_style;
@property(nonatomic) __weak id <EGORefreshTableHeaderDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)dealloc;
- (void)removeFromSuperviewWithInsetsBack:(id)arg1;
- (void)egoRefreshScrollViewRevertNormalState:(id)arg1;
- (void)egoRefreshScrollViewDataSourceDidFinishedLoading:(id)arg1;
- (void)egoRefreshScrollViewDataSourceDidFinishedLoading:(id)arg1 insetsNeedBack:(_Bool)arg2 animation:(_Bool)arg3;
- (void)egoRefreshScrollViewDidEndDragging:(id)arg1;
- (void)egoRefreshScrollViewDidScroll:(id)arg1;
- (void)egoRefreshScrollViewWillScroll:(id)arg1;
- (void)setState:(int)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

