//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "ELCAssetSelectionDelegate-Protocol.h"

@class NSString, UIButton, UIImageView, UILabel;
@protocol ELCAssetOriginalSendViewDelegate;

@interface ELCAssetOriginalSendView : UIView <ELCAssetSelectionDelegate>
{
    UIButton *_selectIconButton;
    UILabel *_originalLabel;
    UIButton *_sendButton;
    UIImageView *_countImageView;
    UILabel *_countLabel;
    id <ELCAssetOriginalSendViewDelegate> _delegate;
    UIButton *_markerButton;
    unsigned long long _lastCount;
    long long _style;
}

@property(nonatomic) long long style; // @synthesize style=_style;
@property(nonatomic) unsigned long long lastCount; // @synthesize lastCount=_lastCount;
@property(retain, nonatomic) UIButton *markerButton; // @synthesize markerButton=_markerButton;
@property(nonatomic) __weak id <ELCAssetOriginalSendViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) UILabel *countLabel; // @synthesize countLabel=_countLabel;
@property(retain, nonatomic) UIImageView *countImageView; // @synthesize countImageView=_countImageView;
@property(retain, nonatomic) UIButton *sendButton; // @synthesize sendButton=_sendButton;
@property(retain, nonatomic) UILabel *originalLabel; // @synthesize originalLabel=_originalLabel;
@property(retain, nonatomic) UIButton *selectIconButton; // @synthesize selectIconButton=_selectIconButton;
- (void).cxx_destruct;
- (void)send;
- (void)selectOriginal;
- (void)markBtnClick:(id)arg1;
- (void)setOriginalImageTotalSize:(long long)arg1 selectCount:(unsigned long long)arg2;
- (void)showCountLabelWithCount:(unsigned long long)arg1;
- (id)initWithFrame:(struct CGRect)arg1 supportOriginalSelect:(_Bool)arg2 style:(long long)arg3 supportGriffiti:(_Bool)arg4;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

