//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIScrollView.h>

@class JTCalendar, NSDate, NSMutableArray;

@interface JTCalendarContentView : UIScrollView
{
    NSMutableArray *monthsViews;
    JTCalendar *_calendarManager;
    NSDate *_currentDate;
}

@property(retain, nonatomic) NSDate *currentDate; // @synthesize currentDate=_currentDate;
@property(nonatomic) __weak JTCalendar *calendarManager; // @synthesize calendarManager=_calendarManager;
- (void).cxx_destruct;
- (void)reloadAppearance;
- (void)reloadData;
- (id)beginningOfWeek:(id)arg1;
- (id)beginningOfMonth:(id)arg1;
- (void)configureConstraintsForSubviews;
- (void)layoutSubviews;
- (void)commonInit;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

