//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@protocol LAPluginDelegate;

@interface LAPluginBase : NSObject
{
    id <LAPluginDelegate> _delegate;
}

+ (id)pluginExactName;
+ (void)enqueue:(id)arg1 interval:(double)arg2 withAction:(CDUnknownBlockType)arg3;
+ (void)enqueue:(id)arg1 withAction:(CDUnknownBlockType)arg2;
+ (_Bool)verifyCredibleDomian:(id)arg1 pluginName:(id)arg2 methodName:(id)arg3;
+ (_Bool)verifyCredibleLAWebView:(id)arg1 pluginName:(id)arg2 methodName:(id)arg3;
+ (_Bool)verifyCredibleUIWebView:(id)arg1 pluginName:(id)arg2 methodName:(id)arg3;
@property(nonatomic) __weak id <LAPluginDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)disposePlugin;
- (void)pluginInitialize;
- (void)dealloc;
- (id)init;

@end

