//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSMutableDictionary;

@interface LIMModelBackTrackDispatch : NSObject
{
    NSMutableDictionary *dispatchMap;
    int lock;
}

+ (id)shareModelBackTrackDispatch;
- (void).cxx_destruct;
- (void)dealloc;
- (void)removeModelBackTrack:(id)arg1 observer:(id)arg2;
- (_Bool)containModelBackTrack:(id)arg1;
- (id)getModelBackTrack:(id)arg1 observer:(id)arg2;
- (void)removeBackTracksWithModel:(id)arg1;
- (void)addModelBackTrack:(id)arg1;
- (void)dispatch:(id)arg1 change:(id)arg2;
- (id)init;

@end

