//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSString;
@protocol LVCommentObserver;

@protocol LVCommentProtocol <NSObject>
- (void)removeCommentObserver:(id <LVCommentObserver>)arg1 liveUuid:(NSString *)arg2;
- (void)addCommentObserver:(id <LVCommentObserver>)arg1 liveUuid:(NSString *)arg2;
- (void)removeCommentObserver:(id <LVCommentObserver>)arg1 cid:(NSString *)arg2;
- (void)addCommentObserver:(id <LVCommentObserver>)arg1 cid:(NSString *)arg2;
- (void)requestCommentWithPageSize:(int)arg1 cid:(NSString *)arg2 completion:(void (^)(NSArray *, NSError *))arg3;
@end

