//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSNumber, NSString;

@protocol LVLiveStatisticsProtocol <NSObject>
@property(retain, nonatomic) NSNumber *recordSeenLevel;
@property(retain, nonatomic) NSNumber *unviewedCount;
@property(retain, nonatomic) NSNumber *viewerCount;
@property(retain, nonatomic) NSNumber *messageCount;
@property(retain, nonatomic) NSNumber *praiseCount;
@property(retain, nonatomic) NSNumber *onlineCount;
@property(copy, nonatomic) NSString *title;
@property(copy, nonatomic) NSString *coverUrl;
@property(retain, nonatomic) NSNumber *uv;
@property(retain, nonatomic) NSNumber *pv;
@property(retain, nonatomic) NSNumber *duration;
@property(retain, nonatomic) NSNumber *memberCount;
@end

