//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class DTMagicEmotionModel, LWVMEmotion;

@interface LWEmotionItem : NSObject
{
    _Bool _useCustomContentMode;
    _Bool _disableShortCut;
    DTMagicEmotionModel *_magicModel;
    LWVMEmotion *_emojiModel;
    long long _contentMode;
}

+ (id)buildEmotionItemWithMagicModel:(id)arg1;
+ (id)buildEmotionItemWithEmojiModel:(id)arg1;
@property(nonatomic) _Bool disableShortCut; // @synthesize disableShortCut=_disableShortCut;
@property(nonatomic) _Bool useCustomContentMode; // @synthesize useCustomContentMode=_useCustomContentMode;
@property(nonatomic) long long contentMode; // @synthesize contentMode=_contentMode;
@property(retain, nonatomic) LWVMEmotion *emojiModel; // @synthesize emojiModel=_emojiModel;
@property(retain, nonatomic) DTMagicEmotionModel *magicModel; // @synthesize magicModel=_magicModel;
- (void).cxx_destruct;

@end

