//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "LWPServerLocator-Protocol.h"

@class LWPHistoryServerManager, LWPQueue, LWPServerItem, LWPServerV3NetInfo, LWPV3ServerManager, NSDate, NSString, NSURL;

@interface LWPAladdinV3ServerLocator : NSObject <LWPServerLocator>
{
    LWPV3ServerManager *_serverManager;
    _Bool _isUpdating;
    _Bool _isSupportLWP;
    int _countOfLastConnectedServer;
    LWPQueue *_workQueue;
    NSURL *_vipBaseServer;
    NSURL *_vipServer;
    NSURL *_lastOriVipServer;
    LWPServerItem *_lastSelectServerItem;
    LWPServerV3NetInfo *_currentNetInfo;
    double _timeOfLastConnectedServer;
    NSDate *_lastSuccUpdate;
    NSString *_urlOfLastConnectedServer;
    LWPHistoryServerManager *_historyManager;
}

@property(retain, nonatomic) LWPHistoryServerManager *historyManager; // @synthesize historyManager=_historyManager;
@property(nonatomic) _Bool isSupportLWP; // @synthesize isSupportLWP=_isSupportLWP;
@property(nonatomic) int countOfLastConnectedServer; // @synthesize countOfLastConnectedServer=_countOfLastConnectedServer;
@property(copy, nonatomic) NSString *urlOfLastConnectedServer; // @synthesize urlOfLastConnectedServer=_urlOfLastConnectedServer;
@property(retain, nonatomic) NSDate *lastSuccUpdate; // @synthesize lastSuccUpdate=_lastSuccUpdate;
@property(nonatomic) double timeOfLastConnectedServer; // @synthesize timeOfLastConnectedServer=_timeOfLastConnectedServer;
@property(retain, nonatomic) LWPServerV3NetInfo *currentNetInfo; // @synthesize currentNetInfo=_currentNetInfo;
@property(nonatomic) _Bool isUpdating; // @synthesize isUpdating=_isUpdating;
@property(retain, nonatomic) LWPV3ServerManager *serverManager; // @synthesize serverManager=_serverManager;
@property(retain, nonatomic) LWPServerItem *lastSelectServerItem; // @synthesize lastSelectServerItem=_lastSelectServerItem;
@property(retain, nonatomic) NSURL *lastOriVipServer; // @synthesize lastOriVipServer=_lastOriVipServer;
@property(retain, nonatomic) NSURL *vipServer; // @synthesize vipServer=_vipServer;
@property(copy, nonatomic) NSURL *vipBaseServer; // @synthesize vipBaseServer=_vipBaseServer;
@property(retain, nonatomic) LWPQueue *workQueue; // @synthesize workQueue=_workQueue;
- (void).cxx_destruct;
- (void)resetVipServerUrl;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)removeObserveVipServerChange;
- (void)addObserveVipServerChange;
- (id)fetchServers:(id)arg1;
- (_Bool)checkBodyDataVaild:(id)arg1 sign:(id)arg2;
- (_Bool)checkBodyDataVaild:(id)arg1 response:(id)arg2 error:(id)arg3;
- (_Bool)processSuitsNode:(id)arg1 updateCount:(long long *)arg2;
- (void)lwpFetchServers:(id)arg1 finishBlock:(CDUnknownBlockType)arg2;
- (void)_updateServerList:(_Bool)arg1 delCache:(_Bool)arg2 serverData:(id)arg3;
- (void)_updateServerList:(_Bool)arg1 delCache:(_Bool)arg2;
- (void)updateServerListWithData:(id)arg1;
- (_Bool)isUpdateTooFrequently;
- (_Bool)isTimeToUpdate;
- (id)specifyShortServer;
- (id)specifyServer;
- (id)defaultServerURL;
- (id)getShortServerUrl;
- (id)getServerUrl;
- (id)itemWithUrl:(id)arg1 isShort:(_Bool)arg2;
- (void)removeItem:(id)arg1 isShort:(_Bool)arg2;
- (void)disconnectCheckForUrl:(id)arg1 isConnectedFailed:(_Bool)arg2 isShort:(_Bool)arg3;
- (void)allMasterServerUrls:(id *)arg1 slaveServerUrls:(id *)arg2 historyMasterUrls:(id *)arg3 historySlaveUrls:(id *)arg4;
- (id)allServerUrls;
- (id)lwpLocatorGetSecondServerUrl;
- (id)lwpLocatorGetFirstServerUrl;
- (void)reorderServerUrl:(id)arg1;
- (void)updateServerList:(id)arg1;
- (void)asyncUpdateServerList:(_Bool)arg1;
- (void)clearServerCache;
- (void)lwpLocatorServerConnectFail:(id)arg1 isShort:(_Bool)arg2;
- (void)lwpLocatorServerConnected:(id)arg1 isShort:(_Bool)arg2;
- (void)lwpLocatorServerAuthed:(id)arg1 isShort:(_Bool)arg2;
- (void)lwpLocatorServerBroken:(id)arg1 isShort:(_Bool)arg2;
- (id)lwpLocatorGetShortServerUrl;
- (id)lwpLocatorGetServerUrl;
@property(readonly, copy) NSString *description;
- (void)dealloc;
- (id)initWithQueue:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

