//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSMutableDictionary;
@protocol OS_dispatch_queue;

@interface LWPFlowControlCenter : NSObject
{
    NSObject<OS_dispatch_queue> *_defaultTimerQueue;
    CDUnknownBlockType _triggerFlowCheckBlock;
    NSMutableDictionary *_flowContrlMap;
    NSMutableDictionary *_flowTimerMap;
}

@property(retain, nonatomic) NSMutableDictionary *flowTimerMap; // @synthesize flowTimerMap=_flowTimerMap;
@property(retain, nonatomic) NSMutableDictionary *flowContrlMap; // @synthesize flowContrlMap=_flowContrlMap;
@property(copy, nonatomic) CDUnknownBlockType triggerFlowCheckBlock; // @synthesize triggerFlowCheckBlock=_triggerFlowCheckBlock;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *defaultTimerQueue; // @synthesize defaultTimerQueue=_defaultTimerQueue;
- (void).cxx_destruct;
- (id)flowControllerForType:(id)arg1;
- (void)updateFlowTimer:(id)arg1 flowType:(id)arg2;
- (id)flowTimerForType:(id)arg1;
- (void)stopFlowCheck:(id)arg1;
- (void)_startFlowTimer:(unsigned long long)arg1 flowType:(id)arg2;
- (_Bool)isLimit:(id)arg1;
- (_Bool)tryAcquire:(double)arg1 flowType:(id)arg2 macrosToWait:(unsigned long long *)arg3;
- (void)updateFlowControl:(id)arg1 flowRate:(double)arg2;
- (_Bool)addFlowControl:(id)arg1 flowRate:(double)arg2 error:(id *)arg3;
- (id)init;

@end

