//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class LWPFileResultCaches, LWPFileUploadTaskManager, NSMutableArray, NSMutableDictionary;

@interface LWPFileUploadService : NSObject
{
    _Bool _usingFileResultCache;
    _Bool _usingDingPanFileResultCache;
    int _lock;
    NSMutableArray *_uploaderQueue;
    NSMutableDictionary *_uploadTaskMap;
    LWPFileUploadTaskManager *_taskManager;
    LWPFileResultCaches *_fileResultCaches;
}

+ (id)getUploadInfoFile:(id)arg1 identifier:(id)arg2;
+ (id)getUploadInfoPathWithFileKey:(id)arg1;
+ (id)getLWPFileUploadInfoFolder;
+ (id)getCacheKeyForFile:(id)arg1 identifier:(id)arg2;
+ (id)getUploadInfo:(id)arg1 identifier:(id)arg2;
+ (void)saveUploadInfo:(id)arg1 forFile:(id)arg2 error:(id)arg3;
+ (_Bool)shouldSaveUploadInfo:(id)arg1 error:(id)arg2;
+ (void)removeUploadInfo:(id)arg1 forFile:(id)arg2;
+ (id)sharedInstance;
@property(retain, nonatomic) LWPFileResultCaches *fileResultCaches; // @synthesize fileResultCaches=_fileResultCaches;
@property(retain, nonatomic) LWPFileUploadTaskManager *taskManager; // @synthesize taskManager=_taskManager;
@property(retain, nonatomic) NSMutableDictionary *uploadTaskMap; // @synthesize uploadTaskMap=_uploadTaskMap;
@property(retain, nonatomic) NSMutableArray *uploaderQueue; // @synthesize uploaderQueue=_uploaderQueue;
- (void).cxx_destruct;
- (void)clearFileResultCache;
- (_Bool)usingFileResultCacheWithFileAttr:(id)arg1;
- (void)disableDingPanFileResultCache;
- (void)enableDingPanFileResultCache;
- (void)disableFileResultCache;
- (void)enableFileResultCache;
- (void)dispatchFailureForFile:(id)arg1 uploadInfo:(id)arg2 task:(id)arg3 error:(id)arg4;
- (void)dispatchProgressForFile:(id)arg1 totalSize:(unsigned long long)arg2 offsetSize:(unsigned long long)arg3 task:(id)arg4 uploadInfo:(id)arg5;
- (void)dispatchSuccessForFile:(id)arg1 originUrl:(id)arg2 thumbUrl:(id)arg3 task:(id)arg4 uploadInfo:(id)arg5;
- (void)dispatchStartForFile:(id)arg1 task:(id)arg2 uploadInfo:(id)arg3;
- (id)retriveUploadItems:(id)arg1 withTask:(id)arg2 deleteFlag:(_Bool)arg3;
- (id)queryUploaderWithFile:(id)arg1 identifier:(id)arg2;
- (void)commitAndCloseStream:(id)arg1;
- (void)clearCallbackAndCloseStream:(id)arg1;
- (id)openStreamWithFilePath:(id)arg1 fileAttr:(id)arg2;
- (id)taskWithFileAttr:(id)arg1 uploadInfo:(id)arg2;
- (void)dequeueTask:(id)arg1;
- (void)run;
- (void)enqueueTask:(id)arg1;
- (void)finishWithUploadResult:(id)arg1 error:(id)arg2 startBlock:(CDUnknownBlockType)arg3 successBlock:(CDUnknownBlockType)arg4 progressBlock:(CDUnknownBlockType)arg5 failureBlock:(CDUnknownBlockType)arg6;
- (void)removeUploader:(id)arg1;
- (void)addUploadTask:(id)arg1;
- (id)uploadFileWithFileAttr:(id)arg1 start:(CDUnknownBlockType)arg2 success:(CDUnknownBlockType)arg3 onProgress:(CDUnknownBlockType)arg4 failure:(CDUnknownBlockType)arg5;
- (id)init;

@end

