//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSString;
@protocol OS_dispatch_queue;

@interface LWPQueue : NSObject
{
    _Bool _isMainQueue;
    NSObject<OS_dispatch_queue> *_queue;
    const char *_name;
    _Bool _enableTProfile;
    NSString *_ocName;
}

+ (id)mainQueue;
@property(copy, nonatomic) NSString *ocName; // @synthesize ocName=_ocName;
@property(nonatomic) _Bool enableTProfile; // @synthesize enableTProfile=_enableTProfile;
- (void).cxx_destruct;
- (_Bool)_isSameQueue;
- (void)dispatchOnQueue:(CDUnknownBlockType)arg1 synchronous:(_Bool)arg2 runIfSameQueue:(_Bool)arg3;
- (id)description;
- (void)dispatchOnQueue:(CDUnknownBlockType)arg1 synchronous:(_Bool)arg2;
- (void)dispatchOnQueue:(CDUnknownBlockType)arg1 runIfSameQueue:(_Bool)arg2;
- (void)dispatchOnQueue:(CDUnknownBlockType)arg1;
- (_Bool)isCurrentQueue;
- (id)nativeQueue;
- (const char *)name;
- (void)dealloc;
- (id)initWithName:(const char *)arg1;
- (id)initWithOCName:(id)arg1;

@end

