//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class LWPClientTMD, NSMutableDictionary;
@protocol OS_dispatch_queue;

@interface LWPTransactionService : NSObject
{
    NSMutableDictionary *_transactionPool;
    NSMutableDictionary *_mergeReqLinkerMap;
    NSObject<OS_dispatch_queue> *_callbackQueue;
    CDUnknownBlockType _sendRequestBlock;
    CDUnknownBlockType _sendResponseBlock;
    CDUnknownBlockType _reqDestoryCallback;
    CDUnknownBlockType _isFlowLimitBlock;
    LWPClientTMD *_clientTMD;
}

@property(retain, nonatomic) LWPClientTMD *clientTMD; // @synthesize clientTMD=_clientTMD;
@property(copy, nonatomic) CDUnknownBlockType isFlowLimitBlock; // @synthesize isFlowLimitBlock=_isFlowLimitBlock;
@property(copy, nonatomic) CDUnknownBlockType reqDestoryCallback; // @synthesize reqDestoryCallback=_reqDestoryCallback;
@property(copy, nonatomic) CDUnknownBlockType sendResponseBlock; // @synthesize sendResponseBlock=_sendResponseBlock;
@property(copy, nonatomic) CDUnknownBlockType sendRequestBlock; // @synthesize sendRequestBlock=_sendRequestBlock;
@property(nonatomic) NSObject<OS_dispatch_queue> *callbackQueue; // @synthesize callbackQueue=_callbackQueue;
- (void).cxx_destruct;
- (void)filterAfterRequest:(id)arg1 response:(id)arg2 error:(id)arg3;
- (_Bool)isTriggerTMD:(id)arg1;
- (_Bool)filterBeforeRequest:(id)arg1;
- (id)transactionWithMID:(id)arg1;
- (void)clear;
- (void)cleanPending:(id)arg1 mode:(unsigned long long)arg2;
- (void)flushPending:(id)arg1 mode:(unsigned long long)arg2 force:(_Bool)arg3;
- (void)sendResponseToWired:(id)arg1 response:(id)arg2;
- (void)recvResponseFromWired:(id)arg1;
- (_Bool)cancelTransactionWithMid:(id)arg1;
- (_Bool)cancelTransaction:(id)arg1;
- (void)destory:(id)arg1 withError:(id)arg2 withResponse:(id)arg3;
- (void)recvPartOfRequest:(id)arg1 withResponse:(id)arg2;
- (void)destoryV2:(id)arg1 withError:(id)arg2 withResponse:(id)arg3;
- (id)mergeKeyOfRequest:(id)arg1;
- (_Bool)isMergeRequest:(id)arg1;
- (void)enqueue:(id)arg1;
- (void)dump;
- (_Bool)isMessageInQueue:(id)arg1;
- (id)transactionProcess;
- (id)init;

@end

