//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "MADataSource-Protocol.h"

@class NSString;

@interface MAAbstractMercatorDataSource : NSObject <MADataSource>
{
    _Bool _cacheable;
    _Bool _opaque;
    float _minZoom;
    float _maxZoom;
}

@property(nonatomic, getter=isOpaque) _Bool opaque; // @synthesize opaque=_opaque;
@property(nonatomic, getter=isCacheable) _Bool cacheable; // @synthesize cacheable=_cacheable;
@property(nonatomic) float maxZoom; // @synthesize maxZoom=_maxZoom;
@property(nonatomic) float minZoom; // @synthesize minZoom=_minZoom;
- (void)didReceiveMemoryWarning;
- (void)cancelAllDownloads;
- (_Bool)tileSourceHasTile:(CDStruct_c8e85508)arg1;
- (id)imageForTile:(CDStruct_c8e85508)arg1 inCache:(id)arg2;
@property(readonly, nonatomic) NSString *sourceDescription;
@property(readonly, nonatomic) NSString *uniqueCacheKey;
- (id)uniqueCacheKeyForTile:(CDStruct_c8e85508)arg1;
@property(readonly, nonatomic) struct MACoordinateBounds latitudeLongitudeBoundingBox;
@property(readonly, nonatomic) unsigned long long tileSideLength;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

