//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "DTRpcInterceptor-Protocol.h"

@class NSArray, NSMutableArray, NSString;
@protocol MYBankLogin;

@interface MYBankRPCManager : NSObject <DTRpcInterceptor>
{
    _Bool _hasLogined;
    _Bool _isLogining;
    id <MYBankLogin> _loginMgr;
    NSMutableArray *_pendingRPCCalls;
    NSString *_productID;
    NSString *_productVer;
    NSArray *_backgroudRPC;
}

+ (void)cancelAllRequest;
+ (void)requestRPC:(id)arg1 withCallback:(CDUnknownBlockType)arg2 onViewController:(id)arg3;
+ (int)currentEnv;
+ (void)setMYBankEnvironment:(int)arg1;
+ (id)sharedManager;
+ (void)setUserIdBlock:(CDUnknownBlockType)arg1;
+ (void)setDebugEnable:(_Bool)arg1;
+ (void)setProductID:(id)arg1 productVersion:(id)arg2;
+ (id)initWithAppKey:(id)arg1 withEnv:(int)arg2;
@property(retain, nonatomic) NSArray *backgroudRPC; // @synthesize backgroudRPC=_backgroudRPC;
@property(retain, nonatomic) NSString *productVer; // @synthesize productVer=_productVer;
@property(retain, nonatomic) NSString *productID; // @synthesize productID=_productID;
@property(nonatomic) _Bool isLogining; // @synthesize isLogining=_isLogining;
@property(nonatomic) _Bool hasLogined; // @synthesize hasLogined=_hasLogined;
@property(retain, nonatomic) NSMutableArray *pendingRPCCalls; // @synthesize pendingRPCCalls=_pendingRPCCalls;
@property(retain, nonatomic) id <MYBankLogin> loginMgr; // @synthesize loginMgr=_loginMgr;
- (void).cxx_destruct;
- (void)handleException:(id)arg1;
- (id)afterRpcOperation:(id)arg1;
- (id)beforeRpcOperation:(id)arg1;
- (void)finishLogin:(_Bool)arg1;
- (void)doLoginWith:(id)arg1;
- (id)descriptionForCode:(id)arg1 sysCode:(id)arg2;
- (void)showDescriptionWithInfo:(id)arg1;
- (void)requestRPCWithNode:(id)arg1;
- (void)processRPCWithNode:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

