//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSUserDefaults.h>

@interface NSUserDefaults (Backup)
+ (id)dt_currentBackupPath;
+ (void)dt_statisticsEvent:(id)arg1 args:(id)arg2;
+ (void)dt_verifyStandardUserDefaults;
+ (void)initialize;
- (void)dt_backupPlist;
- (void)dt_removePersistentDomainForName:(id)arg1;
- (_Bool)dt_synchronize;
@end

