//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSString, OpenDatabase;

@protocol OpenDatabaseDelegate <NSObject>

@optional
- (void)didFailedWithErrorCode:(int)arg1 database:(OpenDatabase *)arg2;
- (void)didFailedWithErrorCode:(int)arg1;
- (void)didRekeyDatabaseInPath:(NSString *)arg1;
- (void)willRekeyDatabaseInPath:(NSString *)arg1;
- (void)didRemoveDbFileInPath:(NSString *)arg1;
@end

