//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSIndexPath, NSString, PSTCollectionReusableView, PSTCollectionView, PSTCollectionViewCell;

@protocol PSTCollectionViewDataSource <NSObject>
- (PSTCollectionViewCell *)collectionView:(PSTCollectionView *)arg1 cellForItemAtIndexPath:(NSIndexPath *)arg2;
- (long long)collectionView:(PSTCollectionView *)arg1 numberOfItemsInSection:(long long)arg2;

@optional
- (PSTCollectionReusableView *)collectionView:(PSTCollectionView *)arg1 viewForSupplementaryElementOfKind:(NSString *)arg2 atIndexPath:(NSIndexPath *)arg3;
- (long long)numberOfSectionsInCollectionView:(PSTCollectionView *)arg1;
@end

