//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "CAAnimationDelegate-Protocol.h"

@class CAShapeLayer, NSString, NSTimer, UIImageView;

@interface SYWaterDropView : UIView <CAAnimationDelegate>
{
    _Bool _animationing;
    _Bool _isRefresh;
    float _centerX;
    float _waterTop;
    float _maxDropLength;
    float _radius;
    float _currentOffset;
    CAShapeLayer *_shapeLayer;
    CAShapeLayer *_lineLayer;
    UIImageView *_refreshView;
    CDUnknownBlockType _handleRefreshEvent;
    CAShapeLayer *_doudongLayer;
    NSTimer *_timer;
}

@property(retain, nonatomic) NSTimer *timer; // @synthesize timer=_timer;
@property(retain, nonatomic) CAShapeLayer *doudongLayer; // @synthesize doudongLayer=_doudongLayer;
@property(nonatomic) float currentOffset; // @synthesize currentOffset=_currentOffset;
@property(copy, nonatomic) CDUnknownBlockType handleRefreshEvent; // @synthesize handleRefreshEvent=_handleRefreshEvent;
@property(retain, nonatomic) UIImageView *refreshView; // @synthesize refreshView=_refreshView;
@property(retain, nonatomic) CAShapeLayer *lineLayer; // @synthesize lineLayer=_lineLayer;
@property(retain, nonatomic) CAShapeLayer *shapeLayer; // @synthesize shapeLayer=_shapeLayer;
- (void).cxx_destruct;
- (void)doudong;
- (void)startRefreshAnimation;
- (void)animationDidStop:(id)arg1 finished:(_Bool)arg2;
- (void)stopRefresh;
- (void)resetWater;
- (void)privateSetCurrentOffset:(float)arg1;
- (struct CGPath *)createPathWithOffset:(float)arg1;
- (void)loadWaterView;
- (void)parameterInit;
@property(readonly, nonatomic) _Bool isRefreshing;
- (struct CGSize)intrinsicContentSize;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

