//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface TBShortURLUtil : NSObject
{
}

+ (id)decodeShortUrl:(id)arg1 parseType:(unsigned long long)arg2 completionHandler:(CDUnknownBlockType)arg3;
+ (id)decodeUrlOffline:(id)arg1;
+ (id)encodeShortUrl:(id)arg1 parseType:(unsigned long long)arg2 completionHandler:(CDUnknownBlockType)arg3;
+ (id)encodeShortUrl:(id)arg1 parseType:(unsigned long long)arg2 timeout:(double)arg3 completionHandler:(CDUnknownBlockType)arg4;
+ (id)encodeUrlOffline:(id)arg1;

@end

