//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIImage.h>

@interface UIImage (YYImageCoder)
- (id)_imageDataRepresentationForSystem:(_Bool)arg1;
- (id)imageDataRepresentation;
- (void)saveToAlbumWithCompletionBlock:(CDUnknownBlockType)arg1;
@property(nonatomic) _Bool isDecodedForDisplay;
- (id)imageByDecoded;
@end

