//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UINavigationItem.h>

@interface UINavigationItem (BLExtension)
- (void)bl_setLeftBarButtonItem:(id)arg1;
- (void)bl_setLeftBarButtonItems:(id)arg1;
- (id)bl_iOS56FixedSpaceItem;
- (id)bl_iOS7RightFixedSpaceItem;
- (id)bl_iOS7FixedSpaceItem;
- (id)bl_fixedSpaceItem:(double)arg1;
- (void)transformArrowToUp:(_Bool)arg1 animated:(_Bool)arg2;
- (void)updateTitle:(id)arg1 style:(long long)arg2;
- (void)updateTitle:(id)arg1;
- (void)setTitle:(id)arg1 color:(id)arg2 fontSize:(double)arg3 style:(long long)arg4 target:(id)arg5 action:(SEL)arg6;
- (void)setTitle:(id)arg1 color:(id)arg2 style:(long long)arg3 target:(id)arg4 action:(SEL)arg5;
@end

