//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIPasteboard.h>

@class NSAttributedString, NSData;

@interface UIPasteboard (YYText)
@property(copy, nonatomic) NSAttributedString *attributedString;
@property(copy, nonatomic) NSData *imageData;
@property(copy, nonatomic) NSData *WEBPData;
@property(copy, nonatomic) NSData *GIFData;
@property(copy, nonatomic) NSData *JPEGData;
@property(copy, nonatomic) NSData *PNGData;
@end

