//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "Marshal.h"

@class NSNumber, NSString;

@interface WKIDLAutomaticIconModel : Marshal
{
    NSString *_automaticIconMediaId;
    NSNumber *_automaticIconTag;
}

@property(retain, nonatomic) NSNumber *automaticIconTag; // @synthesize automaticIconTag=_automaticIconTag;
@property(copy, nonatomic) NSString *automaticIconMediaId; // @synthesize automaticIconMediaId=_automaticIconMediaId;
- (void).cxx_destruct;
- (id)filedsMeta__;
- (id)init;

@end

