//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "Marshal.h"

@class NSNumber;

@interface WKIDLSessionInfoModel : Marshal
{
    _Bool _inProcess;
    _Bool _stopTrigger;
    NSNumber *_seq;
    NSNumber *_maxNotifyPts;
    NSNumber *_ackPts;
    NSNumber *_currentPts;
    NSNumber *_timestamp;
}

@property(retain, nonatomic) NSNumber *timestamp; // @synthesize timestamp=_timestamp;
@property(retain, nonatomic) NSNumber *currentPts; // @synthesize currentPts=_currentPts;
@property(retain, nonatomic) NSNumber *ackPts; // @synthesize ackPts=_ackPts;
@property(retain, nonatomic) NSNumber *maxNotifyPts; // @synthesize maxNotifyPts=_maxNotifyPts;
@property(retain, nonatomic) NSNumber *seq; // @synthesize seq=_seq;
@property(nonatomic) _Bool stopTrigger; // @synthesize stopTrigger=_stopTrigger;
@property(nonatomic) _Bool inProcess; // @synthesize inProcess=_inProcess;
- (void).cxx_destruct;
- (id)filedsMeta__;
- (id)init;

@end

