//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "Marshal.h"

@class NSDictionary, NSNumber, NSString;

@interface WKIDLPushTraceModel : Marshal
{
    NSString *_day;
    NSNumber *_level;
    NSNumber *_type;
    NSString *_bizType;
    NSNumber *_startTime;
    NSNumber *_endTime;
    NSString *_cmd;
    NSString *_parameter;
    NSNumber *_expireTime;
    NSDictionary *_callbackParams;
}

@property(copy, nonatomic) NSDictionary *callbackParams; // @synthesize callbackParams=_callbackParams;
@property(retain, nonatomic) NSNumber *expireTime; // @synthesize expireTime=_expireTime;
@property(copy, nonatomic) NSString *parameter; // @synthesize parameter=_parameter;
@property(copy, nonatomic) NSString *cmd; // @synthesize cmd=_cmd;
@property(retain, nonatomic) NSNumber *endTime; // @synthesize endTime=_endTime;
@property(retain, nonatomic) NSNumber *startTime; // @synthesize startTime=_startTime;
@property(copy, nonatomic) NSString *bizType; // @synthesize bizType=_bizType;
@property(retain, nonatomic) NSNumber *type; // @synthesize type=_type;
@property(retain, nonatomic) NSNumber *level; // @synthesize level=_level;
@property(copy, nonatomic) NSString *day; // @synthesize day=_day;
- (void).cxx_destruct;
- (id)filedsMeta__;
- (id)init;

@end

