//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "Marshal.h"

@class NSNumber;

@interface WKIDLFollowModel : Marshal
{
    NSNumber *_openId;
    NSNumber *_status;
    NSNumber *_tag;
    NSNumber *_lastModify;
}

@property(retain, nonatomic) NSNumber *lastModify; // @synthesize lastModify=_lastModify;
@property(retain, nonatomic) NSNumber *tag; // @synthesize tag=_tag;
@property(retain, nonatomic) NSNumber *status; // @synthesize status=_status;
@property(retain, nonatomic) NSNumber *openId; // @synthesize openId=_openId;
- (void).cxx_destruct;
- (id)filedsMeta__;
- (id)init;

@end

