//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SClient.h"

@interface WKIDLNotificationService : SClient
{
}

+ (id)_appname__;
+ (id)_serviceKey__;
- (void)setBadge:(id)arg1 callback:(id)arg2;
- (void)unbind:(id)arg1;
- (void)updateDeviceApnStatus:(id)arg1 deviceApnStatus:(id)arg2 callback:(id)arg3;
- (void)bindiOSWithPushKit:(id)arg1 appVersion:(id)arg2 pushKitDeviceToken:(id)arg3 callback:(id)arg4;
- (void)bindiOS:(id)arg1 appVersion:(id)arg2 callback:(id)arg3;
- (void)bindAnd:(id)arg1 system:(id)arg2 packageName:(id)arg3 callback:(id)arg4;

@end

