//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSMutableArray;

@interface WKMessageConvBatchSendInfo : NSObject
{
    _Bool _sending;
    NSMutableArray *_waitingSendMessages;
}

@property _Bool sending; // @synthesize sending=_sending;
@property(retain) NSMutableArray *waitingSendMessages; // @synthesize waitingSendMessages=_waitingSendMessages;
- (void).cxx_destruct;
- (id)init;

@end

