//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSString;
@protocol WKNoticeHandlerProtocol;

@protocol WKPushServiceProtocol <NSObject>
- (void)removeTopic:(NSString *)arg1;
- (void)registerNoticeHandler:(id <WKNoticeHandlerProtocol>)arg1 forTopic:(NSString *)arg2;
@end

