//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSString;

@interface WKVideoAttributeModel : NSObject
{
    _Bool _isShortVideo;
    long long _bitRate;
    long long _videoHeight;
    long long _videoWidth;
    long long _duration;
    unsigned long long _fileSize;
    NSString *_fileType;
    NSString *_fileName;
    NSString *_path;
    NSString *_videoMediaId;
    NSString *_picMediaId;
}

@property(nonatomic) _Bool isShortVideo; // @synthesize isShortVideo=_isShortVideo;
@property(copy, nonatomic) NSString *picMediaId; // @synthesize picMediaId=_picMediaId;
@property(copy, nonatomic) NSString *videoMediaId; // @synthesize videoMediaId=_videoMediaId;
@property(copy, nonatomic) NSString *path; // @synthesize path=_path;
@property(copy, nonatomic) NSString *fileName; // @synthesize fileName=_fileName;
@property(copy, nonatomic) NSString *fileType; // @synthesize fileType=_fileType;
@property(nonatomic) unsigned long long fileSize; // @synthesize fileSize=_fileSize;
@property(nonatomic) long long duration; // @synthesize duration=_duration;
@property(nonatomic) long long videoWidth; // @synthesize videoWidth=_videoWidth;
@property(nonatomic) long long videoHeight; // @synthesize videoHeight=_videoHeight;
@property(nonatomic) long long bitRate; // @synthesize bitRate=_bitRate;
- (void).cxx_destruct;

@end

