//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "YapDatabaseView.h"

@class NSString, YapDatabaseViewOptions;

@interface YapDatabaseFilteredView : YapDatabaseView
{
    id filteringBlock;
    long long filteringBlockType;
    NSString *parentViewName;
}

@property(readonly, nonatomic) NSString *parentViewName; // @synthesize parentViewName;
- (void).cxx_destruct;
- (void)getGroupingBlock:(id *)arg1 groupingBlockType:(long long *)arg2 sortingBlock:(id *)arg3 sortingBlockType:(long long *)arg4 filteringBlock:(id *)arg5 filteringBlockType:(long long *)arg6;
- (void)processChangeset:(id)arg1;
- (id)newConnection:(id)arg1;
- (id)dependencies;
- (_Bool)supportsDatabase:(id)arg1 withRegisteredExtensions:(id)arg2;
@property(readonly, nonatomic) long long filteringBlockType; // @synthesize filteringBlockType;
@property(readonly, nonatomic) id filteringBlock; // @synthesize filteringBlock;
- (id)initWithParentViewName:(id)arg1 filteringBlock:(id)arg2 filteringBlockType:(long long)arg3 versionTag:(id)arg4 options:(id)arg5;
- (id)initWithParentViewName:(id)arg1 filteringBlock:(id)arg2 filteringBlockType:(long long)arg3 versionTag:(id)arg4;
- (id)initWithParentViewName:(id)arg1 filteringBlock:(id)arg2 filteringBlockType:(long long)arg3;
- (id)initWithParentViewName:(id)arg1 filtering:(id)arg2 versionTag:(id)arg3 options:(id)arg4;
- (id)initWithParentViewName:(id)arg1 filtering:(id)arg2 versionTag:(id)arg3;
- (id)initWithParentViewName:(id)arg1 filtering:(id)arg2;
- (id)initWithGrouping:(id)arg1 sorting:(id)arg2 versionTag:(id)arg3 options:(id)arg4;

// Remaining properties
@property(readonly, copy, nonatomic) YapDatabaseViewOptions *options;

@end

