//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "YapDatabaseExtensionTransaction.h"

@class YapDatabaseReadTransaction, YapDatabaseRelationshipConnection;

@interface YapDatabaseRelationshipTransaction : YapDatabaseExtensionTransaction
{
    YapDatabaseRelationshipConnection *relationshipConnection;
    YapDatabaseReadTransaction *databaseTransaction;
    _Bool isFlushing;
}

- (void)removeEdge:(id)arg1 withProcessing:(long long)arg2;
- (void)removeEdgeWithName:(id)arg1 sourceKey:(id)arg2 collection:(id)arg3 destinationKey:(id)arg4 collection:(id)arg5 withProcessing:(long long)arg6;
- (void)addEdge:(id)arg1;
- (unsigned long long)edgeCountWithName:(id)arg1 sourceKey:(id)arg2 collection:(id)arg3 destinationFilePath:(id)arg4;
- (unsigned long long)edgeCountWithName:(id)arg1 sourceKey:(id)arg2 collection:(id)arg3 destinationKey:(id)arg4 collection:(id)arg5;
- (unsigned long long)edgeCountWithName:(id)arg1 destinationFilePath:(id)arg2;
- (unsigned long long)edgeCountWithName:(id)arg1 destinationKey:(id)arg2 collection:(id)arg3;
- (unsigned long long)edgeCountWithName:(id)arg1 sourceKey:(id)arg2 collection:(id)arg3;
- (unsigned long long)edgeCountWithName:(id)arg1;
- (void)enumerateEdgesWithName:(id)arg1 sourceKey:(id)arg2 collection:(id)arg3 destinationFilePath:(id)arg4 usingBlock:(CDUnknownBlockType)arg5;
- (void)enumerateEdgesWithName:(id)arg1 sourceKey:(id)arg2 collection:(id)arg3 destinationKey:(id)arg4 collection:(id)arg5 usingBlock:(CDUnknownBlockType)arg6;
- (void)enumerateEdgesWithName:(id)arg1 destinationFilePath:(id)arg2 usingBlock:(CDUnknownBlockType)arg3;
- (void)enumerateEdgesWithName:(id)arg1 destinationKey:(id)arg2 collection:(id)arg3 usingBlock:(CDUnknownBlockType)arg4;
- (void)enumerateEdgesWithName:(id)arg1 sourceKey:(id)arg2 collection:(id)arg3 usingBlock:(CDUnknownBlockType)arg4;
- (void)enumerateEdgesWithName:(id)arg1 usingBlock:(CDUnknownBlockType)arg2;
- (id)destinationNodeForEdge:(id)arg1;
- (id)sourceNodeForEdge:(id)arg1;
- (void)handleRemoveAllObjectsInAllCollections;
- (void)handleRemoveObjectsForKeys:(id)arg1 inCollection:(id)arg2 withRowids:(id)arg3;
- (void)handleRemoveObjectForCollectionKey:(id)arg1 withRowid:(long long)arg2;
- (void)handleTouchMetadataForCollectionKey:(id)arg1 withRowid:(long long)arg2;
- (void)handleTouchObjectForCollectionKey:(id)arg1 withRowid:(long long)arg2;
- (void)handleReplaceMetadata:(id)arg1 forCollectionKey:(id)arg2 withRowid:(long long)arg3;
- (void)handleReplaceObject:(id)arg1 forCollectionKey:(id)arg2 withRowid:(long long)arg3;
- (void)handleUpdateObject:(id)arg1 forCollectionKey:(id)arg2 withMetadata:(id)arg3 rowid:(long long)arg4;
- (void)handleInsertObject:(id)arg1 forCollectionKey:(id)arg2 withMetadata:(id)arg3 rowid:(long long)arg4;
- (void)rollbackTransaction;
- (void)commitTransaction;
- (_Bool)flushPendingChangesToMainDatabaseTable;
- (void)flush;
- (void)removeAllEdges;
- (void)removeAllProtocolEdges;
- (void)deleteEdgesWithSourceOrDestination:(long long)arg1;
- (void)deleteEdge:(id)arg1;
- (void)updateEdge:(id)arg1;
- (void)insertEdge:(id)arg1;
- (void)preprocessManualEdges:(id)arg1;
- (void)preprocessProtocolEdges:(id)arg1 forUpdatedSource:(id)arg2;
- (void)preprocessProtocolEdges:(id)arg1 forInsertedSource:(id)arg2;
- (id)findManualEdgeMatching:(id)arg1;
- (long long)edgeCountWithDestinationFilePath:(id)arg1 name:(id)arg2 excludingSource:(long long)arg3;
- (long long)edgeCountWithDestination:(long long)arg1 name:(id)arg2 excludingSource:(long long)arg3;
- (long long)edgeCountWithSource:(long long)arg1 name:(id)arg2 excludingDestination:(long long)arg3;
- (id)rowidNumberForDeletedKey:(id)arg1 inCollection:(id)arg2;
- (void)enumerateExistingEdgesWithDestination:(long long)arg1 usingBlock:(CDUnknownBlockType)arg2;
- (void)enumerateExistingEdgesWithSource:(long long)arg1 usingBlock:(CDUnknownBlockType)arg2;
- (id)findChangesMatchingName:(id)arg1 sourceKey:(id)arg2 collection:(id)arg3 rowid:(long long)arg4 destinationFilePath:(id)arg5;
- (id)findChangesMatchingName:(id)arg1 sourceKey:(id)arg2 collection:(id)arg3 rowid:(long long)arg4 destinationKey:(id)arg5 collection:(id)arg6 rowid:(long long)arg7;
- (id)findChangesMatchingName:(id)arg1 destinationFilePath:(id)arg2;
- (id)findChangesMatchingName:(id)arg1 destinationKey:(id)arg2 collection:(id)arg3 rowid:(long long)arg4;
- (id)findChangesMatchingName:(id)arg1 sourceKey:(id)arg2 collection:(id)arg3 rowid:(long long)arg4;
- (id)findChangesMatchingName:(id)arg1;
- (id)tableName;
- (id)registeredName;
- (id)extensionConnection;
- (id)databaseTransaction;
- (_Bool)populateTables;
- (_Bool)createTables;
- (_Bool)dropTable;
- (_Bool)prepareIfNeeded;
- (_Bool)createIfNeeded;
- (id)initWithRelationshipConnection:(id)arg1 databaseTransaction:(id)arg2;

@end

