//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class YapDatabaseConnection;
@protocol OS_dispatch_semaphore;

@interface YapDatabaseConnectionState : NSObject
{
    NSObject<OS_dispatch_semaphore> *writeSemaphore;
    YapDatabaseConnection *connection;
    _Bool yapLevelSharedReadLock;
    _Bool sqlLevelSharedReadLock;
    _Bool longLivedReadTransaction;
    _Bool yapLevelExclusiveWriteLock;
    _Bool waitingForWriteLock;
    unsigned long long lastKnownSnapshot;
}

- (void).cxx_destruct;
- (void)signalWriteLock;
- (void)waitForWriteLock;
- (void)prepareWriteLock;
- (void)dealloc;
- (id)initWithConnection:(id)arg1;

@end

