//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "NSFastEnumeration-Protocol.h"

@class NSDictionary, NSSet;

@interface YapSet : NSObject <NSFastEnumeration>
{
    NSDictionary *dictionary;
    NSSet *set;
}

- (void).cxx_destruct;
- (unsigned long long)countByEnumeratingWithState:(CDStruct_70511ce9 *)arg1 objects:(id *)arg2 count:(unsigned long long)arg3;
- (void)enumerateObjectsUsingBlock:(CDUnknownBlockType)arg1;
- (_Bool)intersectsSet:(id)arg1;
- (_Bool)containsObject:(id)arg1;
- (id)initWithDictionary:(id)arg1;
- (id)initWithSet:(id)arg1;

@end

